// Generated by hecks site site_projection.project_site. Do not edit.

// The domain's shape, read from its bluebook: every aggregate with its attributes, value objects,
// lifecycle, commands and queries. The pages, the forms and the input parser all read this one
// constant, so the editor can edit any aggregate; none of it is written by hand.

/** How an attribute's value is entered: `object` is a value object, the rest are single values. */
export type Kind = "text" | "integer" | "number" | "boolean" | "object" | "reference";

/**
 * What an attribute names: an instance of another aggregate, offered as a choice. `strict` pickers
 * accept only a key that exists; the others suggest and accept any text. `listing` is the query of
 * the target that lists what is on offer, or none to offer every instance. With `kinds`, the value is
 * `<kind>:<key>`: the kind is chosen first, then the record of the aggregate that kind names.
 */
export interface Picker {
  target?: string;
  /** The target's chapter, when the editor spans several or the target is in another. */
  chapter?: string;
  /** The target's identity attribute. */
  key?: string;
  /** The attribute that names an instance to a person (its title, name or label, else its identity). */
  label?: string;
  listing?: string;
  strict?: boolean;
  kinds?: PickerKind[];
}

/** One kind of a `<kind>:<key>` value, and the aggregate it names when it names one. */
export type PickerKind = Omit<Picker, "kinds"> & { kind: string };

export interface Attr {
  name: string;
  /** The type as the bluebook spells it ("String", "Byline"). */
  type: string;
  kind: Kind;
  optional: boolean;
  /** True for `list_of`: the attribute holds a list of `type`. */
  list: boolean;
  /**
   * `body` for an attribute whose value object has the shape of a structured document (blocks of
   * spans); `date` or `datetime` for whole seconds since 1970 that the names say are a moment.
   */
  widget?: "body" | "date" | "datetime";
  /** Set when the attribute names an instance of another aggregate of the editor. */
  picker?: Picker;
  /** The members of the closed set the attribute is one of, when its value object declares one. */
  options?: string[];
  /** The aggregate a `reference` points at. */
  target?: string;
}

export interface Transition {
  verb: string;
  from: string[];
  to: string;
}

export interface Lifecycle {
  field: string;
  default: string;
  transitions: Transition[];
  /** Each state's badge tone: `neutral`, `ok`, `info`, `warn` or `danger`. */
  tones: Record<string, string>;
}

export interface Command {
  name: string;
  goal: string | null;
  role: string | null;
  /** True when the command makes a new instance; false when it acts on one (`reference_to`). */
  creates: boolean;
  /** The aggregate the command acts on, when it is not a creating command. */
  on: string | null;
  /** True when the editor asks for confirmation before running it (see the generator's `Destructive`). */
  destructive: boolean;
  attributes: Attr[];
  /** The arguments that only clear a field and are not offered as inputs: sent as empty lists. */
  empty?: string[];
}

export interface Query {
  name: string;
  description: string | null;
  attributes: Attr[];
}

/**
 * A record of another aggregate that goes with this one's records, because its identity is a
 * `<kind>:<slug>` key of this aggregate. `shape` says how to show it; `create` and `edit` name the
 * commands that make and change it, when it has them.
 */
export interface Related {
  aggregate: string;
  chapter?: string;
  /** The related aggregate's identity attribute, which the key fills. */
  field: string;
  shape: "document" | "gallery" | "metadata";
  create?: string;
  edit?: string;
}

/** An aggregate that keeps a draft of a body beside the live one, and the commands that handle it. */
export interface Drafts {
  /** The draft attribute (`draft_body`) and the live one it stands for (`body`). */
  attribute: string;
  live: string;
  save: string;
  publish?: string;
  discard?: string;
}

export interface Aggregate {
  name: string;
  /** The chapter that declares the aggregate; set when the editor spans several. */
  chapter?: string;
  /** The roles that may edit it, when its chapter limits them; any admitted role otherwise. */
  roles?: string[];
  description: string | null;
  identity: string;
  lifecycle: Lifecycle | null;
  attributes: Attr[];
  valueObjects: Record<string, Attr[]>;
  commands: Command[];
  queries: Query[];
  /** The aggregates keyed by this one's records, shown as panels on a record's page. */
  related?: Related[];
  /** The draft the aggregate keeps beside a live body, when it keeps one. */
  drafts?: Drafts;
}

/** How one part of a picture's record is sent: `wrap` is the part of a value object that holds the value. */
export interface MediaField {
  name: string;
  wrap: string | null;
}

/** The aggregate that registers pictures, when the chapter has one: found by shape, never by name. */
export interface Media {
  aggregate: string;
  command: string;
  fields: { key: MediaField; alt: MediaField; mime: MediaField; width?: MediaField; height?: MediaField };
  /** The query that lists the pictures, or null when every instance is read. */
  listing: string | null;
  /** The chapter that holds the picture aggregate, when it is not this editor's own chapter. */
  domain?: string;
  /** That aggregate, which is then not among the editor's own; see `domain`. */
  definition?: Aggregate;
}

/**
 * The aggregate whose records are actions to run later, found by shape: the attribute that names the
 * record an action is for, the closed set of actions, the due time, and the commands. The editor only
 * makes and changes these records; something else runs them.
 */
export interface Scheduling {
  aggregate: string;
  chapter?: string;
  subject: string;
  action: string;
  actions: string[];
  due: string;
  /** The first state of a record: an action not yet run. */
  pending: string;
  schedule: string;
  reschedule?: string;
  cancel?: string;
  /** The query that lists the actions of one subject, when there is one. */
  query?: string;
  /** The optional text a record may carry to say why it ended as it did. */
  reason?: string;
  /** True when the editor makes the record's identity, since it is not the subject. */
  generated?: boolean;
}

export interface Schema {
  /** The first chapter, which names the domain the host is asked for. */
  domain: string;
  /** Every chapter, in the order the navigation groups them; set when the editor spans several. */
  chapters?: string[];
  aggregates: Aggregate[];
  media?: Media;
  scheduling?: Scheduling;
}

export const SCHEMA: Schema = {
  "domain": "Press",
  "aggregates": [
    {
      "name": "Article",
      "description": "One piece the publisher writes, from draft to archive.",
      "identity": "slug",
      "lifecycle": {
        "field": "status",
        "default": "draft",
        "transitions": [
          {
            "verb": "Publish",
            "from": [
              "draft"
            ],
            "to": "published"
          },
          {
            "verb": "Archive",
            "from": [
              "draft",
              "published"
            ],
            "to": "archived"
          },
          {
            "verb": "Restore",
            "from": [
              "archived"
            ],
            "to": "draft"
          }
        ],
        "tones": {
          "draft": "neutral",
          "published": "ok",
          "archived": "info"
        }
      },
      "attributes": [
        {
          "name": "slug",
          "type": "ArticleSlug",
          "kind": "object",
          "optional": false,
          "list": false
        },
        {
          "name": "headline",
          "type": "Headline",
          "kind": "object",
          "optional": false,
          "list": false
        },
        {
          "name": "standfirst",
          "type": "Standfirst",
          "kind": "object",
          "optional": true,
          "list": false
        },
        {
          "name": "byline",
          "type": "Byline",
          "kind": "object",
          "optional": false,
          "list": false
        },
        {
          "name": "tags",
          "type": "Tag",
          "kind": "object",
          "optional": false,
          "list": true
        },
        {
          "name": "sections",
          "type": "Section",
          "kind": "object",
          "optional": false,
          "list": true
        },
        {
          "name": "body",
          "type": "Body",
          "kind": "object",
          "optional": false,
          "list": false,
          "widget": "body"
        },
        {
          "name": "draft_body",
          "type": "Body",
          "kind": "object",
          "optional": true,
          "list": false,
          "widget": "body"
        }
      ],
      "valueObjects": {
        "ArticleSlug": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "Headline": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "Standfirst": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "Byline": [
          {
            "name": "name",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          },
          {
            "name": "contact",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "Tag": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "Link": [
          {
            "name": "label",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          },
          {
            "name": "url",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "Section": [
          {
            "name": "heading",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          },
          {
            "name": "links",
            "type": "Link",
            "kind": "object",
            "optional": false,
            "list": true
          }
        ],
        "Mark": [
          {
            "name": "name",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "Span": [
          {
            "name": "text",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          },
          {
            "name": "marks",
            "type": "Mark",
            "kind": "object",
            "optional": false,
            "list": true
          },
          {
            "name": "href",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false
          }
        ],
        "Item": [
          {
            "name": "spans",
            "type": "Span",
            "kind": "object",
            "optional": false,
            "list": true
          },
          {
            "name": "depth",
            "type": "Integer",
            "kind": "integer",
            "optional": true,
            "list": false
          },
          {
            "name": "list_kind",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false
          }
        ],
        "Block": [
          {
            "name": "kind",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          },
          {
            "name": "level",
            "type": "Integer",
            "kind": "integer",
            "optional": true,
            "list": false
          },
          {
            "name": "align",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false
          },
          {
            "name": "indent",
            "type": "Integer",
            "kind": "integer",
            "optional": true,
            "list": false
          },
          {
            "name": "spans",
            "type": "Span",
            "kind": "object",
            "optional": false,
            "list": true
          },
          {
            "name": "items",
            "type": "Item",
            "kind": "object",
            "optional": false,
            "list": true
          },
          {
            "name": "media_ref",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false
          },
          {
            "name": "alt",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false
          },
          {
            "name": "caption",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false
          }
        ],
        "Body": [
          {
            "name": "blocks",
            "type": "Block",
            "kind": "object",
            "optional": false,
            "list": true
          }
        ]
      },
      "commands": [
        {
          "name": "Draft",
          "goal": "Start an article the site does not show yet",
          "role": "Editor",
          "creates": true,
          "on": null,
          "destructive": false,
          "attributes": [
            {
              "name": "slug",
              "type": "ArticleSlug",
              "kind": "object",
              "optional": false,
              "list": false
            },
            {
              "name": "headline",
              "type": "Headline",
              "kind": "object",
              "optional": false,
              "list": false
            },
            {
              "name": "standfirst",
              "type": "Standfirst",
              "kind": "object",
              "optional": true,
              "list": false
            },
            {
              "name": "byline",
              "type": "Byline",
              "kind": "object",
              "optional": false,
              "list": false
            },
            {
              "name": "tags",
              "type": "Tag",
              "kind": "object",
              "optional": false,
              "list": true
            },
            {
              "name": "sections",
              "type": "Section",
              "kind": "object",
              "optional": false,
              "list": true
            },
            {
              "name": "body",
              "type": "Body",
              "kind": "object",
              "optional": false,
              "list": false,
              "widget": "body"
            }
          ]
        },
        {
          "name": "Revise",
          "goal": "Change an article's words",
          "role": "Editor",
          "creates": false,
          "on": "Article",
          "destructive": false,
          "attributes": [
            {
              "name": "headline",
              "type": "Headline",
              "kind": "object",
              "optional": false,
              "list": false
            },
            {
              "name": "standfirst",
              "type": "Standfirst",
              "kind": "object",
              "optional": true,
              "list": false
            },
            {
              "name": "byline",
              "type": "Byline",
              "kind": "object",
              "optional": false,
              "list": false
            },
            {
              "name": "tags",
              "type": "Tag",
              "kind": "object",
              "optional": false,
              "list": true
            },
            {
              "name": "sections",
              "type": "Section",
              "kind": "object",
              "optional": false,
              "list": true
            },
            {
              "name": "body",
              "type": "Body",
              "kind": "object",
              "optional": false,
              "list": false,
              "widget": "body"
            }
          ]
        },
        {
          "name": "SaveDraft",
          "goal": "Keep an edit aside until it is promoted",
          "role": "Editor",
          "creates": false,
          "on": "Article",
          "destructive": false,
          "attributes": [
            {
              "name": "draft_body",
              "type": "Body",
              "kind": "object",
              "optional": false,
              "list": false,
              "widget": "body"
            }
          ]
        },
        {
          "name": "PublishDraft",
          "goal": "Promote the saved edit to the article's body",
          "role": "Editor",
          "creates": false,
          "on": "Article",
          "destructive": false,
          "attributes": []
        },
        {
          "name": "DiscardDraft",
          "goal": "Throw the saved edit away",
          "role": "Editor",
          "creates": false,
          "on": "Article",
          "destructive": true,
          "attributes": []
        },
        {
          "name": "Publish",
          "goal": "Put a drafted article on the site",
          "role": "Editor",
          "creates": false,
          "on": "Article",
          "destructive": false,
          "attributes": []
        },
        {
          "name": "Archive",
          "goal": "Take an article off the site and out of the way",
          "role": "Editor",
          "creates": false,
          "on": "Article",
          "destructive": false,
          "attributes": []
        },
        {
          "name": "Restore",
          "goal": "Bring an archived article back as a draft",
          "role": "Editor",
          "creates": false,
          "on": "Article",
          "destructive": false,
          "attributes": []
        }
      ],
      "queries": [
        {
          "name": "Published",
          "description": "Every article the site shows.",
          "attributes": []
        },
        {
          "name": "ByHeadline",
          "description": "Articles with exactly this headline.",
          "attributes": [
            {
              "name": "headline",
              "type": "Headline",
              "kind": "object",
              "optional": false,
              "list": false
            }
          ]
        }
      ],
      "drafts": {
        "attribute": "draft_body",
        "live": "body",
        "save": "SaveDraft",
        "publish": "PublishDraft",
        "discard": "DiscardDraft"
      }
    },
    {
      "name": "Masthead",
      "description": "The publisher's name and contact: one row, no lifecycle.",
      "identity": "key",
      "lifecycle": null,
      "attributes": [
        {
          "name": "key",
          "type": "MastheadKey",
          "kind": "object",
          "optional": false,
          "list": false
        },
        {
          "name": "title",
          "type": "Title",
          "kind": "object",
          "optional": true,
          "list": false
        },
        {
          "name": "about",
          "type": "Statement",
          "kind": "object",
          "optional": true,
          "list": false,
          "widget": "body"
        }
      ],
      "valueObjects": {
        "MastheadKey": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "Title": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "Run": [
          {
            "name": "text",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "Piece": [
          {
            "name": "kind",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          },
          {
            "name": "spans",
            "type": "Run",
            "kind": "object",
            "optional": false,
            "list": true
          }
        ],
        "Statement": [
          {
            "name": "blocks",
            "type": "Piece",
            "kind": "object",
            "optional": false,
            "list": true
          }
        ]
      },
      "commands": [
        {
          "name": "Establish",
          "goal": "Set the masthead",
          "role": "Editor",
          "creates": true,
          "on": null,
          "destructive": false,
          "attributes": [
            {
              "name": "key",
              "type": "MastheadKey",
              "kind": "object",
              "optional": false,
              "list": false
            },
            {
              "name": "title",
              "type": "Title",
              "kind": "object",
              "optional": true,
              "list": false
            },
            {
              "name": "about",
              "type": "Statement",
              "kind": "object",
              "optional": true,
              "list": false,
              "widget": "body"
            }
          ]
        }
      ],
      "queries": []
    },
    {
      "name": "MediaItem",
      "description": "A picture the publisher has uploaded: its record only, the bytes are kept elsewhere.",
      "identity": "key",
      "lifecycle": null,
      "attributes": [
        {
          "name": "key",
          "type": "PictureKey",
          "kind": "object",
          "optional": false,
          "list": false
        },
        {
          "name": "alt",
          "type": "AltText",
          "kind": "object",
          "optional": false,
          "list": false
        },
        {
          "name": "mime_type",
          "type": "MimeType",
          "kind": "object",
          "optional": false,
          "list": false
        },
        {
          "name": "width",
          "type": "Pixels",
          "kind": "object",
          "optional": true,
          "list": false
        },
        {
          "name": "height",
          "type": "Pixels",
          "kind": "object",
          "optional": true,
          "list": false
        },
        {
          "name": "focal_point",
          "type": "FocalPoint",
          "kind": "object",
          "optional": true,
          "list": false
        }
      ],
      "valueObjects": {
        "PictureKey": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "AltText": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "MimeType": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "Pixels": [
          {
            "name": "value",
            "type": "Integer",
            "kind": "integer",
            "optional": false,
            "list": false
          }
        ],
        "FocalPoint": [
          {
            "name": "x",
            "type": "Float",
            "kind": "number",
            "optional": false,
            "list": false
          },
          {
            "name": "y",
            "type": "Float",
            "kind": "number",
            "optional": false,
            "list": false
          }
        ]
      },
      "commands": [
        {
          "name": "RegisterPicture",
          "goal": "Record a picture that has been uploaded",
          "role": "Editor",
          "creates": true,
          "on": null,
          "destructive": false,
          "attributes": [
            {
              "name": "key",
              "type": "PictureKey",
              "kind": "object",
              "optional": false,
              "list": false
            },
            {
              "name": "alt",
              "type": "AltText",
              "kind": "object",
              "optional": false,
              "list": false
            },
            {
              "name": "mime_type",
              "type": "MimeType",
              "kind": "object",
              "optional": false,
              "list": false
            },
            {
              "name": "width",
              "type": "Pixels",
              "kind": "object",
              "optional": true,
              "list": false
            },
            {
              "name": "height",
              "type": "Pixels",
              "kind": "object",
              "optional": true,
              "list": false
            },
            {
              "name": "focal_point",
              "type": "FocalPoint",
              "kind": "object",
              "optional": true,
              "list": false
            }
          ]
        }
      ],
      "queries": [
        {
          "name": "Pictures",
          "description": "Every registered picture.",
          "attributes": []
        }
      ]
    }
  ],
  "media": {
    "aggregate": "MediaItem",
    "command": "RegisterPicture",
    "fields": {
      "key": {
        "name": "key",
        "wrap": "value"
      },
      "alt": {
        "name": "alt",
        "wrap": "value"
      },
      "mime": {
        "name": "mime_type",
        "wrap": "value"
      },
      "width": {
        "name": "width",
        "wrap": "value"
      },
      "height": {
        "name": "height",
        "wrap": "value"
      }
    },
    "listing": "Pictures"
  }
};
