// Generated by hecks site site_projection.project_site. Do not edit.

// The domain's shape, read from its bluebook: every aggregate with its attributes, value objects,
// lifecycle, commands and queries. The pages, the forms and the input parser all read this one
// constant, so the editor can edit any aggregate; none of it is written by hand.

/** How an attribute's value is entered: `object` is a value object, the rest are single values. */
export type Kind = "text" | "integer" | "number" | "boolean" | "object" | "reference";

export interface Attr {
  name: string;
  /** The type as the bluebook spells it ("String", "Byline"). */
  type: string;
  kind: Kind;
  optional: boolean;
  /** True for `list_of`: the attribute holds a list of `type`. */
  list: boolean;
  /** `body` for an attribute whose value object has the shape of a structured document (blocks of spans). */
  widget?: "body";
  /** The aggregate a `reference` points at. */
  target?: string;
}

export interface Transition {
  verb: string;
  from: string[];
  to: string;
}

export interface Lifecycle {
  field: string;
  default: string;
  transitions: Transition[];
}

export interface Command {
  name: string;
  goal: string | null;
  role: string | null;
  /** True when the command makes a new instance; false when it acts on one (`reference_to`). */
  creates: boolean;
  /** The aggregate the command acts on, when it is not a creating command. */
  on: string | null;
  attributes: Attr[];
}

export interface Query {
  name: string;
  description: string | null;
  attributes: Attr[];
}

export interface Aggregate {
  name: string;
  description: string | null;
  identity: string;
  lifecycle: Lifecycle | null;
  attributes: Attr[];
  valueObjects: Record<string, Attr[]>;
  commands: Command[];
  queries: Query[];
}

/** How one part of a picture's record is sent: `wrap` is the part of a value object that holds the value. */
export interface MediaField {
  name: string;
  wrap: string | null;
}

/** The aggregate that registers pictures, when the chapter has one: found by shape, never by name. */
export interface Media {
  aggregate: string;
  command: string;
  fields: { key: MediaField; alt: MediaField; mime: MediaField; width?: MediaField; height?: MediaField };
  /** The query that lists the pictures, or null when every instance is read. */
  listing: string | null;
}

export interface Schema {
  domain: string;
  aggregates: Aggregate[];
  media?: Media;
}

export const SCHEMA: Schema = {
  "domain": "Press",
  "aggregates": [
    {
      "name": "Article",
      "description": "One piece the publisher writes, from draft to archive.",
      "identity": "slug",
      "lifecycle": {
        "field": "status",
        "default": "draft",
        "transitions": [
          {
            "verb": "Publish",
            "from": [
              "draft"
            ],
            "to": "published"
          },
          {
            "verb": "Archive",
            "from": [
              "draft",
              "published"
            ],
            "to": "archived"
          },
          {
            "verb": "Restore",
            "from": [
              "archived"
            ],
            "to": "draft"
          }
        ]
      },
      "attributes": [
        {
          "name": "slug",
          "type": "ArticleSlug",
          "kind": "object",
          "optional": false,
          "list": false
        },
        {
          "name": "headline",
          "type": "Headline",
          "kind": "object",
          "optional": false,
          "list": false
        },
        {
          "name": "standfirst",
          "type": "Standfirst",
          "kind": "object",
          "optional": true,
          "list": false
        },
        {
          "name": "byline",
          "type": "Byline",
          "kind": "object",
          "optional": false,
          "list": false
        },
        {
          "name": "tags",
          "type": "Tag",
          "kind": "object",
          "optional": false,
          "list": true
        },
        {
          "name": "sections",
          "type": "Section",
          "kind": "object",
          "optional": false,
          "list": true
        },
        {
          "name": "body",
          "type": "Body",
          "kind": "object",
          "optional": false,
          "list": false,
          "widget": "body"
        }
      ],
      "valueObjects": {
        "ArticleSlug": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "Headline": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "Standfirst": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "Byline": [
          {
            "name": "name",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          },
          {
            "name": "contact",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "Tag": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "Link": [
          {
            "name": "label",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          },
          {
            "name": "url",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "Section": [
          {
            "name": "heading",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          },
          {
            "name": "links",
            "type": "Link",
            "kind": "object",
            "optional": false,
            "list": true
          }
        ],
        "Mark": [
          {
            "name": "name",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "Span": [
          {
            "name": "text",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          },
          {
            "name": "marks",
            "type": "Mark",
            "kind": "object",
            "optional": false,
            "list": true
          },
          {
            "name": "href",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false
          }
        ],
        "Item": [
          {
            "name": "spans",
            "type": "Span",
            "kind": "object",
            "optional": false,
            "list": true
          },
          {
            "name": "depth",
            "type": "Integer",
            "kind": "integer",
            "optional": true,
            "list": false
          },
          {
            "name": "list_kind",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false
          }
        ],
        "Block": [
          {
            "name": "kind",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          },
          {
            "name": "level",
            "type": "Integer",
            "kind": "integer",
            "optional": true,
            "list": false
          },
          {
            "name": "align",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false
          },
          {
            "name": "indent",
            "type": "Integer",
            "kind": "integer",
            "optional": true,
            "list": false
          },
          {
            "name": "spans",
            "type": "Span",
            "kind": "object",
            "optional": false,
            "list": true
          },
          {
            "name": "items",
            "type": "Item",
            "kind": "object",
            "optional": false,
            "list": true
          },
          {
            "name": "media_ref",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false
          },
          {
            "name": "alt",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false
          },
          {
            "name": "caption",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false
          }
        ],
        "Body": [
          {
            "name": "blocks",
            "type": "Block",
            "kind": "object",
            "optional": false,
            "list": true
          }
        ]
      },
      "commands": [
        {
          "name": "Draft",
          "goal": "Start an article the site does not show yet",
          "role": "Editor",
          "creates": true,
          "on": null,
          "attributes": [
            {
              "name": "slug",
              "type": "ArticleSlug",
              "kind": "object",
              "optional": false,
              "list": false
            },
            {
              "name": "headline",
              "type": "Headline",
              "kind": "object",
              "optional": false,
              "list": false
            },
            {
              "name": "standfirst",
              "type": "Standfirst",
              "kind": "object",
              "optional": true,
              "list": false
            },
            {
              "name": "byline",
              "type": "Byline",
              "kind": "object",
              "optional": false,
              "list": false
            },
            {
              "name": "tags",
              "type": "Tag",
              "kind": "object",
              "optional": false,
              "list": true
            },
            {
              "name": "sections",
              "type": "Section",
              "kind": "object",
              "optional": false,
              "list": true
            },
            {
              "name": "body",
              "type": "Body",
              "kind": "object",
              "optional": false,
              "list": false,
              "widget": "body"
            }
          ]
        },
        {
          "name": "Revise",
          "goal": "Change an article's words",
          "role": "Editor",
          "creates": false,
          "on": "Article",
          "attributes": [
            {
              "name": "headline",
              "type": "Headline",
              "kind": "object",
              "optional": false,
              "list": false
            },
            {
              "name": "standfirst",
              "type": "Standfirst",
              "kind": "object",
              "optional": true,
              "list": false
            },
            {
              "name": "byline",
              "type": "Byline",
              "kind": "object",
              "optional": false,
              "list": false
            },
            {
              "name": "tags",
              "type": "Tag",
              "kind": "object",
              "optional": false,
              "list": true
            },
            {
              "name": "sections",
              "type": "Section",
              "kind": "object",
              "optional": false,
              "list": true
            },
            {
              "name": "body",
              "type": "Body",
              "kind": "object",
              "optional": false,
              "list": false,
              "widget": "body"
            }
          ]
        },
        {
          "name": "Publish",
          "goal": "Put a drafted article on the site",
          "role": "Editor",
          "creates": false,
          "on": "Article",
          "attributes": []
        },
        {
          "name": "Archive",
          "goal": "Take an article off the site and out of the way",
          "role": "Editor",
          "creates": false,
          "on": "Article",
          "attributes": []
        },
        {
          "name": "Restore",
          "goal": "Bring an archived article back as a draft",
          "role": "Editor",
          "creates": false,
          "on": "Article",
          "attributes": []
        }
      ],
      "queries": [
        {
          "name": "Published",
          "description": "Every article the site shows.",
          "attributes": []
        },
        {
          "name": "ByHeadline",
          "description": "Articles with exactly this headline.",
          "attributes": [
            {
              "name": "headline",
              "type": "Headline",
              "kind": "object",
              "optional": false,
              "list": false
            }
          ]
        }
      ]
    },
    {
      "name": "Masthead",
      "description": "The publisher's name and contact: one row, no lifecycle.",
      "identity": "key",
      "lifecycle": null,
      "attributes": [
        {
          "name": "key",
          "type": "MastheadKey",
          "kind": "object",
          "optional": false,
          "list": false
        },
        {
          "name": "title",
          "type": "Title",
          "kind": "object",
          "optional": true,
          "list": false
        },
        {
          "name": "about",
          "type": "Statement",
          "kind": "object",
          "optional": true,
          "list": false,
          "widget": "body"
        }
      ],
      "valueObjects": {
        "MastheadKey": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "Title": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "Run": [
          {
            "name": "text",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "Piece": [
          {
            "name": "kind",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          },
          {
            "name": "spans",
            "type": "Run",
            "kind": "object",
            "optional": false,
            "list": true
          }
        ],
        "Statement": [
          {
            "name": "blocks",
            "type": "Piece",
            "kind": "object",
            "optional": false,
            "list": true
          }
        ]
      },
      "commands": [
        {
          "name": "Establish",
          "goal": "Set the masthead",
          "role": "Editor",
          "creates": true,
          "on": null,
          "attributes": [
            {
              "name": "key",
              "type": "MastheadKey",
              "kind": "object",
              "optional": false,
              "list": false
            },
            {
              "name": "title",
              "type": "Title",
              "kind": "object",
              "optional": true,
              "list": false
            },
            {
              "name": "about",
              "type": "Statement",
              "kind": "object",
              "optional": true,
              "list": false,
              "widget": "body"
            }
          ]
        }
      ],
      "queries": []
    },
    {
      "name": "MediaItem",
      "description": "A picture the publisher has uploaded: its record only, the bytes are kept elsewhere.",
      "identity": "key",
      "lifecycle": null,
      "attributes": [
        {
          "name": "key",
          "type": "PictureKey",
          "kind": "object",
          "optional": false,
          "list": false
        },
        {
          "name": "alt",
          "type": "AltText",
          "kind": "object",
          "optional": false,
          "list": false
        },
        {
          "name": "mime_type",
          "type": "MimeType",
          "kind": "object",
          "optional": false,
          "list": false
        },
        {
          "name": "width",
          "type": "Pixels",
          "kind": "object",
          "optional": true,
          "list": false
        },
        {
          "name": "height",
          "type": "Pixels",
          "kind": "object",
          "optional": true,
          "list": false
        },
        {
          "name": "focal_point",
          "type": "FocalPoint",
          "kind": "object",
          "optional": true,
          "list": false
        }
      ],
      "valueObjects": {
        "PictureKey": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "AltText": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "MimeType": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "Pixels": [
          {
            "name": "value",
            "type": "Integer",
            "kind": "integer",
            "optional": false,
            "list": false
          }
        ],
        "FocalPoint": [
          {
            "name": "x",
            "type": "Float",
            "kind": "number",
            "optional": false,
            "list": false
          },
          {
            "name": "y",
            "type": "Float",
            "kind": "number",
            "optional": false,
            "list": false
          }
        ]
      },
      "commands": [
        {
          "name": "RegisterPicture",
          "goal": "Record a picture that has been uploaded",
          "role": "Editor",
          "creates": true,
          "on": null,
          "attributes": [
            {
              "name": "key",
              "type": "PictureKey",
              "kind": "object",
              "optional": false,
              "list": false
            },
            {
              "name": "alt",
              "type": "AltText",
              "kind": "object",
              "optional": false,
              "list": false
            },
            {
              "name": "mime_type",
              "type": "MimeType",
              "kind": "object",
              "optional": false,
              "list": false
            },
            {
              "name": "width",
              "type": "Pixels",
              "kind": "object",
              "optional": true,
              "list": false
            },
            {
              "name": "height",
              "type": "Pixels",
              "kind": "object",
              "optional": true,
              "list": false
            },
            {
              "name": "focal_point",
              "type": "FocalPoint",
              "kind": "object",
              "optional": true,
              "list": false
            }
          ]
        }
      ],
      "queries": [
        {
          "name": "Pictures",
          "description": "Every registered picture.",
          "attributes": []
        }
      ]
    }
  ],
  "media": {
    "aggregate": "MediaItem",
    "command": "RegisterPicture",
    "fields": {
      "key": {
        "name": "key",
        "wrap": "value"
      },
      "alt": {
        "name": "alt",
        "wrap": "value"
      },
      "mime": {
        "name": "mime_type",
        "wrap": "value"
      },
      "width": {
        "name": "width",
        "wrap": "value"
      },
      "height": {
        "name": "height",
        "wrap": "value"
      }
    },
    "listing": "Pictures"
  }
};
