require_relative "../projector"
require_relative "diagrams/structure"
require_relative "diagrams/dispatch"
require_relative "diagrams/statecharts"

module Hecks
  module Projections
    # Projects a domain's declaration as Mermaid diagrams, one file per diagram kind.
    # Mermaid is plain text that renders in GitHub markdown with no build step or binary.
    module Diagrams
      extend Hecks::Projector::Target

      projects_as :diagrams, emits: :files

      module_function

      # Projects one domain's whole shape into every diagram kind it has data
      # for, one Mermaid file per entry.
      #
      # @param bluebook [Bluebook::Chapter] the assembled chapter to project
      # @param options [Hash{Symbol => Object}] projection options; only `:hecksagon`
      #   (a `Bluebook::Hecksagon`, or `nil`) is read, and only by `frameworks_diagram`
      # @return [Hash{String => String}] each diagram's filename (such as
      #   `"relationships.mmd"`) mapped to its rendered Mermaid source
      def call(bluebook:, options: {})
        files = lifecycle_files(bluebook)
        files.merge!(whole_domain_files(bluebook))
        files.merge!(surface_files(bluebook))
        files.merge!(saga_files(bluebook))
        files.merge!({ "frameworks.mmd" => frameworks_diagram(bluebook, options[:hecksagon]) }.compact)
      end

      # Every aggregate and entity in this domain, flattened into one list.
      def holders(bluebook)
        bluebook.aggregates.flat_map { |aggregate| [aggregate, *aggregate.entities] }
      end

      def holders_with_lifecycle(bluebook) = holders(bluebook).select(&:lifecycle)

      # `chapter_name` drives the re-run hint: `hecks project_diagrams` takes a chapter
      # name, not the subject's.
      def header(chapter_name, subject)
        <<~HEADER
          %% GENERATED by hecks project_diagrams from #{subject} — DO NOT EDIT BY HAND.
          %% Re-run `hecks project_diagrams <domain-path> #{chapter_name}` after any change.
        HEADER
      end

      # The header and a left-to-right flowchart of the distinct `lines`.
      def flowchart(bluebook, subject, lines)
        "#{header(bluebook.name, subject)}flowchart LR\n#{lines.uniq.join("\n")}\n"
      end

      def lifecycle_files(bluebook)
        holders_with_lifecycle(bluebook).to_h do |holder|
          ["#{holder.hecks_name}_lifecycle.mmd", Statecharts.lifecycle_diagram(bluebook, holder)]
        end
      end

      # The diagrams of which there is at most one a domain, left out when it has no data for them.
      def whole_domain_files(bluebook)
        { "relationships.mmd" => Structure.relationship_diagram(bluebook),
          "dispatch.mmd"      => Dispatch.dispatch_diagram(bluebook),
          "roles.mmd"         => Structure.roles_diagram(bluebook),
          "ports.mmd"         => Structure.ports_diagram(bluebook),
          "read_models.mmd"   => Structure.read_model_diagram(bluebook) }.compact
      end

      def surface_files(bluebook)
        surfaced = holders(bluebook).reject { |holder| holder.commands.empty? && holder.queries.empty? }
        surfaced.to_h { |holder| ["#{holder.hecks_name}_surface.mmd", Dispatch.surface_diagram(bluebook, holder)] }
      end

      def saga_files(bluebook)
        bluebook.process_managers.to_h { |saga| ["#{saga.hecks_name}_saga.mmd", Statecharts.saga_diagram(bluebook, saga)] }
      end

      # `hecksagon` is a separate argument because `bluebook` carries no reference to it;
      # without one there is no frameworks diagram.
      def frameworks_diagram(bluebook, hecksagon)
        return nil unless hecksagon

        lines = framework_edges(bluebook, hecksagon)
        return nil if lines.empty?

        flowchart(bluebook, "#{bluebook.name}'s own declared attaches and cross-domain policy targets", lines)
      end

      def framework_edges(bluebook, hecksagon)
        attached = hecksagon.member_chapters.map { |name| domain_edge(bluebook.name, "attaches", name, dotted: true) }
        attached + bluebook.policies.filter_map(&:target_domain).uniq
                           .map { |name| domain_edge(bluebook.name, "reaches across", name, dotted: false) }
      end

      def domain_edge(from, label, to, dotted:)
        arrow = dotted ? "-.->" : "-->"
        %(    #{from}[(#{from})] #{arrow}|#{label}| #{to}[(#{to})])
      end
    end
  end
end
