require_relative "../projector"

module Hecks
  module Projections
    # The Rust parser's keyword table, projected from the chapter's own Syntax aggregate,
    # so the parser's grammar knowledge is derived rather than hand-typed a second time.
    module ParserTable
      extend Projector::Target
      projects_as :parser_table, declares: "Syntax"

      module_function

      # Projects the Rust parser's keyword and closed-set tables for one chapter.
      #
      # @param bluebook [Bluebook::Chapter] the chapter to project; the language's own
      #   for the ordinary `bin/project_parser_table` run
      # @param options [Hash{Symbol => Object}] ignored; present to satisfy the
      #   `Projector::Target` calling convention
      # @return [String] the rendered Rust source
      def call(bluebook:, options: {}) = render(bluebook)

      module_function

      # The chapter's `Syntax` aggregate. Taken from the argument, not the grammar registry,
      # so the projection is not pinned to the language's own chapter.
      #
      # @param bluebook [Bluebook::Chapter] the chapter to read the Syntax aggregate
      #   from
      # @return [Bluebook::Aggregate, nil] the chapter's `"Syntax"` aggregate, `nil` if
      #   it declares none
      def syntax(bluebook) = bluebook.aggregate("Syntax")

      # Every cell as text, as spec/syntax_conformance_spec.rb's `rows` helper reads it.
      #
      # @param bluebook [Bluebook::Chapter] the chapter to read from
      # @param name [String] the closed-set value object's name, such as `"Context"`
      # @return [Array<Hash{Symbol => String}>] one row per declared member, every
      #   field stringified
      def rows(bluebook, name)
        syntax(bluebook).value_objects.find { |vo| vo.hecks_name == name }
              .members.map { |row| row.to_h.transform_values(&:to_s) }
      end

      # Reads one closed set's member names, for a Rust `&[&str]` constant.
      #
      # @param bluebook [Bluebook::Chapter] the chapter to read from
      # @param name [String] the closed-set value object's name
      # @return [Array<String>] every declared member's `:name` field
      def closed_set_members(bluebook, name) = rows(bluebook, name).map { |row| row[:name] }

      KEYWORD_FIELDS  = %i[word context body inner opens fills status was resolves_via disambiguator].freeze
      ARGUMENT_FIELDS = %i[keyword context at named kind required fills selects
                           pair_key_fills pair_value_fills pairs_shape status variadic minimum].freeze

      # A Rust string literal for one field's value. Fields are plain ASCII, so only
      # the backslash and double quote need escaping.
      #
      # @param value [Object] the field value to render; stringified before escaping
      # @return [String] a quoted Rust string literal
      def rust_string(value) = "\"#{value.to_s.gsub('\\', '\\\\\\\\').gsub('"', '\\"')}\""

      # Renders one `KEYWORDS` table entry.
      #
      # @param row [Hash{Symbol => String}] one keyword row, keyed by `KEYWORD_FIELDS`
      # @return [String] one `KeywordRow { ... },` line
      def keyword_row(row)
        fields = KEYWORD_FIELDS.map { |field| rust_string(row[field]) }
        "    KeywordRow { #{KEYWORD_FIELDS.zip(fields).map { |name, value| "#{name}: #{value}" }.join(', ')} },"
      end

      # Renders one `ARGUMENTS` table entry.
      #
      # @param row [Hash{Symbol => String}] one argument row, keyed by `ARGUMENT_FIELDS`
      # @return [String] one `ArgumentRow { ... },` line
      def argument_row(row)
        fields = ARGUMENT_FIELDS.map { |field| rust_string(row[field]) }
        "    ArgumentRow { #{ARGUMENT_FIELDS.zip(fields).map { |name, value| "#{name}: #{value}" }.join(', ')} },"
      end

      # Renders one `pub static NAME: &[&str]` constant.
      #
      # @param name [String] the Rust constant's name
      # @param values [Array<String>] the constant's member strings
      # @return [String] the rendered `pub static` declaration
      def const_str_array(name, values)
        lines = values.map { |value| "    #{rust_string(value)}," }
        "pub static #{name}: &[&str] = &[\n#{lines.join("\n")}\n];\n"
      end

      # Renders the whole Rust source. Keyword and Argument rows come from `SyntaxBoot.call`,
      # which dispatches the seed rows so `status` is a real lifecycle (ADR 0026).
      #
      # @param bluebook [Bluebook::Chapter] the chapter to project
      # @return [String] the rendered `KEYWORDS`/`ARGUMENTS`/closed-set Rust source
      def render(bluebook)
        table     = Hecks::Bluebook::MetaValidator::SyntaxBoot.call
        keywords  = table[:keywords]
        arguments = table[:arguments]

        <<~RUST
          // GENERATED by bin/project_parser_table from
          // aggregate-local syntax tables under lib/hecks/language/ — DO NOT EDIT BY HAND.
          //
          // Re-run `bin/project_parser_table` after any syntax-table change.
          // spec/parser_table_spec.rb regenerates this into memory and fails the
          // normal `bundle exec rspec` suite the moment this file drifts from what
          // the language currently declares — see that spec and
          // bin/project_parser_table's own header for why this file is never
          // hand-edited.

          #[derive(Debug, Clone, Copy)]
          pub struct KeywordRow {
              pub word: &'static str,
              pub context: &'static str,
              pub body: &'static str,
              pub inner: &'static str,
              pub opens: &'static str,
              pub fills: &'static str,
              pub status: &'static str,
              pub was: &'static str,
              /// Which shared Hecks::Bluebook::DSL::RuleReference
              /// primitive this word's own bare form resolves through,
              /// once it has one ("hash_chain" / "owner_keyed" /
              /// "sibling_scan") — "" for every word that only ever
              /// declares.
              pub resolves_via: &'static str,
              /// Which disambiguator keyword argument a bare reference
              /// may supply — "declared_by" today, "" otherwise.
              pub disambiguator: &'static str,
          }

          #[derive(Debug, Clone, Copy)]
          pub struct ArgumentRow {
              pub keyword: &'static str,
              pub context: &'static str,
              pub at: &'static str,
              pub named: &'static str,
              pub kind: &'static str,
              pub required: &'static str,
              pub fills: &'static str,
              pub selects: &'static str,
              pub pair_key_fills: &'static str,
              pub pair_value_fills: &'static str,
              pub pairs_shape: &'static str,
              pub status: &'static str,
              pub variadic: &'static str,
              pub minimum: &'static str,
          }

          impl KeywordRow {
              /// An absent status reads as admitted — the grown-column convention
              /// syntax_conformance_spec.rb's own `status_of`/`live?` already use.
              pub fn live(&self) -> bool {
                  matches!(self.status, "" | "admitted" | "deprecated")
              }
          }

          impl ArgumentRow {
              pub fn live(&self) -> bool {
                  matches!(self.status, "" | "admitted" | "deprecated")
              }
          }

          pub static KEYWORDS: &[KeywordRow] = &[
          #{keywords.map { |row| keyword_row(row) }.join("\n")}
          ];

          pub static ARGUMENTS: &[ArgumentRow] = &[
          #{arguments.map { |row| argument_row(row) }.join("\n")}
          ];

          #{const_str_array('CONTEXTS', closed_set_members(bluebook, 'Context'))}
          #{const_str_array('BODIES', closed_set_members(bluebook, 'Body'))}
          #{const_str_array('ARGUMENT_KINDS', closed_set_members(bluebook, 'ArgumentKind'))}
          #{const_str_array('PAIRS_SHAPES', closed_set_members(bluebook, 'PairsShape'))}
          #{const_str_array('STATUSES', closed_set_members(bluebook, 'Status'))}
        RUST
      end
    end
  end
end
