require_relative "../projector"
require_relative "vocabulary"

module Hecks
  module Projections
    # The language's closed sets, projected into the Rust kernel — one
    # `rust/src/kernel/vocab/<table>.rs` per Vocabulary table, each a
    # `pub enum` plus `match`-based accessors with no wildcard arm, so a
    # row the chapter gains is a compile error at every exhaustive match
    # over it rather than a silent gap.
    #
    #   Projector.call(:rust_vocabulary, bluebook: <the Bluebook chapter>)
    #   # => { "vocab/mod.rs" => "...", "vocab/refusal_template.rs" => "...", ... }
    #
    # Paths are relative to rust/src/kernel/; bin/project_rust_vocabulary
    # writes them. This generalizes the old bin/project_refusal_wording,
    # which read Runtime::RefusalWording::TEMPLATES — a hand-typed copy of
    # the RefusalTemplate rows. This reads the chapter itself.
    #
    # Only TABLES the kernel needs. Each entry in TABLES names its enum
    # and its generated extras; a table not listed is not projected. The
    # enum names that differ from the table name keep existing Rust call
    # sites (`RefusalSite`) and the dispatch-step names D1 consumes
    # (`AggregateStep`, `EntityStep`).
    module RustVocabulary
      extend Projector::Target

      projects_as :rust_vocabulary, declares: "Vocabulary", emits: :files

      GENERATOR = "bin/project_rust_vocabulary".freeze
      SOURCE    = "lib/hecks/language/bluebook/vocabulary.bluebook".freeze

      # table name => enum name, variant-naming fields, file stem, kind.
      # `:order` tables also get `ORDER` and `position`; `:templates`
      # gets `render` and the placeholder sweep test.
      TABLES = {
        "RefusalTemplate"        => { enum: "RefusalSite",     variant_from: %w[refusal site], file: "refusal_template",
                                      kind: :templates },
        "QueryComparator"        => { enum: "QueryComparator", variant_from: %w[name], file: "query_comparator", kind: :set },
        "FieldHint"              => { enum: "FieldHint",       variant_from: %w[name], file: "field_hint", kind: :set },
        "AggregateDispatchOrder" => { enum: "AggregateStep",   variant_from: %w[step], file: "aggregate_dispatch_order",
                                      kind: :order },
        "EntityDispatchOrder"    => { enum: "EntityStep",      variant_from: %w[step], file: "entity_dispatch_order",
                                      kind: :order }
      }.freeze

      module_function

      def call(bluebook:, options: {}) = render(bluebook)

      def render(bluebook)
        tables = Vocabulary.tables(bluebook)
        files = TABLES.to_h do |table, spec|
          rows = tables.fetch(table) { raise ArgumentError, "Vocabulary declares no #{table} table" }
          ["vocab/#{spec[:file]}.rs", table_file(table, spec, rows)]
        end
        { "vocab/mod.rs" => mod_file }.merge(files)
      end

      def header(table)
        <<~RUST
          // GENERATED by #{GENERATOR} (Hecks::Projections::RustVocabulary,
          // lib/hecks/projections/rust_vocabulary.rb) from Vocabulary::#{table}
          // (#{SOURCE}).
          // Do not hand-edit — re-run #{GENERATOR} instead.
        RUST
      end

      def mod_file
        mods    = TABLES.values.map { |spec| "pub mod #{spec[:file]};" }.join("\n")
        exports = TABLES.values.map { |spec| "pub use #{spec[:file]}::#{spec[:enum]};" }.join("\n")
        <<~RUST
          // GENERATED by #{GENERATOR} (Hecks::Projections::RustVocabulary,
          // lib/hecks/projections/rust_vocabulary.rb) from the Vocabulary
          // aggregate (#{SOURCE}).
          // Do not hand-edit — re-run #{GENERATOR} instead.
          //
          // One module per projected table. Every enum below is matched
          // exhaustively by its own accessors — no wildcard arm — so a row the
          // language gains fails to compile until it is handled.

          #{mods}

          #{exports}
        RUST
      end

      def table_file(table, spec, rows)
        variants = rows.map { |row| variant_name(row, spec[:variant_from]) }
        duplicates = variants.tally.select { |_, count| count > 1 }.keys
        raise ArgumentError, "duplicate #{spec[:enum]} variant(s): #{duplicates.join(', ')}" if duplicates.any?

        enum   = spec[:enum]
        fields = rows.first.keys
        body = [
          header(table),
          "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]",
          "pub enum #{enum} {",
          variants.map { |variant| "    #{variant}," },
          "}",
          "",
          "impl #{enum} {",
          constants(enum, variants, spec[:kind]),
          fields.map { |field| accessor(enum, field, variants, rows) },
          from_name(enum, spec[:kind]),
          extras(enum, variants, spec[:kind]),
          "}",
          "",
          tests(enum, spec[:kind])
        ]
        "#{body.flatten.join("\n").rstrip}\n"
      end

      def constants(enum, variants, kind)
        list = variants.map { |variant| "        #{enum}::#{variant}," }
        if kind == :order
          ["    /// The declared step order, first to last.",
           "    pub const ORDER: [#{enum}; #{variants.size}] = [", list, "    ];", ""]
        else
          ["    /// Every row, in declared order.",
           "    pub const ALL: &'static [#{enum}] = &[", list, "    ];", ""]
        end
      end

      def accessor(enum, field, variants, rows)
        arms = variants.zip(rows).map { |variant, row| "            #{enum}::#{variant} => #{rust_string(row.fetch(field))}," }
        ["    /// The row's declared `#{field}`.",
         "    pub fn #{accessor_name(field)}(&self) -> &'static str {",
         "        match self {",
         arms,
         "        }",
         "    }",
         ""]
      end

      # Built on the enum's own list and name accessor, not a string
      # match, so it needs no wildcard arm either.
      def from_name(enum, kind)
        list  = kind == :order ? "ORDER" : "ALL"
        field = kind == :templates ? "site" : name_field(kind)
        ["    /// The row whose `#{field}` is `name`, if any.",
         "    pub fn from_name(name: &str) -> Option<#{enum}> {",
         "        #{enum}::#{list}.iter().copied().find(|row| row.#{accessor_name(field)}() == name)",
         "    }",
         ""]
      end

      def extras(enum, variants, kind)
        case kind
        when :order
          arms = variants.each_with_index.map { |variant, index| "            #{enum}::#{variant} => #{index}," }
          ["    /// This step's index in `ORDER`.",
           "    pub fn position(&self) -> usize {",
           "        match self {",
           arms,
           "        }",
           "    }"]
        when :templates
          ["    /// `RefusalWording.render`: replace every `{key}` marker, in the",
           "    /// order given. A template is read, never evaluated.",
           "    pub fn render(&self, values: &[(&str, &str)]) -> String {",
           "        let mut text = self.template().to_string();",
           "        for (key, value) in values {",
           "            text = text.replace(&format!(\"{{{key}}}\"), value);",
           "        }",
           "        text",
           "    }"]
        else
          []
        end
      end

      def tests(enum, kind)
        list = kind == :order ? "ORDER" : "ALL"
        name = accessor_name(kind == :templates ? "site" : name_field(kind))
        lines = ["#[cfg(test)]",
                 "mod tests {",
                 "    use super::*;",
                 ""]
        unless kind == :templates
          lines += ["    #[test]",
                    "    fn every_row_is_found_by_its_own_name() {",
                    "        for row in #{enum}::#{list}.iter() {",
                    "            assert_eq!(#{enum}::from_name(row.#{name}()), Some(*row));",
                    "        }",
                    "    }",
                    ""]
        end
        lines += order_test(enum) if kind == :order
        lines += placeholder_test(enum) if kind == :templates
        lines.pop while lines.last == ""
        lines + ["}"]
      end

      def order_test(enum)
        ["    #[test]",
         "    fn position_is_the_index_in_order() {",
         "        for (index, step) in #{enum}::ORDER.iter().enumerate() {",
         "            assert_eq!(step.position(), index);",
         "        }",
         "    }",
         ""]
      end

      # Placeholders are read off each template's own text, never a second
      # hand-kept list.
      def placeholder_test(enum)
        ["    #[test]",
         "    fn every_site_renders_with_no_leftover_placeholder() {",
         "        for site in #{enum}::ALL {",
         "            let template = site.template();",
         "            let mut keys: Vec<String> = Vec::new();",
         "            let mut current: Option<String> = None;",
         "            for ch in template.chars() {",
         "                match (ch, current.as_mut()) {",
         "                    ('{', _) => current = Some(String::new()),",
         "                    ('}', Some(key)) => {",
         "                        keys.push(key.clone());",
         "                        current = None;",
         "                    }",
         "                    (_, Some(key)) => key.push(ch),",
         "                    (_, None) => {}",
         "                }",
         "            }",
         "            let dummies: Vec<(String, String)> = keys.iter().map(|k| (k.clone(), format!(\"<{k}>\"))).collect();",
         "            let pairs: Vec<(&str, &str)> = dummies.iter().map(|(k, v)| (k.as_str(), v.as_str())).collect();",
         "            let rendered = site.render(&pairs);",
         "            assert!(",
         "                !rendered.contains('{') && !rendered.contains('}'),",
         "                \"{site:?} left an unrendered placeholder behind: {rendered:?}\"",
         "            );",
         "        }",
         "    }"]
      end

      def name_field(kind) = kind == :order ? "step" : "name"

      # `refusal` is a Rust-safe word but reads ambiguously beside the
      # kernel's own `Refusal` enum; the accessor says what it answers.
      def accessor_name(field) = field == "refusal" ? "refusal_class" : field

      def variant_name(row, fields)
        name = fields.map { |field| pascal(row.fetch(field)) }.join
        raise ArgumentError, "#{name.inspect} is not a Rust variant name" unless name.match?(/\A[A-Z][A-Za-z0-9]*\z/)

        name
      end

      def pascal(text) = text.to_s.split("_").map { |part| part[0].to_s.upcase + part[1..].to_s }.join

      # A Rust string literal: only `\`, `"` and newlines need escaping in
      # the text any vocabulary row holds.
      def rust_string(text)
        escaped = text.to_s.gsub("\\") { "\\\\" }.gsub('"') { "\\\"" }.gsub("\n") { "\\n" }
        "\"#{escaped}\""
      end
    end
  end
end
