require_relative "../projector"
require_relative "../runtime/refusal_wording"
require_relative "vocabulary"
require_relative "rust_vocabulary/enum_body"
require_relative "rust_vocabulary/arguments"
require_relative "rust_vocabulary/tests"

module Hecks
  module Projections
    # The language's closed sets as Rust enums, one `rust/src/kernel/vocab/<table>.rs` per table,
    # matched with no wildcard arm so a new row fails to compile until it is handled.
    #
    #   Projector.call(:rust_vocabulary, bluebook: <the Bluebook chapter>)
    #   # => { "vocab/mod.rs" => "...", "vocab/refusal_template.rs" => "...", ... }
    module RustVocabulary
      extend Projector::Target

      projects_as :rust_vocabulary, declares: "Vocabulary", emits: :files

      GENERATOR = "hecks project_rust_vocabulary".freeze
      SOURCE    = "lib/hecks/language/bluebook/vocabulary.bluebook".freeze

      # Table name => enum name, variant-naming fields, file stem and kind.
      # `:order` adds `position`; `:templates` adds `render` and the typed `<Variant>Args`.
      TABLES = {
        "RefusalTemplate"        => { enum: "RefusalSite",     variant_from: %w[refusal site], file: "refusal_template",
                                      kind: :templates, arguments: "RefusalSiteArgument" },
        "QueryComparator"        => { enum: "QueryComparator", variant_from: %w[name], file: "query_comparator", kind: :set },
        "FieldHint"              => { enum: "FieldHint",       variant_from: %w[name], file: "field_hint", kind: :set },
        "AggregateDispatchOrder" => { enum: "AggregateStep",   variant_from: %w[step], file: "aggregate_dispatch_order",
                                      kind: :order },
        "EntityDispatchOrder"    => { enum: "EntityStep",      variant_from: %w[step], file: "entity_dispatch_order",
                                      kind: :order }
      }.freeze

      RUST_KEYWORDS = %w[as async await break const continue crate dyn else enum extern false fn for if impl in let loop
                         match mod move mut pub ref return self static struct super trait true type unsafe use where
                         while abstract become box do final macro override priv typeof unsized virtual yield try].freeze

      module_function

      def call(bluebook:, options: {}) = render(bluebook)

      def render(bluebook)
        tables = Vocabulary.tables(bluebook)
        files = TABLES.to_h do |table, spec|
          rows = tables.fetch(table) { raise ArgumentError, "Vocabulary declares no #{table} table" }
          arguments = spec[:arguments] && tables.fetch(spec[:arguments]) do
            raise ArgumentError, "Vocabulary declares no #{spec[:arguments]} table"
          end
          ["vocab/#{spec[:file]}.rs", table_file(table, spec, rows, arguments)]
        end
        { "vocab/mod.rs" => mod_file }.merge(files)
      end

      def header(table)
        <<~RUST
          // GENERATED by #{GENERATOR} (Hecks::Projections::RustVocabulary,
          // lib/hecks/projections/rust_vocabulary.rb) from Vocabulary::#{table}
          // (#{SOURCE}).
          // Do not hand-edit — re-run #{GENERATOR} instead.
        RUST
      end

      def mod_file
        mods    = TABLES.values.map { |spec| "pub mod #{spec[:file]};" }.join("\n")
        exports = TABLES.values.map { |spec| "pub use #{spec[:file]}::#{spec[:enum]};" }.join("\n")
        "#{mod_banner}\n#{mods}\n\n#{exports}\n"
      end

      def mod_banner
        <<~RUST
          // GENERATED by #{GENERATOR} (Hecks::Projections::RustVocabulary,
          // lib/hecks/projections/rust_vocabulary.rb) from the Vocabulary
          // aggregate (#{SOURCE}).
          // Do not hand-edit — re-run #{GENERATOR} instead.
          //
          // One module per projected table. Every enum below is matched
          // exhaustively by its own accessors — no wildcard arm — so a row the
          // language gains fails to compile until it is handled.
        RUST
      end

      def table_file(table, spec, rows, argument_rows = nil)
        variants = rows.map { |row| variant_name(row, spec[:variant_from]) }
        reject_duplicates!(spec[:enum], variants)
        by_site = site_arguments_of(spec, rows, argument_rows)
        body = [header(table), enum_lines(spec[:enum], variants), EnumBody.impl_lines(spec, variants, rows),
                argument_lines(spec[:enum], variants, rows, by_site), tests_lines(spec, variants, rows, by_site)]
        "#{body.flatten.join("\n").rstrip}\n"
      end

      def site_arguments_of(spec, rows, argument_rows)
        Arguments.site_arguments(rows, argument_rows) if spec[:kind] == :templates
      end

      def argument_lines(enum, variants, rows, by_site)
        by_site ? Arguments.argument_types(enum, variants, rows, by_site) : []
      end

      def tests_lines(spec, variants, rows, by_site)
        Tests.tests(spec[:enum], spec[:kind], variants, rows, by_site)
      end

      def reject_duplicates!(enum, variants)
        duplicates = variants.tally.select { |_, count| count > 1 }.keys
        raise ArgumentError, "duplicate #{enum} variant(s): #{duplicates.join(", ")}" if duplicates.any?
      end

      def enum_lines(enum, variants)
        ["#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]",
         "pub enum #{enum} {",
         variants.map { |variant| "    #{variant}," },
         "}",
         ""]
      end

      def name_field(kind) = kind == :order ? "step" : "name"

      # `refusal` reads ambiguously beside the kernel's own `Refusal` enum.
      def accessor_name(field) = field == "refusal" ? "refusal_class" : field

      def variant_name(row, fields)
        name = fields.map { |field| pascal(row.fetch(field)) }.join
        raise ArgumentError, "#{name.inspect} is not a Rust variant name" unless name.match?(/\A[A-Z][A-Za-z0-9]*\z/)

        name
      end

      def pascal(text) = text.to_s.split("_").map { |part| part[0].to_s.upcase + part[1..].to_s }.join

      # Only `\`, `"` and newlines need escaping in the text a vocabulary row holds.
      def rust_string(text)
        escaped = text.to_s.gsub("\\") { "\\\\" }.gsub('"') { "\\\"" }.gsub("\n") { "\\n" }
        "\"#{escaped}\""
      end
    end
  end
end
