# frozen_string_literal: true

require "fileutils"
require "json"
require_relative "../../tools"

module Hecks
  module Tools
    module FuzzSweep
      # Prints a domain's result, then shrinks and saves one repro script per distinct finding.
      module Reporting
        # Writes a shrunk (or original) step sequence to disk as a replayable script.
        #
        # @param steps [Array<Hash>] the step sequence to save
        # @param path [String] the file path to write the script to
        # @param seed [Integer] the seed that produced `steps`, recorded in the script's own note
        # @param domain_name [String] the domain's basename, for the script's `name` field
        # @return [void]
        def write_script(steps, path, seed, domain_name)
          File.write(path, JSON.pretty_generate(
                             name:  "#{domain_name}-fuzz",
                             note:  "generated by hecks fuzz — seed #{seed}",
                             steps: steps
                           ))
        end

        # Prints the final report, then shrinks and saves one repro script per distinct finding.
        #
        # @param result [Result] what the sweep of one domain drew and found
        # @return [Boolean] whether the domain had no findings
        def report(result)
          executed = result.clean + result.failures.length
          puts "   #{executed} seeds executed (#{result.drawn} drawn) — " \
               "#{result.clean} clean, #{result.failures.length} found something"
          report_shortfall(result, executed)
          clean = result.failures.empty?
          report_findings(result) unless clean
          puts
          clean
        end

        private

        def report_shortfall(result, executed)
          return unless executed < result.seeds

          puts "   SHORT — asked for #{result.seeds} executing seeds and drew #{result.drawn} to find #{executed}."
          puts "          The generator is not reaching state ; this sweep proves less than it looks."
        end

        def report_findings(result)
          grouped = result.failures.group_by { |failure| failure[:signature] }
          puts "   #{grouped.size} distinct finding(s):"
          save_dir = save_directory(result)
          grouped.each_value.with_index(1) do |group, number|
            print_finding(group, number, result.seeds)
            save_finding(result, group.min_by { |failure| failure[:steps].length }, save_dir)
          end
        end

        # @return [String] where the repro scripts go, created when missing
        def save_directory(result)
          File.join(result.root, "tmp/fuzz-failures").tap { |dir| FileUtils.mkdir_p(dir) }
        end

        def print_finding(group, number, seeds)
          seeds_hit = group.map { |failure| failure[:seed] }
          puts
          puts "   (#{number}) #{group.first[:signature]} — #{group.first[:message]}"
          puts "       #{group.length} of #{seeds} seeds: #{seeds_hit.first(8).join(", ")}#{", …" if seeds_hit.length > 8}"
        end

        # Shrinks the smallest failing sequence of a finding and saves it as a repro script.
        def save_finding(result, smallest, save_dir)
          shrunk = shrink(result.domain, smallest[:steps], smallest[:signature], result.adapter)
          save_path = File.join(save_dir, "#{result.name}-seed#{smallest[:seed]}.json")
          write_script(shrunk, save_path, smallest[:seed], result.name)
          print_saved(smallest[:steps].length, shrunk.length, "hecks run #{result.domain} #{save_path}")
        end

        def print_saved(from, to, command)
          puts "       shrunk #{from} steps -> #{to}"
          puts "       reproduce: #{command}"
        end
      end
    end
  end
end
