// Generated by hecks site site_projection.project_site. Do not edit.

// The domain's shape, read from its bluebook: every aggregate with its attributes, value objects,
// lifecycle, commands and queries. The pages, the forms and the input parser all read this one
// constant, so the editor can edit any aggregate; none of it is written by hand.

/** How an attribute's value is entered: `object` is a value object, the rest are single values. */
export type Kind = "text" | "integer" | "number" | "boolean" | "object" | "reference";

/**
 * What an attribute names: an instance of another aggregate, offered as a choice. `strict` pickers
 * accept only a key that exists; the others suggest and accept any text. `listing` is the query of
 * the target that lists what is on offer, or none to offer every instance. With `kinds`, the value is
 * `<kind>:<key>`: the kind is chosen first, then the record of the aggregate that kind names.
 */
export interface Picker {
  target?: string;
  /** The target's chapter, when the editor spans several or the target is in another. */
  chapter?: string;
  /** The target's identity attribute. */
  key?: string;
  /** The attribute that names an instance to a person (its title, name or label, else its identity). */
  label?: string;
  listing?: string;
  strict?: boolean;
  kinds?: PickerKind[];
}

/** One kind of a `<kind>:<key>` value, and the aggregate it names when it names one. */
export type PickerKind = Omit<Picker, "kinds"> & { kind: string };

/**
 * A list of mixed blocks: a list of one value object whose `discriminator` part is one of `kinds`. With
 * `rules`, each kind's `requires` (parts it must have) and `uses` (parts it may have) come from a
 * declared table; a part no row names belongs to every kind. With none, every part is shown and
 * `mentions` says which parts a kind's rules read. `limits` are the most each list part of the block
 * may hold; `pictures` says, for a value object, which of its parts are a picture's key, alt text and caption.
 */
export interface BlockList {
  discriminator: string;
  kinds: string[];
  rules?: Record<string, { requires: string[]; uses: string[] }>;
  mentions?: Record<string, string[]>;
  limits?: Record<string, number>;
  pictures?: Record<string, { key: string; alt: string; caption?: string }>;
}

export interface Attr {
  name: string;
  /** The type as the bluebook spells it ("String", "Byline"). */
  type: string;
  kind: Kind;
  optional: boolean;
  /** True for `list_of`: the attribute holds a list of `type`. */
  list: boolean;
  /**
   * `body` for an attribute whose value object has the shape of a structured document (blocks of
   * spans); `date` or `datetime` for whole seconds since 1970 that the names say are a moment.
   */
  widget?: "body" | "date" | "datetime";
  /** Set when the attribute names an instance of another aggregate of the editor. */
  picker?: Picker;
  /** The members of the closed set the attribute is one of, when its value object declares one. */
  options?: string[];
  /** The aggregate a `reference` points at. */
  target?: string;
  /** Set when the attribute is a list of mixed blocks (see `BlockList`). */
  blockList?: BlockList;
  /** The most rows the list may hold, when a rule of its holder (an invariant or a command's `given`) says. */
  max?: number;
  /** The fewest rows the list may hold, when a rule of its holder says. */
  min?: number;
  /** The most characters a text may hold, when a rule of its holder says. */
  maxLength?: number;
  /** True when `maxLength` is long enough for the text to be written in a box of several lines. */
  multiline?: boolean;
  /** Set when the value object is a picture: the names of its parts that hold the file, its description and its caption. */
  picture?: { key: string; alt: string; caption?: string };
}

export interface Transition {
  verb: string;
  from: string[];
  to: string;
}

export interface Lifecycle {
  field: string;
  default: string;
  transitions: Transition[];
  /** Each state's badge tone: `neutral`, `ok`, `info`, `warn` or `danger`. */
  tones: Record<string, string>;
}

export interface Command {
  name: string;
  goal: string | null;
  role: string | null;
  /** True when the command makes a new instance; false when it acts on one (`reference_to`). */
  creates: boolean;
  /** The aggregate the command acts on, when it is not a creating command. */
  on: string | null;
  /** True when the editor asks for confirmation before running it (see the generator's `Destructive`). */
  destructive: boolean;
  attributes: Attr[];
  /** The arguments that only clear a field and are not offered as inputs: sent as empty lists. */
  empty?: string[];
}

export interface Query {
  name: string;
  description: string | null;
  attributes: Attr[];
}

/**
 * A record of another aggregate that goes with this one's records, because its identity is a
 * `<kind>:<slug>` key of this aggregate. `shape` says how to show it; `create` and `edit` name the
 * commands that make and change it, when it has them.
 */
export interface Related {
  aggregate: string;
  chapter?: string;
  /** The related aggregate's identity attribute, which the key fills. */
  field: string;
  shape: "document" | "gallery" | "metadata";
  create?: string;
  edit?: string;
}

/** An aggregate that keeps a draft of its content beside the live one, and the commands that handle it. */
export interface Drafts {
  /** The draft attribute (`draft_body`, `draft_content`) and the live one it stands for (`body`, `content`). */
  attribute: string;
  live: string;
  save: string;
  publish?: string;
  discard?: string;
}

export interface Aggregate {
  name: string;
  /** The chapter that declares the aggregate; set when the editor spans several. */
  chapter?: string;
  /** The roles that may edit it, when its chapter limits them; any admitted role otherwise. */
  roles?: string[];
  description: string | null;
  identity: string;
  lifecycle: Lifecycle | null;
  attributes: Attr[];
  valueObjects: Record<string, Attr[]>;
  commands: Command[];
  queries: Query[];
  /** The aggregates keyed by this one's records, shown as panels on a record's page. */
  related?: Related[];
  /** The draft the aggregate keeps beside its live content, when it keeps one. */
  drafts?: Drafts;
}

/** How one part of a picture's record is sent: `wrap` is the part of a value object that holds the value. */
export interface MediaField {
  name: string;
  wrap: string | null;
}

/** The aggregate that registers pictures, when the chapter has one: found by shape, never by name. */
export interface Media {
  aggregate: string;
  command: string;
  fields: { key: MediaField; alt: MediaField; mime: MediaField; width?: MediaField; height?: MediaField };
  /** The query that lists the pictures, or null when every instance is read. */
  listing: string | null;
  /** The chapter that holds the picture aggregate, when it is not this editor's own chapter. */
  domain?: string;
  /** That aggregate, which is then not among the editor's own; see `domain`. */
  definition?: Aggregate;
}

/**
 * The aggregate whose records are actions to run later, found by shape: the attribute that names the
 * record an action is for, the closed set of actions, the due time, and the commands. The editor only
 * makes and changes these records; something else runs them.
 */
export interface Scheduling {
  aggregate: string;
  chapter?: string;
  subject: string;
  action: string;
  actions: string[];
  due: string;
  /** The first state of a record: an action not yet run. */
  pending: string;
  schedule: string;
  reschedule?: string;
  cancel?: string;
  /** The query that lists the actions of one subject, when there is one. */
  query?: string;
  /** The optional text a record may carry to say why it ended as it did. */
  reason?: string;
  /** True when the editor makes the record's identity, since it is not the subject. */
  generated?: boolean;
}

export interface Schema {
  /** The first chapter, which names the domain the host is asked for. */
  domain: string;
  /** Every chapter, in the order the navigation groups them; set when the editor spans several. */
  chapters?: string[];
  aggregates: Aggregate[];
  media?: Media;
  scheduling?: Scheduling;
}

export const SCHEMA: Schema = {
  "domain": "Press",
  "chapters": [
    "Press",
    "Library"
  ],
  "aggregates": [
    {
      "name": "Article",
      "chapter": "Press",
      "description": "One piece the publisher writes, from draft to archive.",
      "identity": "slug",
      "lifecycle": {
        "field": "status",
        "default": "draft",
        "transitions": [
          {
            "verb": "Publish",
            "from": [
              "draft"
            ],
            "to": "published"
          },
          {
            "verb": "Archive",
            "from": [
              "draft",
              "published"
            ],
            "to": "archived"
          }
        ],
        "tones": {
          "draft": "neutral",
          "published": "ok",
          "archived": "info"
        }
      },
      "attributes": [
        {
          "name": "slug",
          "type": "ArticleSlug",
          "kind": "object",
          "optional": false,
          "list": false
        },
        {
          "name": "title",
          "type": "Headline",
          "kind": "object",
          "optional": false,
          "list": false
        },
        {
          "name": "published_on",
          "type": "PublishedOn",
          "kind": "object",
          "optional": false,
          "list": false,
          "widget": "date"
        },
        {
          "name": "categories",
          "type": "CategorySlugRef",
          "kind": "object",
          "optional": false,
          "list": true,
          "picker": {
            "target": "Category",
            "chapter": "Press",
            "key": "slug",
            "label": "name",
            "listing": "Active",
            "strict": true
          }
        },
        {
          "name": "cover",
          "type": "ImageRef",
          "kind": "object",
          "optional": true,
          "list": false,
          "picker": {
            "target": "MediaItem",
            "chapter": "Library",
            "key": "key",
            "label": "alt",
            "listing": "Pictures",
            "strict": false
          }
        }
      ],
      "valueObjects": {
        "ArticleSlug": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "Headline": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "PublishedOn": [
          {
            "name": "value",
            "type": "Integer",
            "kind": "integer",
            "optional": false,
            "list": false
          }
        ],
        "CategorySlugRef": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "ImageRef": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ]
      },
      "commands": [
        {
          "name": "Draft",
          "goal": "Start an article the site does not show yet",
          "role": "Editor",
          "creates": true,
          "on": null,
          "destructive": false,
          "attributes": [
            {
              "name": "slug",
              "type": "ArticleSlug",
              "kind": "object",
              "optional": false,
              "list": false
            },
            {
              "name": "title",
              "type": "Headline",
              "kind": "object",
              "optional": false,
              "list": false
            },
            {
              "name": "published_on",
              "type": "PublishedOn",
              "kind": "object",
              "optional": false,
              "list": false,
              "widget": "date"
            },
            {
              "name": "categories",
              "type": "CategorySlugRef",
              "kind": "object",
              "optional": false,
              "list": true,
              "picker": {
                "target": "Category",
                "chapter": "Press",
                "key": "slug",
                "label": "name",
                "listing": "Active",
                "strict": true
              }
            },
            {
              "name": "cover",
              "type": "ImageRef",
              "kind": "object",
              "optional": true,
              "list": false,
              "picker": {
                "target": "MediaItem",
                "chapter": "Library",
                "key": "key",
                "label": "alt",
                "listing": "Pictures",
                "strict": false
              }
            }
          ]
        },
        {
          "name": "Revise",
          "goal": "Change an article's headline, date, categories or cover",
          "role": "Editor",
          "creates": false,
          "on": "Article",
          "destructive": false,
          "attributes": [
            {
              "name": "title",
              "type": "Headline",
              "kind": "object",
              "optional": false,
              "list": false
            },
            {
              "name": "published_on",
              "type": "PublishedOn",
              "kind": "object",
              "optional": false,
              "list": false,
              "widget": "date"
            },
            {
              "name": "categories",
              "type": "CategorySlugRef",
              "kind": "object",
              "optional": false,
              "list": true,
              "picker": {
                "target": "Category",
                "chapter": "Press",
                "key": "slug",
                "label": "name",
                "listing": "Active",
                "strict": true
              }
            },
            {
              "name": "cover",
              "type": "ImageRef",
              "kind": "object",
              "optional": true,
              "list": false,
              "picker": {
                "target": "MediaItem",
                "chapter": "Library",
                "key": "key",
                "label": "alt",
                "listing": "Pictures",
                "strict": false
              }
            }
          ]
        },
        {
          "name": "Publish",
          "goal": "Put a drafted article on the site",
          "role": "Editor",
          "creates": false,
          "on": "Article",
          "destructive": false,
          "attributes": []
        },
        {
          "name": "Archive",
          "goal": "Take an article off the site and out of the way",
          "role": "Editor",
          "creates": false,
          "on": "Article",
          "destructive": false,
          "attributes": []
        }
      ],
      "queries": [
        {
          "name": "Published",
          "description": "Every article the site shows.",
          "attributes": []
        }
      ],
      "related": [
        {
          "aggregate": "Gallery",
          "chapter": "Library",
          "field": "key",
          "shape": "gallery",
          "create": "Compose"
        }
      ]
    },
    {
      "name": "Category",
      "chapter": "Press",
      "description": "A section of the publisher's writing that articles are filed under.",
      "identity": "slug",
      "lifecycle": {
        "field": "status",
        "default": "active",
        "transitions": [
          {
            "verb": "Retire",
            "from": [
              "active"
            ],
            "to": "retired"
          }
        ],
        "tones": {
          "active": "neutral",
          "retired": "danger"
        }
      },
      "attributes": [
        {
          "name": "slug",
          "type": "CategorySlug",
          "kind": "object",
          "optional": false,
          "list": false
        },
        {
          "name": "name",
          "type": "CategoryName",
          "kind": "object",
          "optional": false,
          "list": false
        }
      ],
      "valueObjects": {
        "CategorySlug": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "CategoryName": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ]
      },
      "commands": [
        {
          "name": "Define",
          "goal": "Add a category articles can be filed under",
          "role": "Editor",
          "creates": true,
          "on": null,
          "destructive": false,
          "attributes": [
            {
              "name": "slug",
              "type": "CategorySlug",
              "kind": "object",
              "optional": false,
              "list": false
            },
            {
              "name": "name",
              "type": "CategoryName",
              "kind": "object",
              "optional": false,
              "list": false
            }
          ]
        },
        {
          "name": "Retire",
          "goal": "Stop offering a category for new articles",
          "role": "Editor",
          "creates": false,
          "on": "Category",
          "destructive": true,
          "attributes": []
        }
      ],
      "queries": [
        {
          "name": "Active",
          "description": "Every category still offered.",
          "attributes": []
        }
      ]
    },
    {
      "name": "Note",
      "chapter": "Press",
      "description": "A reminder the publisher keeps for itself.",
      "identity": "key",
      "lifecycle": null,
      "attributes": [
        {
          "name": "key",
          "type": "NoteKey",
          "kind": "object",
          "optional": false,
          "list": false
        },
        {
          "name": "text",
          "type": "Remark",
          "kind": "object",
          "optional": false,
          "list": false
        },
        {
          "name": "remind_at",
          "type": "Moment",
          "kind": "object",
          "optional": true,
          "list": false,
          "widget": "datetime"
        }
      ],
      "valueObjects": {
        "NoteKey": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "Remark": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "Moment": [
          {
            "name": "value",
            "type": "Integer",
            "kind": "integer",
            "optional": false,
            "list": false
          }
        ]
      },
      "commands": [
        {
          "name": "Jot",
          "goal": "Keep a reminder",
          "role": "Editor",
          "creates": true,
          "on": null,
          "destructive": false,
          "attributes": [
            {
              "name": "key",
              "type": "NoteKey",
              "kind": "object",
              "optional": false,
              "list": false
            },
            {
              "name": "text",
              "type": "Remark",
              "kind": "object",
              "optional": false,
              "list": false
            },
            {
              "name": "remind_at",
              "type": "Moment",
              "kind": "object",
              "optional": true,
              "list": false,
              "widget": "datetime"
            }
          ]
        }
      ],
      "queries": [],
      "related": [
        {
          "aggregate": "Gallery",
          "chapter": "Library",
          "field": "key",
          "shape": "gallery",
          "create": "Compose"
        }
      ]
    },
    {
      "name": "MediaItem",
      "chapter": "Library",
      "roles": [
        "Admin"
      ],
      "description": "A picture the publisher has uploaded: its record only, the bytes are kept elsewhere.",
      "identity": "key",
      "lifecycle": null,
      "attributes": [
        {
          "name": "key",
          "type": "PictureKey",
          "kind": "object",
          "optional": false,
          "list": false
        },
        {
          "name": "alt",
          "type": "AltText",
          "kind": "object",
          "optional": false,
          "list": false
        },
        {
          "name": "mime_type",
          "type": "MimeType",
          "kind": "object",
          "optional": false,
          "list": false
        }
      ],
      "valueObjects": {
        "PictureKey": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "AltText": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "MimeType": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ]
      },
      "commands": [
        {
          "name": "RegisterPicture",
          "goal": "Record a picture that has been uploaded",
          "role": "Editor",
          "creates": true,
          "on": null,
          "destructive": false,
          "attributes": [
            {
              "name": "key",
              "type": "PictureKey",
              "kind": "object",
              "optional": false,
              "list": false
            },
            {
              "name": "alt",
              "type": "AltText",
              "kind": "object",
              "optional": false,
              "list": false
            },
            {
              "name": "mime_type",
              "type": "MimeType",
              "kind": "object",
              "optional": false,
              "list": false
            }
          ]
        }
      ],
      "queries": [
        {
          "name": "Pictures",
          "description": "Every registered picture.",
          "attributes": []
        }
      ]
    },
    {
      "name": "Category",
      "chapter": "Library",
      "roles": [
        "Admin"
      ],
      "description": "A named group of pictures.",
      "identity": "slug",
      "lifecycle": null,
      "attributes": [
        {
          "name": "slug",
          "type": "CategorySlug",
          "kind": "object",
          "optional": false,
          "list": false
        },
        {
          "name": "name",
          "type": "GroupName",
          "kind": "object",
          "optional": false,
          "list": false
        }
      ],
      "valueObjects": {
        "CategorySlug": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "GroupName": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ]
      },
      "commands": [
        {
          "name": "Group",
          "goal": "Start a group of pictures",
          "role": "Editor",
          "creates": true,
          "on": null,
          "destructive": false,
          "attributes": [
            {
              "name": "slug",
              "type": "CategorySlug",
              "kind": "object",
              "optional": false,
              "list": false
            },
            {
              "name": "name",
              "type": "GroupName",
              "kind": "object",
              "optional": false,
              "list": false
            }
          ]
        }
      ],
      "queries": [
        {
          "name": "All",
          "description": "Every group.",
          "attributes": []
        }
      ]
    },
    {
      "name": "Gallery",
      "chapter": "Library",
      "roles": [
        "Admin"
      ],
      "description": "The pictures that go with one article or note, named by `<kind>:<slug>`.",
      "identity": "key",
      "lifecycle": null,
      "attributes": [
        {
          "name": "key",
          "type": "GalleryKey",
          "kind": "object",
          "optional": false,
          "list": false,
          "picker": {
            "kinds": [
              {
                "kind": "article",
                "target": "Article",
                "chapter": "Press",
                "key": "slug",
                "label": "title",
                "strict": true
              },
              {
                "kind": "note",
                "target": "Note",
                "chapter": "Press",
                "key": "key",
                "label": "key",
                "strict": true
              }
            ]
          }
        },
        {
          "name": "name",
          "type": "GalleryName",
          "kind": "object",
          "optional": false,
          "list": false
        },
        {
          "name": "pictures",
          "type": "PictureRef",
          "kind": "object",
          "optional": false,
          "list": true,
          "picker": {
            "target": "MediaItem",
            "chapter": "Library",
            "key": "key",
            "label": "alt",
            "listing": "Pictures",
            "strict": false
          }
        }
      ],
      "valueObjects": {
        "GalleryKey": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "GalleryName": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "PictureRef": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ]
      },
      "commands": [
        {
          "name": "Compose",
          "goal": "Gather pictures for an article or a note",
          "role": "Editor",
          "creates": true,
          "on": null,
          "destructive": false,
          "attributes": [
            {
              "name": "key",
              "type": "GalleryKey",
              "kind": "object",
              "optional": false,
              "list": false,
              "picker": {
                "kinds": [
                  {
                    "kind": "article",
                    "target": "Article",
                    "chapter": "Press",
                    "key": "slug",
                    "label": "title",
                    "strict": true
                  },
                  {
                    "kind": "note",
                    "target": "Note",
                    "chapter": "Press",
                    "key": "key",
                    "label": "key",
                    "strict": true
                  }
                ]
              }
            },
            {
              "name": "name",
              "type": "GalleryName",
              "kind": "object",
              "optional": false,
              "list": false
            },
            {
              "name": "pictures",
              "type": "PictureRef",
              "kind": "object",
              "optional": false,
              "list": true,
              "picker": {
                "target": "MediaItem",
                "chapter": "Library",
                "key": "key",
                "label": "alt",
                "listing": "Pictures",
                "strict": false
              }
            }
          ]
        }
      ],
      "queries": []
    }
  ],
  "media": {
    "aggregate": "MediaItem",
    "command": "RegisterPicture",
    "fields": {
      "key": {
        "name": "key",
        "wrap": "value"
      },
      "alt": {
        "name": "alt",
        "wrap": "value"
      },
      "mime": {
        "name": "mime_type",
        "wrap": "value"
      }
    },
    "listing": "Pictures",
    "domain": "Library"
  }
};
