# frozen_string_literal: true

require "json"
require_relative "fields/definitions"
require_relative "fields/readers"

module Hecks
  module Projections
    module Site
      module Payload
        # The TypeScript that ties a Payload collection to an aggregate: the collection's field
        # definitions, one per attribute, and the function that reads a saved document back into the
        # aggregate's input.
        #
        # Both come from the attribute's shape and, where the editor needs something the shape
        # cannot
        # say (a date picker, a choice list, an upload, a relation), from a `PayloadField` row.
        # They are
        # produced together so a field and the code that reads it cannot disagree.
        module Fields
          BANNER = "// Generated by hecks site site_projection.project_site. Do not edit."

          # The kinds a row may name, with the Payload field type each is.
          KINDS = { "text" => "text", "textarea" => "textarea", "select" => "select", "date" => "date", "day" => "date",
                    "number" => "number", "upload" => "upload", "relationship" => "relationship" }.freeze

          module_function

          # @param aggregates [Array<Model::Aggregate>] the aggregates to drive
          # @param rows [Array<Hash{Symbol => Object}>] the checked `PayloadField` rows
          # @param specs [String] the import path of the generated specs module
          # @param helpers [String] the import path of the module that holds `nonBlank` and its kin
          # @return [String] the module
          # @raise [ArgumentError] when a row names an aggregate or an attribute the domain lacks
          def render(aggregates, rows:, specs:, helpers:)
            check(aggregates, rows)
            body = aggregates.map { |agg| aggregate(agg, rows.select { |row| row[:aggregate] == agg.noun }) }
            [BANNER, header(aggregates, specs, helpers), shared, *body].join("\n\n") << "\n"
          end

          def check(aggregates, rows)
            rows.each do |row|
              agg = aggregates.find { |candidate| candidate.noun == row[:aggregate] }
              raise ArgumentError, "PayloadField names #{row[:aggregate]}, which it does not drive" unless agg

              check_attribute(agg, row)
              check_kind(row)
            end
          end

          def check_attribute(agg, row)
            top, part = row[:attribute].split(".", 2)
            attr = agg.attrs.find { |candidate| candidate.name == top }
            where = "PayloadField #{row[:aggregate]}.#{row[:attribute]}"
            raise ArgumentError, "#{where} is not an attribute" unless attr
            raise ArgumentError, "#{where} is not a part" if part && !attr.parts&.any? { |each| each.name == part }
          end

          def check_kind(row)
            kind = row[:kind]
            if kind && !KINDS.key?(kind)
              raise ArgumentError,
                    "PayloadField kind #{kind.inspect} is one of #{KINDS.keys.join(", ")}"
            end
            return unless %w[upload relationship].include?(kind) && !row[:relation]

            raise ArgumentError, "PayloadField #{row[:attribute]} is #{kind} and needs a relation"
          end

          def header(aggregates, specs, helpers)
            types = aggregates.map { |agg| "type #{agg.noun}Input" }.join(", ")
            <<~TS.chomp
              import type { Field, PayloadRequest } from "payload";

              import { isoOrNull, nonBlank, related, type Doc } from #{helpers.to_json};
              import { #{types} } from #{specs.to_json};
            TS
          end

          def shared
            <<~TS.chomp
              const valuesOf = (value: unknown, pick: (raw: unknown) => string | null): string[] =>
                (Array.isArray(value) ? value : []).map((row) => pick((row as Doc)?.value)).filter((item): item is string => !!item);
            TS
          end

          def aggregate(agg, rows)
            var = "#{agg.noun[0].downcase}#{agg.noun[1..]}"
            <<~TS.chomp
              // ---- #{agg.noun} ----

              export const #{var}Fields = {
              #{fields_block(agg, rows)}
              } satisfies Record<string, Field>;

              export const #{var}FromDoc = async (req: PayloadRequest, doc: Doc): Promise<#{agg.noun}Input> => ({
              #{inputs_block(agg, rows)}
              });
            TS
          end

          def fields_block(agg, rows) = fields_of(agg, rows).map { |name, text| "  #{name}: #{text}," }.join("\n")

          def inputs_block(agg, rows)
            agg.attrs.map { |attr| "  #{attr.ts}: #{Readers.input(attr, row_for(rows, attr.name), rows)}," }.join("\n")
          end

          def row_for(rows, attribute, part = nil)
            wanted = part ? "#{attribute}.#{part}" : attribute
            rows.find { |row| row[:attribute] == wanted } || {}
          end

          def fields_of(agg, rows)
            agg.attrs.map do |attr|
              row = row_for(rows, attr.name)
              [field_name(attr, row), field(agg, attr, row, rows)]
            end
          end

          def field_name(attr, row) = row[:field] || attr.ts

          def field(_agg, attr, row, rows)
            name = field_name(attr, row)
            return Definitions.composite(attr, row, name, rows) if attr.shape == :composite
            return Definitions.array(attr, row, name) if attr.list

            Definitions.literal(Definitions.base(attr, row, name, !attr.optional))
          end

          def kind_of(attr, row)
            row[:kind] || (attr.shape == :integer ? "number" : "text")
          end
        end
      end
    end
  end
end
