require "json"
require_relative "yaml_text"
require_relative "access_yaml"
require_relative "task_yaml"
require_relative "routing_yaml"

module Hecks
  module Projections
    module Deploy
      module Preview
        # Renders `preview.yaml`, one per-branch preview stack's CloudFormation template.
        # Kept separate from the main one, so a preview can never enter a change set against it.
        module Template
          CACHING_DISABLED = "4135ea2d-6df8-44a3-9df3-4b5a84be39ad".freeze
          ALL_VIEWER = "216adef6-5c7f-47e4-b989-5492eafa07d3".freeze

          extend YamlText

          module_function

          def render(settings)
            [
              header(settings), parameters(settings),
              "Resources:\n#{indent(resources(settings).join("\n\n"), 2)}",
              outputs
            ].join("\n") << "\n"
          end

          def header(settings)
            <<~YAML.chomp
              # GENERATED by bin/project_deploy - re-run it to refresh this file rather than
              # hand-editing. Source: the `preview` block of the domain's deployed_to("AwsFargate").
              #
              # One stack per git branch, driven by preview.sh. A separate template from the main
              # one on purpose, so a preview can never appear in a change set against the live
              # stack. It shares the task shape and nothing else.
              #
              # Per branch: ECS cluster, service and task, an ALB, one ECR repository per
              # container, secrets, a log group, a CloudFront distribution (default hostname,
              # nothing cached) and its own database on the shared instance.
              # Borrowed from #{settings.owner_stack}: VPC, subnets and the compute security group.
              # Left out on purpose: alarms, notifications, warmers and custom domains.
              AWSTemplateFormatVersion: '2010-09-09'
              Description: >
                #{settings.infra_name} preview - one feature branch, behind its own ALB and
                CloudFront, on its own database.
            YAML
          end

          def parameters(settings)
            image_tags = settings.containers.map do |c|
              <<~YAML.chomp
                #{c.logical}ImageTag:
                  Type: String
                  Default: bootstrap
              YAML
            end
            "Parameters:\n#{indent([base_parameters, *image_tags, desired_count_parameter].join("\n"), 2)}"
          end

          def base_parameters
            <<~YAML.chomp
              EnvName:
                Type: String
                AllowedPattern: '^[a-z0-9]([a-z0-9-]{0,18}[a-z0-9])?$'
                ConstraintDescription: lowercase letters, digits and hyphens, at most 20 characters, not ending in a hyphen (the ALB name limit is 32).
              DbName:
                Type: String
                AllowedPattern: '^[a-z][a-z0-9_]{0,62}$'
                Description: This preview's own database on the shared instance, created by the one-shot DbInit task before the service starts.
              OwningVpcId:
                Type: AWS::EC2::VPC::Id
              OwningSubnetAId:
                Type: AWS::EC2::Subnet::Id
              OwningSubnetBId:
                Type: AWS::EC2::Subnet::Id
              OwningPublicSubnetAId:
                Type: AWS::EC2::Subnet::Id
              OwningPublicSubnetBId:
                Type: AWS::EC2::Subnet::Id
              OwningSecurityGroupId:
                Type: AWS::EC2::SecurityGroup::Id
              OwningDatabaseEndpoint:
                Type: String
              OwningDatabaseSecretArn:
                Type: String
            YAML
          end

          def desired_count_parameter
            <<~YAML.chomp
              # The repositories are created by this stack, so the first create has no image to
              # point at. preview.sh creates the stack at 0, pushes, then scales up.
              DesiredCount:
                Type: Number
                Default: 0
            YAML
          end

          def resources(settings)
            [
              AccessYaml.secrets(settings), RoutingYaml.networking(settings), repositories(settings),
              cluster_and_logs(settings),
              AccessYaml.roles(settings), TaskYaml.db_init_task(settings), TaskYaml.task_definition(settings),
              RoutingYaml.load_balancing(settings),
              RoutingYaml.service(settings), distribution
            ].flatten
          end

          def repositories(settings)
            settings.containers.map do |c|
              <<~YAML.chomp
                #{c.logical}Repository:
                  Type: AWS::ECR::Repository
                  Properties:
                    RepositoryName: !Sub "#{settings.prefix}-${EnvName}-#{c.name}"
                    EmptyOnDelete: true
              YAML
            end
          end

          def cluster_and_logs(settings)
            [
              <<~YAML.chomp,
                Cluster:
                  Type: AWS::ECS::Cluster
                  Properties:
                    ClusterName: !Sub "#{settings.prefix}-${EnvName}"
              YAML
              <<~YAML.chomp
                LogGroup:
                  Type: AWS::Logs::LogGroup
                  Properties:
                    LogGroupName: !Sub "/ecs/#{settings.prefix}-${EnvName}"
                    RetentionInDays: #{settings.log_retention_days}
              YAML
            ]
          end

          def distribution
            <<~YAML.chomp
              # One behavior, nothing cached: a preview is for looking at a change, so no cache means
              # no stale page after a redeploy and no session response served to the wrong visitor.
              # AllViewer forwards the viewer's Host so a same-origin check sees the real hostname.
              PreviewDistribution:
                Type: AWS::CloudFront::Distribution
                Properties:
                  DistributionConfig:
                    Enabled: true
                    HttpVersion: http2
                    Comment: !Sub "preview ${EnvName}"
                    Origins:
                      - Id: PreviewAlbOrigin
                        DomainName: !GetAtt Alb.DNSName
                        CustomOriginConfig:
                          OriginProtocolPolicy: http-only
                          OriginSSLProtocols: [TLSv1.2]
                    DefaultCacheBehavior:
                      TargetOriginId: PreviewAlbOrigin
                      ViewerProtocolPolicy: redirect-to-https
                      AllowedMethods: [GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE]
                      CachedMethods: [GET, HEAD]
                      Compress: true
                      CachePolicyId: #{CACHING_DISABLED}
                      OriginRequestPolicyId: #{ALL_VIEWER}
            YAML
          end

          def outputs
            <<~YAML.chomp
              Outputs:
                PreviewUrl:
                  Value: !Sub "https://${PreviewDistribution.DomainName}"
                ClusterName:
                  Value: !Ref Cluster
                ServiceName:
                  Value: !GetAtt Service.Name
                DbInitTaskDefinition:
                  Value: !Ref DbInitTaskDefinition
                # The ARN only, so preview.sh can fetch the secret to mint signup and session tokens.
                SessionSecretArn:
                  Value: !Ref SessionSecret
                DatabaseName:
                  Value: !Ref DbName
            YAML
          end
        end
      end
    end
  end
end
