// Generated by hecks site site_projection.project_site. Do not edit.

// The admin sign-in of this site, projected from its bluebook's Admin row and Route rows. Change the
// rows and run `hecks site site_projection.project_site`; with `--check` it fails when this file is out of date.

import { MIDDLEWARE, ROUTES, matchesPath } from "./routes.ts";

/** What the sign-in is built from: the project's Admin row, defaults filled. */
export const ADMIN = {
  sessionCookie: "club_session",
  sessionMaxAge: 1209600,
  hostEnv: "CLUB_DOMAIN_SERVICE_URL",
  hostDefault: "http://127.0.0.1:4500",
  roles: ["Admin", "Owner"],
  accountPath: "/accounts/me",
  membersPath: "/members",
  ssoTokenPath: "/accounts/sso-token",
  ssoTarget: "/cms/api/sso",
  login: "/admin-login",
  sso: "/api/cms-sso",
  verdictTtlMs: 2000,
  timeoutMs: 5000,
} as const;

const MAX_REMEMBERED = 500;

/** Remembers each key's answer for the verdict TTL; callers that arrive while it loads share it, and a failure is never kept. */
function remember<V>(load: (key: string) => Promise<V>) {
  const values = new Map<string, { at: number; value: V }>();
  const running = new Map<string, Promise<V>>();
  return {
    get(key: string): Promise<V> {
      const hit = values.get(key);
      if (hit && Date.now() - hit.at < ADMIN.verdictTtlMs) return Promise.resolve(hit.value);
      const shared = running.get(key);
      if (shared) return shared;
      const started: Promise<V> = load(key)
        .then((value) => {
          if (running.get(key) === started) {
            values.delete(key);
            values.set(key, { at: Date.now(), value });
            if (values.size > MAX_REMEMBERED) values.delete(values.keys().next().value as string);
          }
          return value;
        })
        .finally(() => {
          if (running.get(key) === started) running.delete(key);
        });
      running.set(key, started);
      return started;
    },
    forget(): void {
      values.clear();
      running.clear();
    },
  };
}

export interface AdminSettings {
  /** The domain host's address, when not read from the environment variable the Admin row names. */
  host?: string;
  /** The fetch to use, for tests. */
  fetch?: typeof fetch;
}

let settings: AdminSettings = {};

/** Sets the host or the fetch, and forgets every remembered verdict. */
export function configureAdmin(next: AdminSettings): void {
  settings = next;
  forgetAdminSessions();
}

function hostUrl(): string {
  const named = settings.host ?? (typeof process !== "undefined" ? process.env[ADMIN.hostEnv] : undefined);
  return (named || ADMIN.hostDefault).replace(/\/+$/, "");
}

function askHost(path: string, cookieValue: string): Promise<Response> {
  return (settings.fetch ?? fetch)(`${hostUrl()}${path}`, {
    headers: { Cookie: `${ADMIN.sessionCookie}=${cookieValue}` },
    signal: AbortSignal.timeout(ADMIN.timeoutMs),
  });
}

export interface MemberRow {
  email?: unknown;
  role?: unknown;
  disabled?: unknown;
}

/** True when `email` (any case) is a member holding one of the admin roles and not disabled. */
export function isActiveAdmin(members: MemberRow[], email: string): boolean {
  const wanted = email.trim().toLowerCase();
  return members.some(
    (member) =>
      typeof member.email === "string" &&
      member.email.trim().toLowerCase() === wanted &&
      (ADMIN.roles as readonly unknown[]).includes(member.role) &&
      member.disabled !== true,
  );
}

/** A signed-in admin and the membership list that vouched for them. */
export interface AdminSession {
  email: string;
  members: unknown[];
}

async function fetchAccountEmail(cookieValue: string): Promise<string | null> {
  const res = await askHost(ADMIN.accountPath, cookieValue);
  if (!res.ok) return null;
  const data = await res.json();
  return typeof data.email === "string" ? data.email : null;
}

async function fetchAdminSession(cookieValue: string): Promise<AdminSession | null> {
  const [email, membersRes] = await Promise.all([
    fetchAccountEmail(cookieValue),
    askHost(ADMIN.membersPath, cookieValue),
  ]);
  if (!email || !membersRes.ok) return null;
  const members = await membersRes.json();
  return Array.isArray(members) && isActiveAdmin(members, email) ? { email, members } : null;
}

const accountEmails = remember(fetchAccountEmail);
const adminSessions = remember(fetchAdminSession);

/** Drops every remembered verdict, for after this process changes a member. */
export function forgetAdminSessions(): void {
  accountEmails.forget();
  adminSessions.forget();
}

/** The signed-in person's email, or null when the cookie is absent or the host does not know it. */
export async function currentAccountEmail(cookieValue: string | undefined): Promise<string | null> {
  return cookieValue ? accountEmails.get(cookieValue) : null;
}

/** The signed-in person and the membership list when they hold an admin role, else null. */
export async function currentAdminSession(cookieValue: string | undefined): Promise<AdminSession | null> {
  return cookieValue ? adminSessions.get(cookieValue) : null;
}

/** The signed-in person's email when they may use the admin pages, else null. */
export async function currentAdminEmail(cookieValue: string | undefined): Promise<string | null> {
  return (await currentAdminSession(cookieValue))?.email ?? null;
}

/**
 * Where the hand-off to the CMS sends a person: the CMS's own sign-in endpoint with a short-lived
 * token from the host, or the login page when there is no session or the host refuses the token.
 * `to` is a path inside the CMS to open once signed in; the CMS checks it.
 */
export async function ssoRedirect(cookieValue: string | undefined, to?: string | null): Promise<string> {
  if (!cookieValue) return ADMIN.login;
  const res = await askHost(ADMIN.ssoTokenPath, cookieValue);
  if (!res.ok) return ADMIN.login;
  const { token } = await res.json();
  const params = new URLSearchParams({ token });
  if (to) params.set("to", to);
  return `${ADMIN.ssoTarget}?${params}`;
}

/** How specific a route pattern is: the characters outside its wildcards, so `/admin-login` outranks `/admin*`. */
function specificity(pattern: string): number {
  return pattern.replace(/\*/g, "").length;
}

/** The route that describes a path: the most specific match, and the first listed of equals. */
function routeFor(pathname: string): (typeof ROUTES)[number] | undefined {
  let best: (typeof ROUTES)[number] | undefined;
  for (const candidate of ROUTES) {
    if (!matchesPath(candidate.path, pathname)) continue;
    if (best === undefined || specificity(candidate.path) > specificity(best.path)) best = candidate;
  }
  return best;
}

export type AdminGate = { allow: true } | { allow: false; status: 401 } | { allow: false; redirect: string };

/**
 * Whether a request may go on. The most specific route that matches the path decides: an `admin`
 * route, or any path under the draft-preview prefix, needs an admin session. A preview without
 * one is refused with 401 and nothing else; any other admin path is sent to the login page.
 */
export async function adminGate(pathname: string, cookieValue: string | undefined): Promise<AdminGate> {
  const previewing = pathname.startsWith(MIDDLEWARE.preview.prefix + "/");
  if (routeFor(pathname)?.auth !== "admin" && !previewing) return { allow: true };
  if (await currentAdminEmail(cookieValue)) return { allow: true };
  return previewing ? { allow: false, status: 401 } : { allow: false, redirect: ADMIN.login };
}
