require "spec_helper"
require "tmpdir"
require "fileutils"
require_relative "../../../lib/hecks/hecks/adapters/local_files"

# The Workspace port's adapter writes a launcher beside each domain of the current directory.
RSpec.describe Hecks::Adapters::LocalFiles do
  let(:adapter) { described_class.new }

  def domain(root, path, name)
    FileUtils.mkdir_p(File.join(root, path, "bluebook"))
    File.write(File.join(root, path, "bluebook", "#{name.downcase}.bluebook"), <<~RUBY)
      Hecks.bluebook "#{name}" do
        vision "Books on a shelf."
        aggregate "Book" do
          description "A book."
          attribute :title, Title
          identified_by :title
          value_object("Title") { attribute :value, String }
          command("Shelve") { attribute :title, Title; sets :title; emits Shelved }
        end
      end
    RUBY
    File.write(File.join(root, path, "bluebook", "#{name.downcase}.hecksagon"),
               %(Hecks.hecksagon "#{name}" do\n  persisted_by "Memory"\nend\n))
  end

  around do |example|
    Dir.mktmpdir("local-files") do |dir|
      @dir = dir
      Dir.chdir(dir) { example.run }
    end
  end

  it "writes an executable launcher beside every domain it finds" do
    domain(@dir, "shelf", "Shelf")
    domain(@dir, "library/annex", "Annex")

    answer = adapter.write

    expect(answer.dig(:output, :value)).to include("shelf/shelf  ->  Shelf", "library/annex/annex  ->  Annex")
    expect(File.executable?(File.join(@dir, "shelf/shelf"))).to be(true)
    expect(File.read(File.join(@dir, "shelf/shelf"))).to include("GENERATED by hecks project_cli")
  end

  it "writes only the domains it is named" do
    domain(@dir, "shelf", "Shelf")
    domain(@dir, "annex", "Annex")

    adapter.write(domains: { value: "annex" })

    expect(File.exist?(File.join(@dir, "annex/annex"))).to be(true)
    expect(File.exist?(File.join(@dir, "shelf/shelf"))).to be(false)
  end

  it "replaces a launcher already there and deletes nothing in bin/" do
    domain(@dir, "shelf", "Shelf")
    FileUtils.mkdir_p(File.join(@dir, "bin"))
    File.write(File.join(@dir, "bin/shelf"), "kept\n")
    File.write(File.join(@dir, "shelf/shelf"), "stale\n")

    adapter.write

    expect(File.read(File.join(@dir, "shelf/shelf"))).to include("GENERATED")
    expect(File.read(File.join(@dir, "bin/shelf"))).to eq("kept\n")
  end

  it "refuses when there is no domain to write for" do
    expect { adapter.write }.to raise_error(Hecks::Adapters::ConsoleCapture::Failure, /no domain found/)
  end

  it "refuses a named directory that holds no domain, with the reason it printed" do
    expect { adapter.write(domains: { value: "nowhere" }) }
      .to raise_error(Hecks::Adapters::ConsoleCapture::Failure, /cannot boot/)
  end
end
