require "spec_helper"
require "tmpdir"
require "fileutils"
require_relative "../../../lib/hecks/hecks/adapters/local_files"

# The Workspace port's adapter writes a launcher beside each domain of the current directory.
RSpec.describe Hecks::Adapters::LocalFiles do
  let(:adapter) { described_class.new }

  # The bluebook of a one-aggregate domain; `%<name>s` is the domain's name.
  LOCAL_FILES_BLUEBOOK = <<~RUBY.freeze
    Hecks.bluebook "%<name>s" do
      vision "Books on a shelf."
      aggregate "Book" do
        description "A book."
        attribute :title, Title
        identified_by :title
        value_object("Title") { attribute :value, String }
        command("Shelve") { attribute :title, Title; sets :title; emits Shelved }
      end
    end
  RUBY

  def domain(root, path, name)
    bluebook_dir = File.join(root, path, "bluebook")
    FileUtils.mkdir_p(bluebook_dir)
    File.write(File.join(bluebook_dir, "#{name.downcase}.bluebook"), format(LOCAL_FILES_BLUEBOOK, name: name))
    File.write(File.join(bluebook_dir, "#{name.downcase}.hecksagon"),
               %(Hecks.hecksagon "#{name}" do\n  persisted_by "Memory"\nend\n))
  end

  around do |example|
    Dir.mktmpdir("local-files") do |dir|
      @dir = dir
      Dir.chdir(dir) { example.run }
    end
  end

  context "with a domain at the top and another nested" do
    before do
      domain(@dir, "shelf", "Shelf")
      domain(@dir, "library/annex", "Annex")
    end

    it "names the launcher written beside every domain it finds" do
      expect(adapter.write.dig(:output, :value)).to include("shelf/shelf  ->  Shelf", "library/annex/annex  ->  Annex")
    end

    it "writes it executable, and marks it generated", :aggregate_failures do
      adapter.write

      expect(File.executable?(File.join(@dir, "shelf/shelf"))).to be(true)
      expect(File.read(File.join(@dir, "shelf/shelf"))).to include("GENERATED by hecks project_cli")
    end
  end

  it "writes only the domains it is named", :aggregate_failures do
    domain(@dir, "shelf", "Shelf")
    domain(@dir, "annex", "Annex")

    adapter.write(domains: { value: "annex" })

    expect(File.exist?(File.join(@dir, "annex/annex"))).to be(true)
    expect(File.exist?(File.join(@dir, "shelf/shelf"))).to be(false)
  end

  def leave_a_stale_launcher_and_a_bin_file
    domain(@dir, "shelf", "Shelf")
    FileUtils.mkdir_p(File.join(@dir, "bin"))
    File.write(File.join(@dir, "bin/shelf"), "kept\n")
    File.write(File.join(@dir, "shelf/shelf"), "stale\n")
  end

  it "replaces a launcher already there and deletes nothing in bin/", :aggregate_failures do
    leave_a_stale_launcher_and_a_bin_file

    adapter.write

    expect(File.read(File.join(@dir, "shelf/shelf"))).to include("GENERATED")
    expect(File.read(File.join(@dir, "bin/shelf"))).to eq("kept\n")
  end

  it "refuses when there is no domain to write for" do
    expect { adapter.write }.to raise_error(Hecks::Adapters::ConsoleCapture::Failure, /no domain found/)
  end

  it "refuses a named directory that holds no domain, with the reason it printed" do
    expect { adapter.write(domains: { value: "nowhere" }) }
      .to raise_error(Hecks::Adapters::ConsoleCapture::Failure, /cannot boot/)
  end
end
