// Generated by hecks site site_projection.project_site. Do not edit.

import { jwtVerify } from "jose";
import type { AuthStrategy, CollectionAfterLogoutHook } from "payload";

import { membership } from "./membership";

// Payload's own `local-jwt` strategy refuses any collection with `disableLocalStrategy` set
// ("JWT authentication requires an auth-enabled local collection") and is not even registered when
// every auth collection disables it. Users has no password login, so endpoints/sso.ts mints the
// session cookie and this verifies that same cookie itself: the token Payload's `jwtSign` produces
// ({ id, collection, sid }, HS256 over `payload.secret`, authVersion 1 in the protected header),
// then loads the user and requires its `sessions` entry to still exist so a logout or an expired
// session revokes the cookie.
const JWT_AUTH_VERSION = 1;

// Same cookie and CSRF rules as Payload's own extractJWT, cookie only: a request carrying an Origin
// must be on the csrf allowlist, and one without an Origin must be same-origin, same-site or a
// direct navigation. No Bearer or JWT header: nothing here mints tokens for API clients.
function sessionCookie(headers: Headers, cookiePrefix: string, csrf: string[]): string | null {
  const name = `${cookiePrefix}-token`;
  const raw = (headers.get("cookie") ?? "")
    .split(";")
    .map((part) => part.trim())
    .find((part) => part.startsWith(`${name}=`));
  if (!raw) return null;
  const token = decodeURIComponent(raw.slice(name.length + 1));

  const origin = headers.get("Origin");
  if (origin) return csrf.length === 0 || csrf.includes(origin) ? token : null;
  if (csrf.length === 0) return token;
  return ["same-origin", "same-site", "none"].includes(headers.get("Sec-Fetch-Site") ?? "") ? token : null;
}

// Payload's logout only deletes the session row when the local strategy is on, so without this the
// cookie it clears would still verify until it expires.
export const revokeSessionOnLogout: CollectionAfterLogoutHook = async ({ req }) => {
  const { user, payload } = req;
  const sid = (user as { _sid?: string } | null)?._sid;
  if (!user || !sid) return;

  const current = await payload.findByID({ collection: "users", id: user.id, depth: 0, overrideAccess: true, req });
  const sessions = (current.sessions ?? []).filter((session) => session.id !== sid);
  await payload.update({ collection: "users", id: user.id, data: { sessions }, overrideAccess: true, req });
};

export const sessionStrategy: AuthStrategy = {
  name: "sso-session",
  authenticate: async ({ headers, payload }) => {
    const token = sessionCookie(headers, payload.config.cookiePrefix, payload.config.csrf);
    if (!token) return { user: null };

    try {
      const { payload: claims, protectedHeader } = await jwtVerify(token, new TextEncoder().encode(payload.secret));
      if (protectedHeader.authVersion !== JWT_AUTH_VERSION) return { user: null };

      const { id, collection, sid } = claims as { id?: unknown; collection?: unknown; sid?: unknown };
      if (collection !== "users" || typeof sid !== "string") return { user: null };
      if (typeof id !== "number" && typeof id !== "string") return { user: null };

      const user = await payload.findByID({ collection: "users", id, depth: 0, overrideAccess: true });
      if (!user?.sessions?.some((session) => session.id === sid)) return { user: null };
      // Payload's session alone is not enough: the domain's membership list must still admit this
      // person (membership.ts), so disabling someone there locks them out here on their next request.
      if (typeof user.email !== "string" || !(await membership.isAdmitted(user.email))) return { user: null };

      return { user: { ...user, collection: "users", _strategy: "sso-session", _sid: sid } };
    } catch {
      return { user: null };
    }
  },
};
