# frozen_string_literal: true

module Hecks
  module RustBuild
    class ProjectRust
      class RootMod
        # The explanatory comment blocks emitted at the top of `src/generated/mod.rs`, one entry per
        # output line.
        module Notes
          BANNER = [
            "// GENERATED by hecks project_rust — re-run it to refresh this list.",
            "//",
            "// BUG#25 — every DOMAIN (an entry in `domains`, below: a directory",
            "// carrying its own merged.rs and therefore its own Cargo feature) is",
            "// declared behind that SAME feature, so a broken or absent domain's",
            "// generated code is never even compiled into a build that selects a",
            "// DIFFERENT domain — `cargo build --features waybill` used to pull in",
            "// every OTHER domain's `pub mod` unconditionally, so one domain's own",
            "// non-compiling generated code (a `has_many` field, before this fix)",
            "// broke every feature's build, not just its own. A shared FRAMEWORK",
            "// chapter (governance/identity — no merged.rs of its own, so absent",
            "// from `domains`) stays unconditional: it has no single feature of its",
            "// own to gate behind, and is compiled in by whichever domain(s) attach",
            "// it via `attaches`."
          ].freeze

          ACTIVE_HEAD = [
            "// `active` is whichever ONE domain's own merged Store/dispatch table",
            "// is selected by Cargo feature (rust/Cargo.toml, kept in sync with this",
            "// list by hecks project_rust) — kernel/cli.rs imports",
            "// `crate::generated::active::{dispatch_by_name, Store, ...}` unchanged",
            "// no matter which domain that resolves to.",
            "//",
            "// DOMAIN FEATURES ARE MUTUALLY EXCLUSIVE (R5) — Cargo has no native"
          ].freeze

          ACTIVE_TAIL = [
            "// Cargo.toml stays enabled unless a build passes",
            "// `--no-default-features`, so a plain `cargo build --features banking`",
            "// used to enable BOTH the default domain's feature and banking's,",
            "// producing two `pub use ... as active;` imports and a hard E0252.",
            "// Fixed two ways below, entirely mechanically from `domains`/",
            "// `target_mod_name` (this run's new default) — never hand-maintained:",
            "//",
            "//   1. THE DEFAULT DOMAIN'S OWN re-export backs off whenever any OTHER",
            "//      domain feature is also enabled, so it never contends for `active`",
            "//      by accident — `cargo build --features banking` (still implicitly",
            "//      carrying the default feature) now resolves to banking alone,",
            "//      same as if `--no-default-features` had been passed explicitly.",
            "//   2. Two NON-default domain features enabled TOGETHER (a genuine,",
            "//      not-accidental conflict — nothing makes that combination",
            "//      meaningful) still fail the build, but with an explicit",
            "//      `compile_error!` naming both features instead of a cryptic",
            "//      \"defined multiple times\"."
          ].freeze

          # @param default [String] the domain whose feature `default` names in Cargo.toml
          # @return [Array<String>] the lines explaining how `active` is selected
          def self.active(default)
            ACTIVE_HEAD + ["// concept of that, and `default = [#{default.inspect}]` in"] + ACTIVE_TAIL
          end
        end
      end
    end
  end
end
