// GENERATED by bin/project_field_hints from Vocabulary::FieldHint
// (lib/hecks/language/bluebook/vocabulary.bluebook). Do not
// hand-edit — re-run bin/project_field_hints instead.
//
// web.rs's `text_field` matches these in the SAME precedence Ruby's
// own `text_field` does: EMAIL_HINT, then URL_HINT, then TEL_HINT —
// against `html_type`, first match wins — then, only if `html_type`
// stayed "text", TEXTAREA_HINT against `kind`.

use regex::Regex;
use std::sync::LazyLock;

/// Email hint, resolving to `html_type` on a match —
/// Vocabulary::FieldHint's own declared pattern, unmodified (the
/// same text `Regexp#source` reads off FieldShape's own
/// EMAIL_HINT, which is built from this same row).
/// `(?i)` up front is this crate's spelling
/// of Ruby's trailing `/i` — the WHOLE pattern is case-insensitive
/// on both sides, never partially.
pub static EMAIL_HINT: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r#"(?i)email"#).expect("declared field-hint pattern must compile"));

/// Url hint, resolving to `html_type` on a match —
/// Vocabulary::FieldHint's own declared pattern, unmodified (the
/// same text `Regexp#source` reads off FieldShape's own
/// URL_HINT, which is built from this same row).
/// `(?i)` up front is this crate's spelling
/// of Ruby's trailing `/i` — the WHOLE pattern is case-insensitive
/// on both sides, never partially.
pub static URL_HINT: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r#"(?i)\b(url|uri|website|link)\b"#).expect("declared field-hint pattern must compile"));

/// Tel hint, resolving to `html_type` on a match —
/// Vocabulary::FieldHint's own declared pattern, unmodified (the
/// same text `Regexp#source` reads off FieldShape's own
/// TEL_HINT, which is built from this same row).
/// `(?i)` up front is this crate's spelling
/// of Ruby's trailing `/i` — the WHOLE pattern is case-insensitive
/// on both sides, never partially.
pub static TEL_HINT: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r#"(?i)phone|\btel(ephone)?\b"#).expect("declared field-hint pattern must compile"));

/// Textarea hint, resolving to `kind` on a match —
/// Vocabulary::FieldHint's own declared pattern, unmodified (the
/// same text `Regexp#source` reads off FieldShape's own
/// TEXTAREA_HINT, which is built from this same row).
/// `(?i)` up front is this crate's spelling
/// of Ruby's trailing `/i` — the WHOLE pattern is case-insensitive
/// on both sides, never partially.
pub static TEXTAREA_HINT: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r#"(?i)\b(text|body|note|notes|description|message|comment)\b"#).expect("declared field-hint pattern must compile"));

