#!/usr/bin/env bash
# GENERATED by hecks deploy project -- re-run it to refresh this file rather than hand-editing.
# Settings come from the domain's deployed_to("AwsBox") block (hosting_scripts true).
#
# Deploys ONE container's freshly built local image to widget-shop's app box, under a fresh, unique ECR tag.
#
#   bash deploy-service.sh <service>
#   EXISTING_TAG=<tag> bash deploy-service.sh <service>    redeploy a tag already in ECR (no push)
#
# Why it exists: pushing a floating tag and restarting a container looks like a deploy, but nothing
# records which image the box was told to run, and a box that pulls a tag it already has keeps the old
# image. This script pushes the local image under a never-reused tag (<service>-<UTC timestamp>),
# refuses a tag that is already in ECR, and names that tag in the roll.
# It then rolls the box with deploy-box.sh, naming the new tag for this container and the
# tag the box runs now for every other one.
#
# It ends with smoke-after-deploy.sh, whose own exit codes (20-23) are distinct from a failed deploy
# step's. SKIP_POST_DEPLOY_SMOKE=1 skips it. `hecks deploy service_roll.run` runs this script with
# SMOKE_BY_COMMAND=1, which ends after the roll and leaves the smoke to the smoke_run.run its policy requests.
#
# Exit codes (the ones `service_roll.run` names; a step that fails under `set -e` ends with its own
# status, 1 from bash and 254/255 from the aws CLI):
#   2   unknown service
#   30  EXISTING_TAG is not in ECR              31  the fresh tag is already in ECR
#   32  the box's Compose file is unreadable    33  the box stack has no instance
#   34  the stack has no parameter for the container   35  the stack update failed or did not settle
#   36  a parameter other than the container's changed  37  the task definition lacks the pushed image
#   38  the task definition has no such container      40-43  deploy-box.sh's own
#
# Environment:
#   LOCAL_IMAGE               local image to push, default <ecr repository>:latest
#   EXISTING_TAG              redeploy this tag from ECR instead of building and pushing
#   SETTLE_TIMEOUT_SECS       default 1200, how long to wait for a stack update
#   SKIP_POST_DEPLOY_SMOKE=1  passed through to smoke-after-deploy.sh
#   SMOKE_BY_COMMAND=1        end after the roll and print `rolled taskdef=<td> tag=<tag>`; the caller smokes
set -euo pipefail

REGION=us-east-1
BOX_STACK=hecks-widget-shop-box
BOX_DIR=/opt/widget-shop

SERVICES='website cms'

# Sets the container's settings for one service, or exits.
resolve_service() {
  case "$1" in
    website) ECR_REPOSITORY=widget-shop-website ;;
    cms) ECR_REPOSITORY=acme-cms ;;
    *) echo "unknown service '$1', must be one of: ${SERVICES}" >&2; exit 2 ;;
  esac
}

SERVICE_NAME="${1:?usage: deploy-service.sh <service> (one of: ${SERVICES})}"
resolve_service "$SERVICE_NAME"

cd "$(dirname "${BASH_SOURCE[0]}")"
SETTLE_TIMEOUT_SECS="${SETTLE_TIMEOUT_SECS:-1200}"
ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
ECR_HOST="${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com"
SCRATCH_DIR="$(mktemp -d)"
trap 'rm -rf "$SCRATCH_DIR"' EXIT

# True once $1 (a value of $SECONDS) is further in the past than the settle timeout.
timed_out() { [ $((SECONDS - $1)) -gt "$SETTLE_TIMEOUT_SECS" ]; }

TAG="${EXISTING_TAG:-${SERVICE_NAME}-$(date -u +%Y%m%d%H%M%S)}"
IMAGE_URI="${ECR_HOST}/${ECR_REPOSITORY}:${TAG}"
LOCAL_IMAGE="${LOCAL_IMAGE:-${ECR_REPOSITORY}:latest}"

if [ -n "${EXISTING_TAG:-}" ]; then
  echo "==> reusing ${IMAGE_URI} (no push)"
  aws ecr describe-images --repository-name "$ECR_REPOSITORY" --region "$REGION" \
    --image-ids "imageTag=${TAG}" --query 'imageDetails[0].imageTags' --output text > /dev/null \
    || { echo "tag ${TAG} is not in ECR" >&2; exit 30; }
else
  if aws ecr describe-images --repository-name "$ECR_REPOSITORY" --region "$REGION" \
      --image-ids "imageTag=${TAG}" > /dev/null 2>&1; then
    echo "tag ${TAG} is already in ECR; a tag is never reused. Run again." >&2
    exit 31
  fi
  echo "==> tagging ${LOCAL_IMAGE} as ${IMAGE_URI}"
  docker tag "$LOCAL_IMAGE" "$IMAGE_URI"

  # A private docker config with no credential helper: a helper that blocks on a keychain prompt
  # hangs forever in any unattended shell.
  echo "==> ecr login"
  DOCKER_CONFIG_DIR="${SCRATCH_DIR}/docker-config"
  mkdir -p "$DOCKER_CONFIG_DIR"
  echo '{}' > "${DOCKER_CONFIG_DIR}/config.json"
  aws ecr get-login-password --region "$REGION" \
    | docker --config "$DOCKER_CONFIG_DIR" login --username AWS --password-stdin "$ECR_HOST"

  echo "==> pushing ${IMAGE_URI}"
  docker --config "$DOCKER_CONFIG_DIR" push "$IMAGE_URI"
fi

# deploy-box.sh renders every container the roll does not name at "latest". Name the tag each other
# container runs now, read from the box's own Compose file, so rolling one service leaves the rest alone.
BOX_ID="$(aws cloudformation describe-stacks --stack-name "$BOX_STACK" --region "$REGION" \
  --query "Stacks[0].Outputs[?OutputKey=='InstanceId'].OutputValue" --output text)"
[ -n "$BOX_ID" ] && [ "$BOX_ID" != None ] || { echo "no instance in stack ${BOX_STACK}" >&2; exit 33; }

echo "==> reading the tags the box runs now"
READ_JSON="$(jq -n --arg c "cat ${BOX_DIR}/compose.json 2>/dev/null || echo '{}'" '{commands: [$c]}')"
COMMAND_ID="$(aws ssm send-command --instance-ids "$BOX_ID" --document-name AWS-RunShellScript --region "$REGION" \
  --parameters "$READ_JSON" --query 'Command.CommandId' --output text)"
for _ in $(seq 1 30); do
  sleep 2
  state="$(aws ssm get-command-invocation --command-id "$COMMAND_ID" --instance-id "$BOX_ID" --region "$REGION" \
    --query Status --output text 2>/dev/null || echo Pending)"
  [ "$state" != InProgress ] && [ "$state" != Pending ] && break
done
[ "$state" = Success ] || { echo "could not read the box's Compose file (${state}); nothing was rolled" >&2; exit 32; }
aws ssm get-command-invocation --command-id "$COMMAND_ID" --instance-id "$BOX_ID" --region "$REGION" \
  --query StandardOutputContent --output text > "${SCRATCH_DIR}/compose.json"

TAGS=()
for name in $SERVICES; do
  if [ "$name" = "$SERVICE_NAME" ]; then
    TAGS+=("${name}=${TAG}")
    continue
  fi
  image="$(jq -r --arg n "$name" '.services[$n].image // empty' "${SCRATCH_DIR}/compose.json")"
  # A container the box does not run yet starts at its "latest" image.
  if [ -n "$image" ]; then TAGS+=("${name}=${image##*:}"); fi
done
echo "==> rolling ${TAGS[*]}"

# Only this container is replaced, so only its log is captured first (SKIP_LOG_CAPTURE=1 skips it).
LOG_CAPTURE_SERVICES="$SERVICE_NAME" bash ./deploy-box.sh "${TAGS[@]}"

# The deploy itself is done. End with the smoke, which reports separately, unless the caller runs it.
echo "==> deploy succeeded"
[ -z "${SMOKE_BY_COMMAND:-}" ] || { echo "==> rolled taskdef=${TASKDEF:-} tag=${TAG}"; exit 0; }
bash ./smoke-after-deploy.sh
