# frozen_string_literal: true

require "hecks"
require "hecks/fuzzing"
require "json"
require "fileutils"
require_relative "../tools"
require_relative "argument_gate_matrix/violations"
require_relative "argument_gate_matrix/rows"
require_relative "argument_gate_matrix/dispatching"

module Hecks
  module Tools
    # Generates the argument-gate ordering matrix: for each adjacent pair of gates a command
    # can violate, one input violating both, with Ruby's refusal recorded as the expected answer.
    # A row is kept only when Ruby's dispatch trace shows the earlier gate refused (ADR 0010).
    #
    #   hecks argument_gate_matrix            # report only
    #   hecks argument_gate_matrix --write    # rewrite the matrix + fixtures
    module ArgumentGateMatrix
      # Domains chosen for the argument shapes they carry: value objects, references, roles,
      # entity commands, closed sets, and an identity key colliding with an argument.
      DOMAINS = %w[
        examples/banking
        examples/pizzas
        examples/roster
        examples/chess
        qa/stress_domains/nested_pieces
        qa/stress_domains/ledger_ordering
      ].freeze

      MATRIX_FILE = "spec/corpus/argument_gate_order/matrix.json"

      FIXTURE_NOTE = "GENERATED by hecks argument_gate_matrix (roadmap D2) — one step per adjacent pair of " \
                     "argument-gate steps this domain's own commands can violate, each input violating BOTH, so " \
                     "the refusal that wins is the EARLIER declared step's. Ruby's own answers are pinned in " \
                     "spec/corpus/argument_gate_order/matrix.json; this file holds the Rust port to the same rows " \
                     "through the ordinary conformance harness. Do not hand-edit — re-run " \
                     "hecks argument_gate_matrix --confirm."

      # Gate order comes from the vocabulary table, so reordering it reorders the pairs.
      AGGREGATE_ORDER = Hecks::Vocabulary.symbols("AggregateDispatchOrder").map(&:to_s)
      ENTITY_ORDER    = Hecks::Vocabulary.symbols("EntityDispatchOrder").map(&:to_s)
      # `decode_arguments` is a no-op in Ruby, so no input can violate it.
      GATES = %w[refuse_unknown_arguments refuse_absent_arguments normalize_args refuse_role_mismatch resolve_references].freeze
      # The identity-resolution step that follows the gates in both orders.
      SETTLES = { "aggregate" => "hydrate", "entity" => "hydrate_parent" }.freeze

      # A `Random` whose no-argument `rand` is a constant above every "generate something invalid"
      # probability in `ValueGenerator`, so generated payloads are always valid.
      class SteadyRandom
        def initialize(seed) = @random = Random.new(seed)

        def rand(limit = nil) = limit.nil? ? 0.99 : @random.rand(limit)

        def bytes(count) = @random.bytes(count)
      end

      extend Violations
      extend Rows
      extend Dispatching

      module_function

      # Dispatches every candidate row of each domain, keeps the ones Ruby's dispatch trace
      # confirms, and prints how many; with `--write` it rewrites the matrix and the Rust
      # conformance fixtures.
      def main(argv, root: Tools::ROOT)
        kept, dropped = sweep(root)
        report(kept, dropped)
        write(root, kept) if argv.include?("--write")
        0
      end

      def sweep(root)
        kept = []
        dropped = []
        DOMAINS.each do |domain|
          Hecks::Fuzzing::IsolatedBoot.call(File.join(root, domain)) do |copy|
            sweep_domain(Hecks.boot(copy, environment: nil), domain, kept, dropped)
          end
        end
        [kept, dropped]
      end

      # Files each candidate row of one booted domain under `kept` or `dropped`.
      def sweep_domain(runtime, domain, kept, dropped)
        chapters = runtime.registry.bluebooks.keys
        chapter = chapters.find { |name| candidates(runtime, name).any? } || chapters.first
        candidates(runtime, chapter).each do |row|
          verdict, judged = judge(runtime, row, domain)
          (verdict == :kept ? kept : dropped) << judged
        end
      end

      def report(kept, dropped)
        pairs = kept.group_by { |row| row[:pair].join(" before ") }.transform_values(&:size)
        puts "kept #{kept.size} rows over #{DOMAINS.size} domains; dropped #{dropped.size}"
        pairs.sort.each { |pair, count| puts "  #{pair}: #{count}" }
        report_dropped(dropped)
      end

      def report_dropped(dropped)
        dropped.group_by { |row| row[:reason] }.sort_by { |_, rows| -rows.size }.each do |reason, rows|
          puts "  dropped #{rows.size}: #{reason}"
        end
      end

      def write(root, kept)
        path = File.join(root, MATRIX_FILE)
        FileUtils.mkdir_p(File.dirname(path))
        File.write(path, "#{JSON.pretty_generate(matrix_for(kept))}\n")
        puts "wrote #{path}"

        kept.group_by { |row| row[:domain] }.each { |domain, rows| write_fixture(root, domain, rows) }
      end

      def matrix_for(kept)
        {
          "generated_by"    => "hecks argument_gate_matrix",
          "aggregate_order" => AGGREGATE_ORDER,
          "entity_order"    => ENTITY_ORDER,
          "rows"            => kept.map { |row| matrix_row(row) }
        }
      end

      def matrix_row(row)
        { "domain" => row[:domain], "verb" => row[:verb], "kind" => row[:kind], "pair" => row[:pair],
          "violates" => row[:violates], "role" => row[:role], "args" => row[:args], "expected" => row[:expected] }
      end

      def write_fixture(root, domain, rows)
        path = File.join(root, "spec/corpus/rust_conformance/argument_gate_order_#{File.basename(domain)}.json")
        fixture = { "domain" => domain, "note" => FIXTURE_NOTE, "steps" => rows.map { |row| fixture_step(row) } }
        File.write(path, "#{JSON.pretty_generate(fixture)}\n")
        puts "wrote #{path}"
      end

      def fixture_step(row)
        step = { "verb" => row[:verb] }
        step["role"] = row[:role] if row[:role]
        step["args"] = row[:args]
        step
      end
    end
  end
end
