# frozen_string_literal: true

require "json"
require_relative "../tools"

module Hecks
  module Tools
    # Prints one generated, valid dispatch sequence for a domain, using the generator `hecks fuzz`
    # drives.
    #
    #   hecks generate_sequence <domain> [--seed N] [--steps N] [--adversarial fraction]
    #
    # `--adversarial` mutates the sequence as `hecks quality_control query sweep.run` does; 0 (off)
    # by default.
    module SequenceScript
      USAGE = "usage: hecks generate_sequence <domain> [--seed N] [--steps N] [--adversarial FRACTION]"

      module_function

      # Prints the sequence as a replayable script.
      #
      # @param argv [Array<String>] the domain, then the flags
      # @param root [String] the checkout (unused: the domain is named by path)
      # @return [Integer] 0
      # @raise [SystemExit] with the usage line when an argument is missing or unknown
      def main(argv, root: Tools::ROOT)
        _ = root
        require "hecks"
        require "hecks/fuzzing"
        args = argv.dup
        domain = args.shift or abort USAGE
        seed, steps, adversarial = flags(args)

        generated = Hecks::Fuzzing::SequenceGenerator.generate(domain, seed: seed, steps: steps,
                                                                       adversarial: adversarial)
        puts JSON.pretty_generate(
          name:  "#{File.basename(domain)}-generated",
          note:  "generated by hecks generate_sequence — seed #{seed}, #{steps} steps requested (#{generated.length} produced)",
          steps: generated
        )
        0
      end

      # @param args [Array<String>] the flags, consumed
      # @return [Array(Integer, Integer, Float)] the seed, the step count and the fraction
      def flags(args)
        seed  = 1
        steps = 30
        adversarial = 0.0
        until args.empty?
          case args.shift
          when "--seed"        then seed  = Integer(args.shift)
          when "--steps"       then steps = Integer(args.shift)
          when "--adversarial" then adversarial = Float(args.shift)
          else abort USAGE
          end
        end
        [seed, steps, adversarial]
      end
    end
  end
end
