# frozen_string_literal: true

require "json"
require_relative "../tools"

module Hecks
  module Tools
    # Prints one generated, valid dispatch sequence for a domain, using the generator `hecks fuzz`
    # drives.
    #
    #   hecks generate_sequence <domain> [--seed N] [--steps N] [--adversarial fraction]
    #
    # `--adversarial` mutates the sequence as `hecks quality_control query sweep.run` does; 0 (off)
    # by default.
    module SequenceScript
      USAGE = "usage: hecks generate_sequence <domain> [--seed N] [--steps N] [--adversarial FRACTION]"

      module_function

      # Prints the sequence as a replayable script.
      #
      # @param argv [Array<String>] the domain, then the flags
      # @param root [String] the checkout (unused: the domain is named by path)
      # @return [Integer] 0
      # @raise [SystemExit] with the usage line when an argument is missing or unknown
      def main(argv, root: Tools::ROOT)
        _ = root
        require "hecks"
        require "hecks/fuzzing"
        args = argv.dup
        domain = args.shift or abort USAGE
        seed, steps, adversarial = flags(args)

        puts JSON.pretty_generate(script_for(domain, seed, steps, adversarial))
        0
      end

      # @return [Hash] the replayable script: its name, a note and the generated steps
      def script_for(domain, seed, steps, adversarial)
        generated = Hecks::Fuzzing::SequenceGenerator.generate(domain, seed: seed, steps: steps,
                                                                       adversarial: adversarial)
        {
          name:  "#{File.basename(domain)}-generated",
          note:  "generated by hecks generate_sequence — seed #{seed}, #{steps} steps requested (#{generated.length} produced)",
          steps: generated
        }
      end

      # @param args [Array<String>] the flags, consumed
      # @return [Array(Integer, Integer, Float)] the seed, the step count and the fraction
      def flags(args)
        values = { seed: 1, steps: 30, adversarial: 0.0 }
        apply_flag(values, args.shift, args) until args.empty?
        values.values_at(:seed, :steps, :adversarial)
      end

      # Records one flag in `values`, taking its value from `rest`.
      def apply_flag(values, flag, rest)
        case flag
        when "--seed"        then values[:seed] = Integer(rest.shift)
        when "--steps"       then values[:steps] = Integer(rest.shift)
        when "--adversarial" then values[:adversarial] = Float(rest.shift)
        else abort USAGE
        end
      end
    end
  end
end
