// Generated by hecks site site_projection.project_site. Do not edit.

// Which commands apply to a record now, and which of them need a page of their own.
import type { Aggregate, Command } from "../schema.ts";

type State = Record<string, unknown>;

/** Whether a command applies to an instance in its present state: a lifecycle move only from its states. */
export function available(agg: Aggregate, command: Command, state: State): boolean {
  const move = agg.lifecycle?.transitions.find((transition) => transition.verb === command.name);
  return !move || !agg.lifecycle || move.from.includes(String(state[agg.lifecycle.field]));
}

/** What a command needs asked first: it takes input, or it is destructive. */
export const needsPage = (command: Command): boolean => command.attributes.length > 0 || command.destructive;
