// Generated by hecks site site_projection.project_site. Do not edit.

// A record as the site shows it, in a side drawer beside the editor. The row's `preview` is an address
// template; the record's key and its parts fill it, and the page frames the result. This is only a
// framed address: nothing of the editor is sent to it and nothing is injected into it, and the
// editor's content security policy names its origin (and no other) as a place a frame may load from.
//
// The frame is sandboxed with `allow-scripts allow-same-origin` and nothing else. The site's own
// scripts must run for the page to look as it does, and without `allow-same-origin` the page would
// have an opaque origin, so its storage, its cookies and its requests to itself would all fail. On a
// site served from another origin the flag lets the page keep its own origin and gives it no way to
// reach the editor. A path template is on the editor's own origin, where the pair removes the sandbox
// altogether: use an absolute address for a site served elsewhere.
import { EDITOR } from "../config.ts";
import type { Aggregate } from "../schema.ts";
import { esc } from "./html.ts";
import { icon } from "./icons.ts";
import { partsOf } from "./links.ts";
import type { Parts } from "./links.ts";
import { pictureAggregate, schedulingAggregate } from "./world.ts";
import { label } from "./words.ts";

/** A value placed in an address: encoded, with the colon of a key left as it is. */
const placed = (value: string): string => encodeURIComponent(value).replace(/%3A/gi, ":");

/** The address a record is previewed at, or null when the row names no preview. */
export function previewUrl(agg: Aggregate, id: string): string | null {
  if (!EDITOR.preview) return null;
  const parts = partsOf(agg, id);
  return EDITOR.preview.replace(/\{(key|kind|slug|id)\}/g, (_, name: keyof Parts) => placed(parts[name]));
}

/** What a page needs to offer a preview: the button for the heading, and the drawer for the end of the page. */
export interface Tools {
  button: string;
  drawer: string;
}

const NONE: Tools = { button: "", drawer: "" };

const WIDTHS = [
  ["phone", "Phone", "375 pixels wide"],
  ["tablet", "Tablet", "768 pixels wide"],
  ["desktop", "Desktop", "the width of the window"],
] as const;

function widths(): string {
  const buttons = WIDTHS.map(
    ([name, text, note]) =>
      `<button type="button" class="btn btn-sm join-item" data-preview-width="${name}" aria-pressed="${name === "desktop" ? "true" : "false"}" title="${text}, ${note}">${icon(name)}<span class="hidden sm:inline">${text}</span></button>`,
  );
  return `<div class="join" role="group" aria-label="Preview width">${buttons.join("")}</div>`;
}

function drawer(agg: Aggregate, id: string, url: string): string {
  const title = `Preview of ${label(agg.name).toLowerCase()} ${id}`;
  return `<div class="drawer drawer-end" data-preview>
<input id="preview-toggle" type="checkbox" class="drawer-toggle" aria-hidden="true" tabindex="-1">
<div class="drawer-side z-40">
<label for="preview-toggle" aria-label="Close the preview" class="drawer-overlay"></label>
<section class="flex h-full w-full max-w-6xl flex-col border-l border-base-300 bg-base-200" role="dialog" aria-modal="true" aria-label="${esc(title)}">
<div class="flex flex-wrap items-center gap-2 border-b border-base-300 bg-base-100 p-2">
<h2 class="mr-auto px-2 text-base">Preview</h2>
${widths()}
<button type="button" class="btn btn-sm" data-preview-refresh>${icon("refresh")}<span class="hidden sm:inline">Refresh</span></button>
<a class="btn btn-sm" href="${esc(url)}" target="_blank" rel="noopener" data-preview-external>${icon("external")}<span class="hidden sm:inline">Open in new tab</span></a>
<button type="button" class="btn btn-ghost btn-sm btn-square" aria-label="Close the preview" data-preview-close>${icon("close")}</button>
</div>
<div class="grid min-h-0 flex-1 justify-items-center overflow-auto p-2" data-preview-stage>
<iframe class="h-full w-full max-w-full border border-base-300 bg-white" title="${esc(title)}" sandbox="allow-scripts allow-same-origin" referrerpolicy="no-referrer" data-preview-frame data-src="${esc(url)}"></iframe>
</div>
<p class="px-3 pb-2 text-xs text-muted">This is the site's own page at <span class="break-all">${esc(url)}</span>. It reads only: nothing here publishes. A page that stays blank is one the site does not let this editor show in a frame.</p>
</section>
</div>
</div>`;
}

/** Whether a record of `agg` is something the site shows a page for: the pictures' records and the scheduled actions are not. */
const shown = (agg: Aggregate): boolean => agg !== pictureAggregate() && agg !== schedulingAggregate();

/** The preview button and drawer for one record, or nothing when the row names no preview or the record has no page. */
export function previewTools(agg: Aggregate, id: string): Tools {
  const url = shown(agg) ? previewUrl(agg, id) : null;
  if (!url) return NONE;
  const button = `<a class="btn" href="${esc(url)}" target="_blank" rel="noopener" data-preview-open="preview-toggle">${icon("eye")}Preview</a>`;
  return { button, drawer: drawer(agg, id, url) };
}
