// Generated by hecks site site_projection.project_site. Do not edit.

// Actions scheduled for a record, and every pending action across records. The editor only makes and
// changes the scheduled-action records (their commands, found by shape; see `Scheduling` in
// schema.ts): nothing here runs an action, and a record's own state never changes because of one. A
// runner elsewhere reads the records at their due time and moves each out of its first state. A time
// is chosen with the browser's own date-and-time control, in the viewer's zone.
import { at, mayEdit } from "../names.ts";
import { SCHEMA } from "../schema.ts";
import type { Aggregate, Command, Scheduling } from "../schema.ts";
import { available } from "./availability.ts";
import { confirmDialog, dialogId } from "./dialogs.ts";
import { fields } from "./fields.ts";
import { esc, href, statusBadge } from "./html.ts";
import { backInput, partsOf, plainName, plainText, withBack } from "./links.ts";
import { momentTime, secondsOf } from "./moments.ts";
import type { World } from "./world.ts";
import { schedulingAggregate } from "./world.ts";
import { commandLabel, label, singular } from "./words.ts";

type State = Record<string, unknown>;
type Row = [string, State];

/** The scheduling aggregate with its parts, when this editor has one. */
function scheduler(): { agg: Aggregate; spec: Scheduling } | null {
  const agg = schedulingAggregate();
  return agg && SCHEMA.scheduling ? { agg, spec: SCHEMA.scheduling } : null;
}

/** Whether a scheduled action's subject can be a record of `agg`: its key's kinds name that aggregate. */
function subjectIs(sched: Aggregate, spec: Scheduling, agg: Aggregate): boolean {
  const subject = sched.attributes.find((attr) => attr.name === spec.subject);
  return (subject?.picker?.kinds ?? []).some((kind) => kind.target === agg.name && kind.chapter === agg.chapter);
}

/** Whether records of `agg` have a Schedule panel and the person may use it. */
export function schedules(agg: Aggregate, role: string | null): boolean {
  const found = scheduler();
  return found !== null && subjectIs(found.agg, found.spec, agg) && mayEdit(found.agg, role);
}

/** The query that lists one subject's actions, with the key in the shape its argument takes, or null when there is none. */
export function subjectQuery(agg: Aggregate, id: string): { name: string; args: State } | null {
  const found = scheduler();
  const argument = found?.agg.queries.find((query) => query.name === found.spec.query)?.attributes[0];
  if (!found || !argument || !found.spec.query) return null;
  const attr = found.agg.attributes.find((candidate) => candidate.name === found.spec.subject);
  const key = partsOf(agg, id).key;
  const parts = attr ? (found.agg.valueObjects[attr.type] ?? []) : [];
  return { name: found.spec.query, args: { [argument.name]: attr && attr.kind === "object" && parts.length === 1 ? { [parts[0].name]: key } : key } };
}

const stateOf = (sched: Aggregate, row: State): unknown => (sched.lifecycle ? row[sched.lifecycle.field] : undefined);

const dueIn = (spec: Scheduling, row: State): number | null => secondsOf(row[spec.due]);

/** Soonest first; an action with no readable time goes last. */
const soonest = (spec: Scheduling) => (a: Row, b: Row): number => (dueIn(spec, a[1]) ?? Infinity) - (dueIn(spec, b[1]) ?? Infinity);

const when = (spec: Scheduling, row: State): string => {
  const seconds = dueIn(spec, row);
  return seconds === null ? `<span class="text-muted">No time set</span>` : momentTime(seconds, "datetime");
};

const actionText = (spec: Scheduling, row: State): string => label(plainText(row[spec.action]));

function command(sched: Aggregate, name: string | undefined): Command | undefined {
  return sched.commands.find((candidate) => candidate.name === name);
}

/** The buttons of one pending action, and the question its cancel asks. */
function tools(sched: Aggregate, spec: Scheduling, id: string, row: State, here: string, index: number): { buttons: string; dialog: string } {
  const change = command(sched, spec.reschedule);
  const stop = command(sched, spec.cancel);
  const page = (cmd: Command): string => withBack(href(...at(sched), "id", id, cmd.name), here);
  const reschedule = change && available(sched, change, row) ? `<a class="btn btn-sm" href="${esc(page(change))}">${esc(commandLabel(sched, change))}</a>` : "";
  if (!stop || !available(sched, stop, row)) return { buttons: reschedule, dialog: "" };
  const suffix = String(index);
  const cancel = `<a class="btn btn-sm btn-error btn-outline" href="${esc(page(stop))}" data-confirm="${dialogId(stop, suffix)}">${esc(commandLabel(sched, stop))}</a>`;
  const asking = { suffix, back: { path: here, label: "" } };
  return { buttons: `${reschedule}${cancel}`, dialog: confirmDialog(sched, stop, href(...at(sched), "id", id, stop.name), id, undefined, asking) };
}

function pendingList(sched: Aggregate, spec: Scheduling, rows: Row[], here: string): string {
  if (rows.length === 0) return `<p class="text-muted">Nothing is scheduled for this record.</p>`;
  const lines = rows.map(([id, row], index) => {
    const { buttons, dialog } = tools(sched, spec, id, row, here, index);
    return `<li class="flex flex-wrap items-center gap-x-4 gap-y-2 py-3"><span class="font-semibold">${esc(actionText(spec, row))}</span><span>${when(spec, row)}</span><span class="ml-auto flex flex-wrap gap-2">${buttons}</span>${dialog}</li>`;
  });
  return `<ul class="divide-y divide-base-300" aria-label="Pending actions">${lines.join("\n")}</ul>`;
}

function pastList(sched: Aggregate, spec: Scheduling, rows: Row[]): string {
  if (rows.length === 0) return "";
  const lines = rows.map(([, row]) => {
    const reason = spec.reason && plainText(row[spec.reason]) !== "" ? `<span class="basis-full text-sm text-muted">${esc(plainText(row[spec.reason]))}</span>` : "";
    return `<li class="flex flex-wrap items-center gap-x-4 gap-y-1 py-2"><span>${esc(actionText(spec, row))}</span><span>${when(spec, row)}</span>${statusBadge(sched, stateOf(sched, row))}${reason}</li>`;
  });
  return `<h3 class="mb-1 mt-6 text-sm">Earlier</h3>\n<ul class="divide-y divide-base-300" aria-label="Earlier actions">${lines.join("\n")}</ul>`;
}

/** The form that adds an action for `key`: which action, when, and anything else the creating command takes. */
function addForm(sched: Aggregate, spec: Scheduling, subject: string, here: string): string {
  const make = command(sched, spec.schedule);
  const subjectAttr = sched.attributes.find((attr) => attr.name === spec.subject);
  if (!make || !subjectAttr) return "";
  const named = new Map(make.attributes.map((attr) => [attr.name, attr]));
  const rest = make.attributes.filter((attr) => ![spec.subject, spec.action, spec.due].includes(attr.name) && !(spec.generated && attr.name === sched.identity));
  const asked = [named.get(spec.action), named.get(spec.due), ...rest].flatMap((attr) => attr ?? []);
  return `<form class="mt-6 max-w-xl border-t border-base-300 pt-4" method="post" action="${esc(href(...at(sched), "new", make.name))}" data-form>
<h3 class="text-sm">Add an action</h3>
${backInput({ path: here, label: "" })}<input type="hidden" name="${esc(plainName(sched, subjectAttr))}" value="${esc(subject)}">
${fields(sched, asked, {}, null, true, {})}
<div class="mt-4"><button type="submit" class="btn btn-neutral" data-busy>${esc(label(make.name))}</button></div>
</form>`;
}

/** The Schedule panel of a record: its pending actions, a form to add one, and the ones that have ended. */
export function schedulePanel(agg: Aggregate, id: string, world: World, here: string): string {
  const found = scheduler();
  if (!found || !schedules(agg, world.role)) return "";
  const { agg: sched, spec } = found;
  const key = partsOf(agg, id).key;
  const rows = (world.actions ?? world.rows(sched)).filter(([, row]) => plainText(row[spec.subject]) === key);
  const pending = rows.filter(([, row]) => stateOf(sched, row) === spec.pending).sort(soonest(spec));
  const ended = rows.filter(([, row]) => stateOf(sched, row) !== spec.pending).sort((a, b) => soonest(spec)(b, a)).slice(0, 10);
  return `<section class="border border-base-300 bg-base-100 p-4 sm:p-6" aria-labelledby="schedule-title">
<h2 id="schedule-title" class="text-lg">Schedule</h2>
<p class="mb-4 mt-1 max-w-prose text-sm text-muted">Actions saved here are run later, at the time you choose, by something outside this editor. Saving, changing or cancelling one here never publishes or changes this ${esc(singular(agg.name))} itself.</p>
${pendingList(sched, spec, pending, here)}
${addForm(sched, spec, key, here)}
${pastList(sched, spec, ended)}
</section>`;
}

/** Where a subject key leads: the record's page when the editor holds it, else the key as plain text. */
function subjectLink(key: string, sched: Aggregate, spec: Scheduling, world: World): string {
  const kind = key.slice(0, Math.max(key.indexOf(":"), 0));
  const subject = sched.attributes.find((attr) => attr.name === spec.subject);
  const target = (subject?.picker?.kinds ?? []).find((candidate) => candidate.kind === kind && candidate.target);
  const aggregate = target && SCHEMA.aggregates.find((candidate) => candidate.name === target.target && candidate.chapter === target.chapter);
  const id = aggregate && [key.slice(kind.length + 1), key].find((candidate) => world.lookup(aggregate, candidate));
  return aggregate && id ? `<a class="link" href="${esc(href(...at(aggregate), "id", id))}">${esc(key)}</a>` : esc(key);
}

/** Every pending action, soonest first, with the record each is for and the buttons that change it. */
export function scheduledTable(world: World, here: string): string {
  const found = scheduler();
  if (!found) return "";
  const { agg: sched, spec } = found;
  const rows = world.rows(sched).filter(([, row]) => stateOf(sched, row) === spec.pending).sort(soonest(spec));
  if (rows.length === 0) return `<p class="text-muted">Nothing is scheduled.</p>`;
  const lines = rows.map(([id, row], index) => {
    const { buttons, dialog } = tools(sched, spec, id, row, here, index);
    const key = plainText(row[spec.subject]);
    return `<tr><td>${when(spec, row)}</td><td>${esc(actionText(spec, row))}</td><td class="break-all">${subjectLink(key, sched, spec, world)}</td><td><div class="flex flex-wrap justify-end gap-2">${buttons}</div>${dialog}</td></tr>`;
  });
  const head = `<tr><th scope="col">When</th><th scope="col">Action</th><th scope="col">For</th><th scope="col"><span class="sr-only">Change</span></th></tr>`;
  return `<div class="overflow-x-auto border border-base-300 bg-base-100"><table class="table"><thead>${head}</thead><tbody>${lines.join("\n")}</tbody></table></div>`;
}
