// Generated by hecks site site_projection.project_site. Do not edit.

// The words the editor shows people. The domain's names are CamelCase and singular; people read
// sentence case, plural for a list, and the same verb through a whole flow: the button that says
// "Publish" leaves a notice that says "Published." Nothing here asks the domain; it reads names.
import type { Aggregate, Command } from "../schema.ts";

/** The lower-case words of a CamelCase or snake_case name: "MediaItem" is "media item". */
export const humanize = (name: string): string =>
  name
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/_/g, " ")
    .toLowerCase();

/** `text` with its first letter capitalised. */
export const capital = (text: string): string => text.charAt(0).toUpperCase() + text.slice(1);

/** A name as a sentence-case label: "SaveDraft" is "Save draft". */
export const label = (name: string): string => capital(humanize(name));

/** The plural of an English noun, for the common regular shapes. */
export function pluralOf(noun: string): string {
  if (/[^aeiou]y$/.test(noun)) return `${noun.slice(0, -1)}ies`;
  if (/(s|x|z|ch|sh)$/.test(noun)) return `${noun}es`;
  return `${noun}s`;
}

/** An aggregate as a list's name: "MediaItem" is "Media items". */
export function plural(name: string): string {
  const words = humanize(name).split(" ");
  words[words.length - 1] = pluralOf(words[words.length - 1]);
  return capital(words.join(" "));
}

/** The limits a list's holder gives it as a sentence ("At least 1 and at most 60."), or nothing when it gives none. */
export function limitsNote(min?: number, max?: number): string {
  if (min && max) return `At least ${min} and at most ${max}.`;
  return min ? `At least ${min}.` : max ? `At most ${max}.` : "";
}

/** An aggregate as one thing, lower case: "MediaItem" is "media item". */
export const singular = (name: string): string => humanize(name);

const IRREGULAR: Record<string, string> = {
  set: "set", put: "put", send: "sent", make: "made", undo: "undone", redo: "redone", show: "shown", withdraw: "withdrawn",
  draw: "drawn", hide: "hidden", write: "written", take: "taken", give: "given", keep: "kept", read: "read", pay: "paid", sell: "sold",
  begin: "begun", run: "run", get: "got", find: "found", build: "built", choose: "chosen", leave: "left", hold: "held", lose: "lost",
  break: "broken", bring: "brought", cut: "cut", shut: "shut", split: "split", lay: "laid", say: "said", spend: "spent", lend: "lent",
  bind: "bound", wind: "wound", know: "known", grow: "grown", throw: "thrown", see: "seen", do: "done", go: "gone", have: "had",
};

const DOUBLED = new Set([
  "submit", "admit", "commit", "omit", "plan", "drop", "ship", "stop", "skip", "tag", "pin", "log", "map", "ban", "trim", "wrap",
  "grab", "strip", "refer", "transfer", "permit", "equip", "occur", "defer", "prefer",
]);

const PREFIXES = ["re", "un", "over", "out", "pre", "mis"];

/** The irregular participle of `verb`, or of the verb under a prefix ("reset" is "set" again), or undefined. */
function irregular(verb: string): string | undefined {
  if (Object.hasOwn(IRREGULAR, verb)) return IRREGULAR[verb];
  const prefix = PREFIXES.find((one) => verb.startsWith(one) && Object.hasOwn(IRREGULAR, verb.slice(one.length)));
  return prefix ? `${prefix}${IRREGULAR[verb.slice(prefix.length)]}` : undefined;
}

/** The past participle of a verb: "publish" is "published", "submit" is "submitted", "begin" is "begun", "cancel" is "canceled". */
export function past(verb: string): string {
  const odd = irregular(verb);
  if (odd) return odd;
  if (verb.endsWith("e")) return `${verb}d`;
  if (/[^aeiou]y$/.test(verb)) return `${verb.slice(0, -1)}ied`;
  return DOUBLED.has(verb) ? `${verb}${verb.slice(-1)}ed` : `${verb}ed`;
}

/** A word cut back to what its forms share: "schedule", "scheduled" and "scheduling" are all "schedul". */
const stem = (word: string): string => word.replace(/(ing|ed|es|e|d|s)$/, "");

/**
 * What a command's button says. A command named by one word acts on a thing the page already
 * names, except one that makes something new: "Draft" on the articles page is "Draft article".
 */
export function commandLabel(agg: Aggregate, command: Command): string {
  const words = humanize(command.name).split(" ");
  return capital(command.creates && words.length === 1 ? `${words[0]} ${singular(agg.name)}` : words.join(" "));
}

/**
 * What the notice says when the command has run, in the same verb as its button: "Published draft."
 * When the thing's name already starts with the verb ("Schedule" making a "scheduled action") the
 * repeated word is dropped, so the notice reads "Scheduled action." and never "Scheduled scheduled action."
 */
export function done(agg: Aggregate, command: Command): string {
  const [verb, ...rest] = commandLabel(agg, command).toLowerCase().split(" ");
  const repeated = rest.length > 0 && stem(rest[0]) === stem(verb);
  const object = repeated ? rest.slice(1) : rest;
  return capital(`${[past(verb), ...object].join(" ")}.`);
}
