//! Assembles the "prelude" section of a per-aggregate generated `.rs`
//! file — everything `rust/project/domain_generator.rb#call` writes for
//! ONE aggregate BEFORE its commands loop starts: the file header, every
//! value object (+ its JSON/closed-set codec), every entity (+ its JSON
//! codec and, when routable, `extract_id`/`extract_wants`/
//! `self_identity`), the aggregate record itself (+ its JSON codec, the
//! `ToJson` trait bridge, and its own `extract_id` when routable).
//!
//! This is the real, verifiable byte-exact target for Stage 7's scoped
//! slice: commands/mutations/queries/read_models/reactions/ports/
//! registry (rust/project/{commands,mutations,queries,read_models,
//! reactions,ports,registry,bridging}.rb) are NOT ported this stage (see
//! the stage report), so a WHOLE aggregate `.rs` file can't be
//! reconstructed yet — but this prelude is a real, substantial,
//! contiguous PREFIX of that file, assembled by literally replicating
//! `domain_generator.rb`'s own `f.puts` call sequence up to (not
//! including) `aggregate[:commands].each`, so it byte-matches the
//! corresponding prefix of the real generated file directly.
//!
//! `f.puts` semantics matter for the exact byte output: Ruby's `puts`
//! appends a trailing "\n" ONLY IF the string doesn't already end in one
//! — `puts_str`/`puts_blank` below mirror that exactly, since several
//! `emit_*` functions already carry their own trailing "\n" (see their
//! own header comments) and several don't.

use crate::exemplar::Exemplar;
use crate::json::Json;
use crate::{json_codec, types};
use std::collections::HashMap;

fn puts_str(out: &mut String, s: &str) {
    out.push_str(s);
    if !s.ends_with('\n') {
        out.push('\n');
    }
}

fn puts_blank(out: &mut String) {
    out.push('\n');
}

fn lifecycle_extra_field(node: &Json) -> Vec<(String, String)> {
    match node.get("lifecycle") {
        None => vec![],
        Some(lifecycle) => {
            let field = lifecycle.get("field").and_then(Json::as_str).unwrap_or("");
            let ident = crate::naming::rust_ident_field(field);
            vec![(crate::naming::rust_field(field), format!("crate::kernel::Json::Str(self.{ident}.clone())"))]
        }
    }
}

/// One aggregate's own prelude text, or `None` when
/// `unsupported_attribute_types` says `domain_generator.rb` would skip
/// this aggregate entirely (no `.rs` file at all — matching that absence
/// exactly, not emitting a partial one).
pub fn aggregate_prelude(exemplar: &Exemplar, ir: &Json, aggregate: &Json, source_label: &str) -> Option<String> {
    let value_objects = aggregate.get("value_objects").map(Json::each).unwrap_or(&[]);
    let value_objects_by_name: HashMap<String, &Json> = value_objects.iter().map(|vo| (vo.get("name").and_then(Json::as_str).unwrap_or("").to_string(), vo)).collect();

    if !types::unsupported_attribute_types(aggregate, &value_objects_by_name).is_empty() {
        return None;
    }

    let aggregates_by_name: HashMap<String, &Json> = ir.get("aggregates").map(Json::each).unwrap_or(&[]).iter().map(|a| (a.get("name").and_then(Json::as_str).unwrap_or("").to_string(), a)).collect();

    let mut out = String::new();
    puts_str(&mut out, &format!("// GENERATED by bin/project_rust from {source_label}'s canonical IR."));
    puts_str(&mut out, "// Do not hand-edit — re-run bin/project_rust instead.");
    puts_str(&mut out, "#![allow(dead_code, unused_variables)]");
    puts_str(&mut out, "use crate::kernel::Expr;");
    puts_blank(&mut out);

    for vo in value_objects {
        puts_str(&mut out, &types::emit_value_object(exemplar, vo, &value_objects_by_name, &aggregates_by_name));
        puts_blank(&mut out);

        let closed_set = vo.get("closed_set").map(Json::as_bool).unwrap_or(false);
        let attrs = vo.get("attributes").map(Json::each).unwrap_or(&[]);
        if closed_set && attrs.len() == 1 {
            puts_str(&mut out, &json_codec::emit_closed_set_codec(exemplar, vo));
        } else if closed_set {
            puts_str(&mut out, &json_codec::emit_closed_set_table_codec(exemplar, vo));
        } else {
            let name = crate::naming::rust_ident(vo.get("name").and_then(Json::as_str).unwrap_or(""));
            puts_str(&mut out, &json_codec::emit_to_json_flat(exemplar, &name, attrs, &value_objects_by_name, false, &[], None));
            puts_blank(&mut out);
            puts_str(&mut out, &json_codec::emit_from_json_flat(exemplar, &name, attrs, &value_objects_by_name, None, None, false, false, None));
        }
        puts_blank(&mut out);
    }

    for entity in aggregate.get("entities").map(Json::each).unwrap_or(&[]) {
        puts_str(&mut out, &types::emit_entity(exemplar, entity, &value_objects_by_name));
        puts_blank(&mut out);

        let entity_name = crate::naming::rust_ident(entity.get("name").and_then(Json::as_str).unwrap_or(""));
        let entity_attrs = entity.get("attributes").map(Json::each).unwrap_or(&[]);
        let extra = lifecycle_extra_field(entity);
        puts_str(&mut out, &json_codec::emit_to_json_flat(exemplar, &entity_name, entity_attrs, &value_objects_by_name, false, &extra, None));
        puts_blank(&mut out);
        puts_str(&mut out, &json_codec::emit_from_json_state(exemplar, &entity_name, entity_attrs, &value_objects_by_name, false, &extra, None));
        puts_blank(&mut out);

        if json_codec::extract_id_supported(entity) {
            puts_str(&mut out, &json_codec::emit_extract_id(exemplar, entity));
            puts_blank(&mut out);
            puts_str(&mut out, &json_codec::emit_extract_wants(exemplar, entity));
            puts_blank(&mut out);
            puts_str(&mut out, &json_codec::emit_self_identity(exemplar, entity));
            puts_blank(&mut out);
        }
    }

    puts_str(&mut out, &types::emit_record(exemplar, aggregate, &value_objects_by_name));
    puts_blank(&mut out);

    let record_name = crate::naming::rust_ident(aggregate.get("name").and_then(Json::as_str).unwrap_or(""));
    let record_attrs = aggregate.get("attributes").map(Json::each).unwrap_or(&[]);
    let extra = lifecycle_extra_field(aggregate);
    puts_str(&mut out, &json_codec::emit_to_json_flat(exemplar, &record_name, record_attrs, &value_objects_by_name, true, &extra, Some(aggregate)));
    puts_blank(&mut out);
    puts_str(&mut out, &json_codec::emit_from_json_state(exemplar, &record_name, record_attrs, &value_objects_by_name, true, &extra, Some(aggregate)));
    puts_blank(&mut out);
    puts_str(
        &mut out,
        &format!("impl crate::kernel::ToJson for {record_name} {{\n    fn to_json(&self) -> crate::kernel::Json {{\n        {record_name}::to_json(self)\n    }}\n}}\n"),
    );
    puts_blank(&mut out);

    if json_codec::extract_id_supported(aggregate) {
        puts_str(&mut out, &json_codec::emit_extract_id(exemplar, aggregate));
        puts_blank(&mut out);
    }

    Some(out)
}
