require "spec_helper"
require "open3"
require "tmpdir"
require "hecks/fuzzing/domain_generator"

# `Hecks::Fuzzing::DomainGenerator` — blueprints, rendering and the
# domain-level shrink. The pure examples never boot a generated domain;
# the census example loads bluebooks the lightweight way FormCensus does,
# in its own subprocess, because every generated domain is `QaGenerated`
# and two shapes under one constant must not share a process.
RSpec.describe Hecks::Fuzzing::DomainGenerator do
  it "is a pure function of its seed" do
    first, again, other = [11, 11, 12].map { |seed| described_class.generate(seed: seed) }

    expect(again).to eq(first)
    expect(other).not_to eq(first)
  end

  # The two tables may differ, but only in one direction: `FORMS` is
  # `Builder::FORM_STEPS.keys`, this generator's own recipe list, never
  # `FormCensus::FORMS.keys` outright — if the census names a form this
  # generator has no recipe for (`corrects`, `role_gated`), taking `FORMS`
  # straight from the census would raise KeyError for any seed that drew
  # it. A census form with no builder is fine — it is simply never
  # generated. A builder for something the census cannot measure is not:
  # nothing would ever see the form it claims to be exercising.
  it "can only build forms the census can measure" do
    expect(described_class::FORMS - Hecks::Fuzzing::FormCensus::FORMS.keys).to be_empty
  end

  it "refuses a form FormCensus does not name" do
    expect { described_class.generate(seed: 1, forms: %w[lifecycle telepathy]) }.to raise_error(ArgumentError, /telepathy/)
  end

  it "renders a generated, clearly-marked bluebook under qa_generated/bluebook" do
    Dir.mktmpdir do |dir|
      domain = described_class.write(described_class.generate(seed: 3), dir)
      source = File.read(File.join(domain, "bluebook", "qa_generated.bluebook"))

      expect(domain).to end_with("/qa_generated")
      expect(source).to start_with("# GENERATED by Hecks::Fuzzing::DomainGenerator")
      expect(source).to include('Hecks.bluebook "QaGenerated" do')
      expect(File).to exist(File.join(dir, "blueprint.json"))
    end
  end

  it "puts the two forms it was asked for on the primary aggregate, as FormCensus itself measures them" do
    pairs = [%w[composite_id has_entity], %w[lifecycle closed_set], %w[multi_hop_where list_attr],
             %w[two_hop_given revalued_reference], %w[composite_piece has_default]]
    Dir.mktmpdir do |dir|
      pairs.each_with_index do |forms, index|
        domain = described_class.write(described_class.generate(seed: index, forms: forms), File.join(dir, index.to_s))
        script = "require 'hecks'; require 'hecks/fuzzing/form_census'; " \
                 "puts Hecks::Fuzzing::FormCensus.census(#{domain.inspect}).first.last.slice(*#{forms.inspect}).values.all?"
        output, status = Open3.capture2e("bundle", "exec", "ruby", "-I", File.join(InMemoryDomain::ROOT, "lib"), "-e", script,
                                         chdir: InMemoryDomain::ROOT)

        expect(status).to be_success, output
        expect(output.lines.last.strip).to eq("true"), "#{forms.join(' + ')} not both on the primary aggregate:\n#{output}"
      end
    end
  end

  # Regression for the generator finding hecks_qa's stress-domain sweep hit
  # at seed 357307 (`has_query` + `composite_piece`): `extras` can pick the
  # same entity name (`ENTITY_NAMES` is a small pool shared by every
  # aggregate) on a different aggregate than a form forced it onto, one
  # composite and one not — and an unqualified "LineAdded" collided across
  # aggregates with different shapes, which `validate_event_shapes!`
  # correctly refused. Every event name a generated domain can emit must be
  # unique to its shape, the same way `Hecks::Fuzzing::GeneratedDomainCheck`
  # actually boots one: an event name reused with a different shape is a
  # generator defect, never a legitimate finding.
  it "never lets two aggregates emit the same event name with a different shape" do
    (1..3000).each do |seed|
      blueprint = described_class.generate(seed: seed)
      shapes_by_event = Hash.new { |hash, key| hash[key] = [] }

      commands_of = ->(owner) { owner["commands"] + owner.fetch("entities", []).flat_map { |entity| entity["commands"] } }
      blueprint["aggregates"].each do |aggregate|
        commands_of.call(aggregate).each do |command|
          shape = command["args"].map { |arg| [arg["name"], arg["type"]] }
          command["emits"].each { |event| shapes_by_event[event] << shape }
        end
      end

      colliding = shapes_by_event.select { |_event, shapes| shapes.uniq.size > 1 }
      expect(colliding).to be_empty, "seed #{seed}: #{colliding.keys.join(', ')} emitted with more than one shape"
    end
  end

  describe "domain-level shrinking" do
    let(:blueprint) { described_class.generate(seed: 2, forms: %w[multi_hop_where closed_set]) }

    it "offers only strictly smaller, already-pruned candidates" do
      candidates = described_class.shrink_candidates(blueprint)

      expect(candidates).not_to be_empty
      candidates.each do |candidate|
        expect(described_class.removals(candidate).size).to be < described_class.removals(blueprint).size
        expect(described_class.prune(candidate)).to eq(candidate)
      end
    end

    it "never offers a candidate without the primary aggregate's identity or its creating command" do
      described_class.shrink_candidates(blueprint).each do |candidate|
        primary = candidate["aggregates"].first
        expect(primary["identity"]).to eq(blueprint["aggregates"].first["identity"])
        expect(primary["commands"].count { |command| command["creates"] }).to eq(1)
      end
    end

    it "drops a query whose only where needed an aggregate that was removed" do
      without_root = described_class.prune(described_class.remove_at(blueprint, ["aggregates", 2]))

      expect(without_root["aggregates"].size).to eq(2)
      expect(without_root["aggregates"].first["queries"].map { |query| query["name"] })
        .not_to include(a_string_starting_with("ThroughOpen"))
    end

    # qa/stress_domains/generated_revalued_shape was promoted with
    # `Reopen from closed` and no `Close`: the removal dropped Close's
    # transition, and pruning only asked whether Reopen's command still
    # existed, never whether its from-state could still be reached.
    it "drops a transition whose from-state a removal left unreachable" do
      lifecycled = described_class.generate(seed: 0, forms: %w[lifecycle closed_set])
      close = lifecycled["aggregates"].first["commands"].index { |command| command["name"] == "Close" }
      pruned = described_class.prune(described_class.remove_at(lifecycled, ["aggregates", 0, "commands", close]))

      transitions = pruned["aggregates"].first.dig("lifecycle", "transitions") || []
      expect(transitions.map { |transition| transition["command"] }).not_to include("Reopen")
    end

    it "shrinks greedily to what a finding needs and no further" do
      needs_hop_query = lambda do |candidate|
        candidate["aggregates"].first["queries"].any? { |query| query["name"].start_with?("ThroughOpen") }
      end
      current = blueprint
      while (smaller = described_class.shrink_candidates(current).find(&needs_hop_query))
        current = smaller
      end

      expect(current["aggregates"].size).to eq(3)
      expect(current["policies"]).to be_empty
      expect(described_class.shrink_candidates(current).none?(&needs_hop_query)).to be(true)
      expect(described_class.removals(current).size).to be < described_class.removals(blueprint).size
    end
  end
end
