require "spec_helper"
require "open3"
require "tmpdir"
require "hecks/fuzzing/domain_generator"

# `Hecks::Fuzzing::DomainGenerator`: blueprints, rendering and domain-level shrink.
# The census example runs in a subprocess because every generated domain is `QaGenerated`.
RSpec.describe Hecks::Fuzzing::DomainGenerator do
  it "is a pure function of its seed" do
    first, again, other = [11, 11, 12].map { |seed| described_class.generate(seed: seed) }

    expect(again).to eq(first)
    expect(other).not_to eq(first)
  end

  # The tables may differ in one direction only: a census form with no builder is never
  # generated, but a builder the census cannot measure exercises a form nothing sees.
  it "can only build forms the census can measure" do
    expect(described_class::FORMS - Hecks::Fuzzing::FormCensus::FORMS.keys).to be_empty
  end

  it "refuses a form FormCensus does not name" do
    expect { described_class.generate(seed: 1, forms: %w[lifecycle telepathy]) }.to raise_error(ArgumentError, /telepathy/)
  end

  it "renders a generated, clearly-marked bluebook under qa_generated/bluebook" do
    Dir.mktmpdir do |dir|
      domain = described_class.write(described_class.generate(seed: 3), dir)
      source = File.read(File.join(domain, "bluebook", "qa_generated.bluebook"))

      expect(domain).to end_with("/qa_generated")
      expect(source).to start_with("# GENERATED by Hecks::Fuzzing::DomainGenerator")
      expect(source).to include('Hecks.bluebook "QaGenerated" do')
      expect(File).to exist(File.join(dir, "blueprint.json"))
    end
  end

  it "puts the two forms it was asked for on the primary aggregate, as FormCensus itself measures them" do
    pairs = [%w[composite_id has_entity], %w[lifecycle closed_set], %w[multi_hop_where list_attr],
             %w[two_hop_given revalued_reference], %w[composite_piece has_default]]
    Dir.mktmpdir do |dir|
      pairs.each_with_index do |forms, index|
        domain = described_class.write(described_class.generate(seed: index, forms: forms), File.join(dir, index.to_s))
        script = "require 'hecks'; require 'hecks/fuzzing/form_census'; " \
                 "puts Hecks::Fuzzing::FormCensus.census(#{domain.inspect}).first.last.slice(*#{forms.inspect}).values.all?"
        output, status = Open3.capture2e("bundle", "exec", "ruby", "-I", File.join(InMemoryDomain::ROOT, "lib"), "-e", script,
                                         chdir: InMemoryDomain::ROOT)

        expect(status).to be_success, output
        expect(output.lines.last.strip).to eq("true"), "#{forms.join(' + ')} not both on the primary aggregate:\n#{output}"
      end
    end
  end

  # Regression (seed 357307, `has_query` + `composite_piece`): `extras` can reuse an entity
  # name from the shared pool on another aggregate, so an unqualified "LineAdded" collided
  # across shapes and `validate_event_shapes!` refused it. That is a generator defect.
  it "never lets two aggregates emit the same event name with a different shape" do
    (1..3000).each do |seed|
      blueprint = described_class.generate(seed: seed)
      shapes_by_event = Hash.new { |hash, key| hash[key] = [] }

      commands_of = ->(owner) { owner["commands"] + owner.fetch("entities", []).flat_map { |entity| entity["commands"] } }
      blueprint["aggregates"].each do |aggregate|
        commands_of.call(aggregate).each do |command|
          shape = command["args"].map { |arg| [arg["name"], arg["type"]] }
          command["emits"].each { |event| shapes_by_event[event] << shape }
        end
      end

      colliding = shapes_by_event.select { |_event, shapes| shapes.uniq.size > 1 }
      expect(colliding).to be_empty, "seed #{seed}: #{colliding.keys.join(', ')} emitted with more than one shape"
    end
  end

  describe "domain-level shrinking" do
    let(:blueprint) { described_class.generate(seed: 2, forms: %w[multi_hop_where closed_set]) }

    it "offers only strictly smaller, already-pruned candidates" do
      candidates = described_class.shrink_candidates(blueprint)

      expect(candidates).not_to be_empty
      candidates.each do |candidate|
        expect(described_class.removals(candidate).size).to be < described_class.removals(blueprint).size
        expect(described_class.prune(candidate)).to eq(candidate)
      end
    end

    it "never offers a candidate without the primary aggregate's identity or its creating command" do
      described_class.shrink_candidates(blueprint).each do |candidate|
        primary = candidate["aggregates"].first
        expect(primary["identity"]).to eq(blueprint["aggregates"].first["identity"])
        expect(primary["commands"].count { |command| command["creates"] }).to eq(1)
      end
    end

    it "drops a query whose only where needed an aggregate that was removed" do
      without_root = described_class.prune(described_class.remove_at(blueprint, ["aggregates", 2]))

      expect(without_root["aggregates"].size).to eq(2)
      expect(without_root["aggregates"].first["queries"].map { |query| query["name"] })
        .not_to include(a_string_starting_with("ThroughOpen"))
    end

    # Regression: removing Close left `Reopen from closed` with an unreachable from-state,
    # and pruning only checked that Reopen's command still existed.
    it "drops a transition whose from-state a removal left unreachable" do
      lifecycled = described_class.generate(seed: 0, forms: %w[lifecycle closed_set])
      close = lifecycled["aggregates"].first["commands"].index { |command| command["name"] == "Close" }
      pruned = described_class.prune(described_class.remove_at(lifecycled, ["aggregates", 0, "commands", close]))

      transitions = pruned["aggregates"].first.dig("lifecycle", "transitions") || []
      expect(transitions.map { |transition| transition["command"] }).not_to include("Reopen")
    end

    it "shrinks greedily to what a finding needs and no further" do
      needs_hop_query = lambda do |candidate|
        candidate["aggregates"].first["queries"].any? { |query| query["name"].start_with?("ThroughOpen") }
      end
      current = blueprint
      while (smaller = described_class.shrink_candidates(current).find(&needs_hop_query))
        current = smaller
      end

      expect(current["aggregates"].size).to eq(3)
      expect(current["policies"]).to be_empty
      expect(described_class.shrink_candidates(current).none?(&needs_hop_query)).to be(true)
      expect(described_class.removals(current).size).to be < described_class.removals(blueprint).size
    end
  end
end
