require "spec_helper"
require "hecks/fuzzing/sequence_generator"

RSpec.describe Hecks::Fuzzing::SequenceGenerator do
  def domain(name) = File.join(InMemoryDomain::ROOT, "examples/#{name}")

  describe "determinism" do
    it "produces the exact same script for the same seed" do
      first  = described_class.generate(domain("pizzas"), seed: 5, steps: 15)
      second = described_class.generate(domain("pizzas"), seed: 5, steps: 15)

      expect(first).to eq(second)
    end

    it "produces a different script for a different seed" do
      first  = described_class.generate(domain("pizzas"), seed: 1, steps: 15)
      second = described_class.generate(domain("pizzas"), seed: 2, steps: 15)

      expect(first).not_to eq(second)
    end
  end

  # **Coverage guidance** — `trace`, `prefix:` and `favor:` (CoverageCampaign's
  # two levers). The contract that matters most is the first: turning none
  # of it on changes no generated byte.
  describe "coverage guidance" do
    let(:lease_clock) { File.join(InMemoryDomain::ROOT, "qa/stress_domains/lease_clock") }

    it "traces exactly the steps generate produces, one coverage tuple per attempt" do
      trace = described_class.trace(lease_clock, seed: 7, steps: 20, adversarial: 0.3)

      expect(trace.steps).to eq(described_class.generate(lease_clock, seed: 7, steps: 20, adversarial: 0.3))
      expect(trace.coverage.map(&:first)).to eq((0...20).to_a)
      expect(trace.coverage.map(&:last)).to all(match(/\ALeaseClock::Lease\.\w+ \| (verb|query|dry_run) \| \S+ \| \S+ \| \w+\z/))
      expect(trace.verbs).to include("LeaseClock::Lease.Register", "LeaseClock::Lease.Expired")
    end

    it "reads the addressed record's lifecycle state into a tuple" do
      states = (1..6).flat_map do |seed|
        described_class.trace(lease_clock, seed: seed, steps: 30).coverage.map { |_, tuple| tuple.split(" | ")[2] }
      end

      expect(states).to include("absent", "free")
    end

    it "re-generates a prefix seed's first attempts exactly, then carries on with its own seed" do
      prefix  = { "seed" => 7, "steps" => 8, "favor" => [] }
      base    = described_class.trace(lease_clock, seed: 7, steps: 20, adversarial: 0.3)
      spliced = described_class.trace(lease_clock, seed: 99, steps: 20, adversarial: 0.3, prefix: prefix)

      expect(spliced.coverage.first(8)).to eq(base.coverage.first(8))
      expect(spliced.coverage.size).to eq(28)
      expect(spliced.steps).to eq(described_class.generate(lease_clock, seed: 99, steps: 20, adversarial: 0.3, prefix: prefix))
    end

    it "reproduces a nested prefix chain" do
      inner = { "seed" => 7, "steps" => 8, "favor" => [] }
      first = described_class.trace(lease_clock, seed: 99, steps: 20, prefix: inner, favor: ["LeaseClock::Lease.Reap"])
      outer = { "seed" => 99, "steps" => 12, "favor" => ["LeaseClock::Lease.Reap"], "prefix" => inner }
      deep  = described_class.trace(lease_clock, seed: 5, steps: 20, prefix: outer)

      expect(deep.coverage.first(12)).to eq(first.coverage.first(12))
    end

    it "weights a favored verb up without changing what is eligible" do
      picks = lambda do |favor|
        (1..4).sum do |seed|
          described_class.trace(lease_clock, seed: seed, steps: 30, favor: favor)
                         .coverage.count { |_, tuple| tuple.start_with?("LeaseClock::Lease.Expired |") }
        end
      end

      expect(picks.call(["LeaseClock::Lease.Expired"])).to be > picks.call([])
    end
  end

  describe "validity" do
    # The real self-test. Generation dispatches every candidate step against
    # a live, throwaway runtime as it builds the sequence (SequenceGenerator
    # #call) — `safe_call` only rescues Hecks::Runtime::DOMAIN_REFUSALS,
    # so anything else propagates and fails this example. That's exactly what
    # should happen if the generator ever produces a step shaped wrongly
    # enough to crash the interpreter for reasons that have nothing to do
    # with a genuine domain refusal.
    it "never crashes the interpreter for pizzas, across many seeds" do
      5.times do |seed|
        expect { described_class.generate(domain("pizzas"), seed: seed, steps: 40) }
          .not_to raise_error
      end
    end

    it "never crashes the interpreter for banking, across many seeds" do
      5.times do |seed|
        expect { described_class.generate(domain("banking"), seed: seed, steps: 40) }
          .not_to raise_error
      end
    end

    it "reaches an actual state, not just refusals — at least one instance-acting or entity step becomes eligible" do
      # Weighted eligibility means an instance-acting/entity command only
      # enters the pool once known_ids has an entry for its aggregate — this
      # confirms sequencing actually reaches that point rather than
      # generating 40 independent creates that never build on each other.
      steps = described_class.generate(domain("pizzas"), seed: 11, steps: 40)
      verbs = steps.filter_map { |step| step["verb"] }

      expect(verbs.any? { |verb| !verb.end_with?(".CreatePizza") }).to be(true)
    end

    it "produces steps in the exact shape spec/corpus/*.json already uses" do
      steps = described_class.generate(domain("pizzas"), seed: 9, steps: 10)

      steps.each do |step|
        expect(step.keys - %w[verb query args]).to be_empty
        expect(step).to have_key("args")
        expect(step.key?("verb") ? step["verb"] : step["query"]).to be_a(String)
      end
    end

    it "leaves the real example data untouched" do
      before = Dir.glob("#{domain('pizzas')}/data/**/*")
      described_class.generate(domain("pizzas"), seed: 1, steps: 20)
      after = Dir.glob("#{domain('pizzas')}/data/**/*")

      expect(after).to eq(before)
    end
  end
end
