# frozen_string_literal: true

require "json"
require_relative "../../projector"
require_relative "table"
require_relative "routes_ts/helpers"
require_relative "routes_ts/navigation"
require_relative "routes_ts/listings"

module Hecks
  module Projections
    module Site
      # A site's route table as one dependency-free TypeScript module, `routes.ts`.
      #
      # The module holds the table as `as const` data and the few pure helpers the site's
      # middleware, navigation, sitemap, robots file and content system need over it, so each reads
      # one file instead of carrying its own copy of which pages exist. Nothing in it depends on a
      # framework: it is an ES module that Node (type stripping) and any bundler load as it stands.
      #
      # The text is a pure function of the table: rows keep the order the client declared them in,
      # every list derived from them is sorted by an explicit key, and nothing in it names a time
      # or a machine, so regenerating from the same table changes nothing.
      module RoutesTs
        extend Projector::Target

        projects_as :site_routes_ts, emits: :files

        # The banner every generated file starts with.
        BANNER = "// Generated by hecks site site_projection.project_site. Do not edit."

        # The path of the row that stands for the edge's default behaviour. It matches every path,
        # so it hides none from search.
        CATCH_ALL = "/*"

        # The URL prefix under which a draft preview is served.
        PREVIEW_PREFIX = "/admin-preview"

        module_function

        # Renders `routes.ts` for a route table.
        #
        # @param bluebook [Bluebook::Chapter] the chapter that declares the route table
        # @param options [Hash{Symbol => Object}] `:registry` (Runtime::Registry) the project booted
        #   into, which holds the Site chapter; `:table` (Table) a table already read, instead
        # @return [Hash{String => String}] `"routes.ts"` to its text
        # @raise [Table::Invalid] when the table is refused
        def call(bluebook:, options: {})
          table = options[:table] || Table.read(bluebook, registry: options.fetch(:registry))
          { "routes.ts" => render(table) }
        end

        # @param table [Table] a checked table
        # @return [String] the module's text, ending in a newline
        def render(table)
          rows = table.rows
          [BANNER, header, routes(rows), types, switches(rows), redirects(rows), middleware(rows),
           Navigation.render(table), Listings.search(rows), Listings.sources(rows), helpers].join("\n\n") << "\n"
        end

        # @param rows [Array<Table::Row>] the table's rows
        # @return [Array<Table::Row>] the rows that exist: those not switched off
        def live(rows) = rows.reject(&:off)

        def header
          <<~TS.chomp
            // The route table of this site, projected from its bluebook's Route rows. Change the rows and run
            // `hecks site site_projection.project_site`; `hecks site site_projection.project_site --check` fails when this file is out of date.
          TS
        end

        def types
          <<~TS.chomp
            export type Route = (typeof ROUTES)[number];
          TS
        end

        def routes(rows)
          lines = rows.map { |row| "  #{literal(route_fields(row))}," }
          "export const ROUTES = [\n#{lines.join("\n")}\n] as const;"
        end

        def route_fields(row)
          fields = { **route_identity(row), **route_serving(row), **route_page(row) }
          fields[:seoTitle] = row.seo_title if row.seo_title
          fields
        end

        def route_identity(row)
          { path: row.path, kind: row.kind, render: row.render, auth: row.auth, methods: row.verbs }
        end

        def route_serving(row)
          { cache: row.cache, origin: row.origin, source: row.source, indexable: row.indexable }
        end

        def route_page(row)
          { switch: blank_to_nil(row.switch), off: row.off, preview: row.preview,
            label: blank_to_nil(row.label), seo: blank_to_nil(row.seo), redirectTo: row.redirect_to }
        end

        def switches(rows)
          switched = rows.reject { |row| row.switch.empty? }.group_by(&:switch)
          ids = switched.sort.to_h { |id, group| [id.to_sym, group.none?(&:off)] }
          "// A page's switch: false while the page is off. A page without a switch is always on.\n" \
            "export const SWITCHES: Readonly<Record<string, boolean>> = #{literal(ids)};"
        end

        def redirects(rows)
          pairs = rows.flat_map do |row|
            targeted = row.kind == "redirect" ? [[row.path, row.redirect_to]] : []
            targeted + row.aliases.map { |from| [from, row.path] }
          end
          items = pairs.sort.map { |from, to| "  #{literal({ from: from, to: to, status: 301 })}," }
          "export const REDIRECTS = [\n#{items.join("\n")}\n] as const;".sub("[\n\n]", "[]")
        end

        def middleware(rows)
          off = rows.select(&:off).flat_map { |row| [row.path, *row.aliases] }.sort
          <<~TS.chomp
            // The three rules the site's middleware applies, as data: a switched-off page answers 404, a
            // request under the preview prefix is served from draft content, and `.html` is dropped.
            export const MIDDLEWARE = {
              off: { status: 404, paths: #{literal(off)} },
              preview: { prefix: #{literal(PREVIEW_PREFIX)} },
              stripHtml: { suffix: ".html" },
            } as const;
          TS
        end

        def helpers = Helpers.text

        def blank_to_nil(text) = text.nil? || text.empty? ? nil : text

        # @param value [Object] a string, number, boolean, nil, array or hash
        # @return [String] the TypeScript literal for it: objects with bare keys, on one line
        def literal(value)
          case value
          when Array then "[#{value.map { |item| literal(item) }.join(", ")}]"
          when Hash then "{ #{value.map { |key, item| "#{key_literal(key)}: #{literal(item)}" }.join(", ")} }".sub("{  }", "{}")
          else scalar_literal(value)
          end
        end

        def scalar_literal(value)
          case value
          when nil then "null"
          when true, false, Integer then value.to_s
          when String then JSON.generate(value)
          else raise ArgumentError, "no TypeScript literal for #{value.inspect}"
          end
        end

        def key_literal(key)
          key.to_s.match?(/\A[A-Za-z_$][\w$]*\z/) ? key.to_s : JSON.generate(key.to_s)
        end
      end
    end
  end
end
