# frozen_string_literal: true

require_relative "../../projector"
require_relative "root_rows"

module Hecks
  module Projections
    module Site
      # The files at a project's root that are written from rows beside its route table: the
      # local-stack settings template (`.env.tpl`, from `Secrets` and `Env` rows) and the workflow
      # that
      # keeps the generated files current (`.github/workflows/site-routes.yml`, from a `Ci` row).
      #
      # Each file is written only when its rows are declared. Settings that are secrets are
      # references
      # into 1Password, never values, so nothing secret is written to disk.
      module SiteRoot
        extend Projector::Target

        projects_as :site_root, emits: :files

        # The `Secrets` row: where the secrets live and what starts the stack.
        SECRETS = RootRows.new("Secrets", fields: { vault: String, item: String, section: String, launcher: String },
                                          required: %i[vault item section], defaults: { launcher: "bin/dev" })

        # An `Env` row: a plain setting when it carries `value`, a secret reference when it does
        # not.
        ENV_ROWS = RootRows.new("Env", fields: { name: String, value: String }, required: %i[name], many: true)

        # The `Ci` row: the workflow that checks the generated files.
        CI = RootRows.new("Ci", fields:   { name: String, ruby: String, node: String, gem_dir: String, script: String,
                                          test: String, paths: String },
                                required: %i[gem_dir],
                                defaults: { name: "Site routes", ruby: "3.3", node: "22", script: "bin/site_routes",
                                            test: "npm test", paths: "" })

        # The workflow's path and the steps' action pins, which a project does not choose.
        WORKFLOW = ".github/workflows/site-routes.yml"
        BANNER = "# Generated by hecks site site_projection.project_site. Do not edit."

        module_function

        # @param bluebook [Bluebook::Chapter] the chapter that declares the route table
        # @param options [Hash{Symbol => Object}] unused
        # @return [Hash{String => String}] each file's path relative to the project root to its
        #   text;
        #   empty when the project declares no such rows
        # @raise [Table::Invalid] when a row is refused
        def call(bluebook:, options: {})
          files = {}
          env = env_template(bluebook)
          files[".env.tpl"] = env if env
          ci = CI.read(bluebook).first
          files[WORKFLOW] = workflow(ci) if ci
          files
        end

        # @return [String, nil] the template, or nil with no `Env` rows
        def env_template(chapter)
          vars = ENV_ROWS.read(chapter)
          return nil if vars.empty?

          secrets = SECRETS.read(chapter).first
          if secrets.nil? && vars.any? { |var| !var.key?(:value) }
            raise Table::Invalid, "Env rows without a value are secrets; the project declares no Secrets row"
          end

          [BANNER, *header(secrets), *vars.map { |var| line(var, secrets) }].join("\n") << "\n"
        end

        def header(secrets)
          return [] unless secrets

          ["# Local-stack settings. Secrets are op:// references into the 1Password",
           "# \"#{secrets[:vault]}\" vault, item \"#{secrets[:item]}\", section \"#{secrets[:section]}\",",
           "# resolved at start-up by",
           "# `op run --env-file=.env.tpl -- <command>` (#{secrets[:launcher]} does this); no secret is",
           "# ever written to disk. The plain lines below are not secret."]
        end

        def line(var, secrets)
          return "#{var[:name]}=#{var[:value]}" if var.key?(:value)

          "#{var[:name]}=op://#{secrets[:vault]}/#{secrets[:item]}/#{secrets[:section]}/#{var[:name]}"
        end

        # @param row [Hash{Symbol => Object}] the checked `Ci` row
        # @return [String] the workflow
        def workflow(row)
          paths = path_list(row).map { |path| "      - #{path.to_s.inspect}" }.join("\n")
          format(WORKFLOW_TEXT, banner: BANNER, name: row[:name], paths: paths, ruby: row[:ruby].inspect,
                                node: row[:node].inspect, gem_dir: row[:gem_dir], script: row[:script], test: row[:test])
        end

        def path_list(row)
          listed = row[:paths].split(",").map(&:strip).reject(&:empty?)
          [*listed, row[:script], "#{row[:gem_dir]}/Gemfile.lock", WORKFLOW].uniq
        end

        WORKFLOW_TEXT = <<~YAML
          %<banner>s
          # Two checks, neither needing AWS or a database:
          #
          #   1. the generated files are current: `%<script>s --check` regenerates them with the
          # hecks gem
          #      the Gemfile.lock pins and exits 1, naming each file, if a row was edited without
          #      regenerating or a generated file was hand-edited;
          #   2. `%<test>s`, which holds the generated code to what the hand-written code does.
          name: %<name>s

          on:
            push:
              branches: [main]
              paths:
          %<paths>s
            pull_request:
              paths:
          %<paths>s
            # Lets a GitHub merge queue run this check on each queued PR (paths are not applied to
            # merge_group).
            merge_group:
            workflow_dispatch: {}

          permissions:
            contents: read

          jobs:
            routes-current-and-parity:
              runs-on: ubuntu-24.04
              timeout-minutes: 15

              steps:
                - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

                - uses: ruby/setup-ruby@14594264cd68ce8a2345dd349bc3d138a4ef85c8 # v1
                  with:
                    ruby-version: %<ruby>s
                    bundler-cache: true
                    working-directory: %<gem_dir>s

                - name: The generated files are current
                  run: %<script>s --check

                - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
                  with:
                    node-version: %<node>s

                - name: npm ci
                  run: npm ci

                - name: Parity between the generated code and the hand-written code
                  run: %<test>s
        YAML
      end
    end
  end
end
