# frozen_string_literal: true

require_relative "../../projector"
require_relative "root_rows"
require_relative "site_root/workflow"

module Hecks
  module Projections
    module Site
      # The files at a project's root that are written from rows beside its route table: the
      # local-stack settings template (`.env.tpl`, from `Secrets` and `Env` rows) and the workflow
      # that
      # keeps the generated files current (`.github/workflows/site-routes.yml`, from a `Ci` row).
      #
      # Each file is written only when its rows are declared. Settings that are secrets are
      # references
      # into 1Password, never values, so nothing secret is written to disk.
      module SiteRoot
        extend Projector::Target

        projects_as :site_root, emits: :files

        # The `Secrets` row: where the secrets live and what starts the stack.
        SECRETS = RootRows.new("Secrets", fields:   { vault: String, item: String, section: String, launcher: String },
                                          required: %i[vault item])

        # An `Env` row: a plain setting when it carries `value`, a secret reference when it does
        # not. `group` heads the rows from it on with a comment; `off` comments the line out.
        ENV_ROWS = RootRows.new("Env", required: %i[name], many: true,
                                       fields: { name: String, value: [String, Integer, TrueClass, FalseClass], group: String,
                                                off: [TrueClass, FalseClass] })

        # The `Ci` row: the workflow that checks the generated files.
        CI = RootRows.new("Ci", fields:   { name: String, ruby: String, node: String, gem_dir: String, script: String,
                                          test: String, paths: String, install: String },
                                required: %i[gem_dir],
                                defaults: { name: "Site routes", ruby: "3.3", node: "22", script: "bin/site_routes",
                                            test: "npm test", paths: "", install: "npm ci" })

        # The workflow's path and the steps' action pins, which a project does not choose.
        WORKFLOW = ".github/workflows/site-routes.yml"
        BANNER = "# Generated by hecks site site_projection.project_site. Do not edit."

        module_function

        # @param bluebook [Bluebook::Chapter] the chapter that declares the route table
        # @param options [Hash{Symbol => Object}] unused
        # @return [Hash{String => String}] each file's path relative to the project root to its
        #   text;
        #   empty when the project declares no such rows
        # @raise [Table::Invalid] when a row is refused
        def call(bluebook:, options: {})
          files = {}
          env = env_template(bluebook)
          files[".env.tpl"] = env if env
          ci = CI.read(bluebook).first
          files[WORKFLOW] = workflow(ci) if ci
          files
        end

        # @return [String, nil] the template, or nil with no `Env` rows
        def env_template(chapter)
          vars = ENV_ROWS.read(chapter)
          return nil if vars.empty?

          secrets = SECRETS.read(chapter).first
          if secrets.nil? && vars.any? { |var| !var.key?(:value) }
            raise Table::Invalid, "Env rows without a value are secrets; the project declares no Secrets row"
          end

          [BANNER, *header(secrets), *body(vars, secrets)].join("\n") << "\n"
        end

        def header(secrets)
          return [] unless secrets

          where = ["vault \"#{secrets[:vault]}\"", "item \"#{secrets[:item]}\"",
                   *(secrets[:section] ? ["section \"#{secrets[:section]}\""] : [])].join(", ")
          starter = secrets[:launcher] ? " (#{secrets[:launcher]} does this)" : ""
          ["# Local-stack settings. Secrets are op:// references into 1Password (#{where}),",
           "# resolved at start-up by `op run --env-file=.env.tpl -- <command>`#{starter};",
           "# no secret is ever written to disk. The plain lines are not secret."]
        end

        def body(vars, secrets)
          group = nil
          vars.flat_map do |var|
            heading = var[:group] && var[:group] != group ? ["", "# #{var[:group]}"] : []
            group = var[:group] if var[:group]
            [*heading, line(var, secrets)]
          end
        end

        def line(var, secrets)
          text = "#{var[:name]}=#{var.key?(:value) ? var[:value] : reference(var, secrets)}"
          var[:off] ? "# #{text}" : text
        end

        def reference(var, secrets)
          "op://#{[secrets[:vault], secrets[:item], secrets[:section], var[:name]].compact.join("/")}"
        end

        # @param row [Hash{Symbol => Object}] the checked `Ci` row
        # @return [String] the workflow
        def workflow(row)
          paths = path_list(row).map { |path| "      - #{path.to_s.inspect}" }.join("\n")
          format(Workflow::TEXT, banner: BANNER, name: row[:name], paths: paths, ruby: row[:ruby].inspect,
                                node: row[:node].inspect, gem_dir: row[:gem_dir], script: row[:script], test: row[:test],
                                install_steps: install_steps(row[:install]))
        end

        # The steps that install the project's dependencies; a project that installs with yarn gets
        # corepack enabled first, so the version it pins is the one that runs.
        def install_steps(install)
          steps = []
          steps << "- name: Enable corepack\n        run: corepack enable" if install.start_with?("yarn")
          steps << "- name: Install dependencies\n        run: #{install}"
          steps.join("\n\n      ")
        end

        def path_list(row)
          listed = row[:paths].split(",").map(&:strip).reject(&:empty?)
          [*listed, row[:script], "#{row[:gem_dir]}/Gemfile.lock", WORKFLOW].uniq
        end
      end
    end
  end
end
