require_relative "block_rendering"

module Hecks
  module Fuzzing
    module DomainGenerator
      # Renders a blueprint to bluebook source text.
      module Rendering
        include BlockRendering

        def render(blueprint)
          out = render_header(blueprint)
          blueprint["aggregates"].each { |aggregate| out.concat(render_aggregate(aggregate)) }
          blueprint["policies"].each { |policy| out.concat(render_policy(policy)) }
          out << "end"
          "#{out.join("\n")}\n"
        end

        def render_header(blueprint)
          ["# GENERATED by Hecks::Fuzzing::DomainGenerator — seed #{blueprint["seed"]}, forms " \
           "#{blueprint["forms"].join(", ")}. Not hand-written; see hecks quality_control check_generated_domains.",
           "Hecks.bluebook #{DOMAIN_NAME.inspect} do",
           "  vision #{"A generated domain that puts #{blueprint["forms"].join(" and ")} together.".inspect}",
           "",
           "  core"]
        end

        def render_aggregate(aggregate)
          [*aggregate_header(aggregate), *aggregate_fields(aggregate), *aggregate_rules(aggregate),
           *aggregate_behaviors(aggregate), "  end"]
        end

        def aggregate_header(aggregate)
          ["", "  aggregate #{aggregate["name"].inspect} do",
           "    description #{"A generated #{aggregate["name"].downcase}.".inspect}", "",
           identity_line(aggregate["identity"], "    ")]
        end

        # An aggregate's attributes, references and value objects.
        def aggregate_fields(aggregate)
          aggregate["attributes"].map { |attribute| "    #{render_attribute(attribute)}" } +
            aggregate["references"].map { |target| "    reference_to #{target}" } +
            aggregate["vos"].flat_map { |name, vo| render_value_object(name, vo, "    ") }
        end

        # An aggregate's lifecycle and invariants.
        def aggregate_rules(aggregate)
          lifecycle = aggregate["lifecycle"] ? render_lifecycle(aggregate["lifecycle"], "    ") : []
          lifecycle + aggregate["invariants"].map { |inv| "    invariant(#{inv["label"].inspect}) { #{inv["expr"]} }" }
        end

        # An aggregate's entities, commands and queries.
        def aggregate_behaviors(aggregate)
          aggregate["entities"].flat_map { |entity| render_entity(entity) } +
            aggregate["commands"].flat_map { |command| render_command(command, aggregate["name"], "    ") } +
            aggregate["queries"].flat_map { |query| render_query(query) }
        end

        def identity_line(identity, indent) = "#{indent}identified_by #{identity.map { |part| ":#{part}" }.join(", ")}"

        def render_entity(entity)
          lifecycle = entity["lifecycle"] ? render_lifecycle(entity["lifecycle"], "      ") : []
          ["", "    entity #{entity["name"].inspect} do",
           "      description #{"A generated #{entity["name"].downcase}.".inspect}",
           identity_line(entity["identity"], "      "),
           *entity["attributes"].map { |attribute| "      #{render_attribute(attribute)}" },
           *lifecycle,
           *entity["commands"].flat_map { |command| render_command(command, nil, "      ") },
           "    end"]
        end

        def render_attribute(attribute)
          type = attribute["list"] ? "list_of(#{attribute["type"]})" : attribute["type"]
          line = "attribute :#{attribute["name"]}, #{type}"
          line += ", optional: true" if attribute["optional"]
          line += ", default: { value: #{attribute["default"].inspect} }" if attribute.key?("default")
          line
        end

        def render_query(query)
          out = ["", "    query #{query["name"].inspect} do", "      description #{"Generated #{query["name"]}.".inspect}"]
          query["wheres"].each do |where|
            out << "      where(:#{where["field"].inspect} => #{where["value"].inspect})"
          end
          out << "      order_by :#{query["order_by"]}"
          out << "    end"
        end

        def render_policy(policy)
          ["", "  policy #{policy["name"].inspect} do", "    on #{policy["on"]}", "    trigger #{policy["trigger"]}", "  end"]
        end
      end
    end
  end
end
