// Generated by hecks site site_projection.project_site. Do not edit.

// What a picture's bytes are. The type an upload claims is never trusted: the first bytes decide,
// against an allow-list of raster formats (JPEG, PNG, WebP, GIF, AVIF). SVG, which can carry script,
// and anything else is refused. The same bytes give the picture's size when the format makes it cheap
// to read, and the storage key is the bytes' own digest with the format's extension, so a key is never
// built from anything the client sent.

/** The extension each allowed type is stored under. */
export const EXTENSION_OF: Readonly<Record<string, string>> = {
  "image/jpeg": "jpg",
  "image/png": "png",
  "image/webp": "webp",
  "image/gif": "gif",
  "image/avif": "avif",
};

/** The type a stored key's extension says it is. */
export const TYPE_OF: Readonly<Record<string, string>> = Object.fromEntries(Object.entries(EXTENSION_OF).map(([type, ext]) => [ext, type]));

/** A key the editor generated: a SHA-256 digest in hex, a dot, and an allowed extension. */
export const KEY_PATTERN = /^[0-9a-f]{64}\.(jpg|png|webp|gif|avif)$/;

const ascii = (bytes: Uint8Array, from: number, to: number): string => String.fromCharCode(...bytes.subarray(from, to));
const be16 = (b: Uint8Array, at: number): number => (b[at] << 8) | b[at + 1];
const be32 = (b: Uint8Array, at: number): number => ((b[at] << 24) | (b[at + 1] << 16) | (b[at + 2] << 8) | b[at + 3]) >>> 0;
const le16 = (b: Uint8Array, at: number): number => b[at] | (b[at + 1] << 8);
const le24 = (b: Uint8Array, at: number): number => b[at] | (b[at + 1] << 8) | (b[at + 2] << 16);

const PNG = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];

/** AVIF is an ISO file whose first box names an avif brand, as its major brand or a compatible one. */
function isAvif(bytes: Uint8Array): boolean {
  if (bytes.length < 16 || ascii(bytes, 4, 8) !== "ftyp") return false;
  const end = Math.min(be32(bytes, 0), 64, bytes.length);
  for (let at = 8; at + 4 <= end; at += 4) {
    const brand = ascii(bytes, at, at + 4);
    if (brand === "avif" || brand === "avis") return true;
  }
  return false;
}

/** The allowed type the bytes are, or null when they are none of them. */
export function sniff(bytes: Uint8Array): string | null {
  if (bytes.length >= 3 && bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff) return "image/jpeg";
  if (bytes.length >= 8 && PNG.every((value, at) => bytes[at] === value)) return "image/png";
  if (bytes.length >= 6 && ["GIF87a", "GIF89a"].includes(ascii(bytes, 0, 6))) return "image/gif";
  if (bytes.length >= 12 && ascii(bytes, 0, 4) === "RIFF" && ascii(bytes, 8, 12) === "WEBP") return "image/webp";
  return isAvif(bytes) ? "image/avif" : null;
}

export interface Size {
  width: number;
  height: number;
}

function jpegSize(bytes: Uint8Array): Size | null {
  let at = 2;
  while (at + 9 < bytes.length) {
    if (bytes[at] !== 0xff) return null;
    const marker = bytes[at + 1];
    if (marker === 0xff) {
      at += 1;
    } else if (marker >= 0xc0 && marker <= 0xcf && ![0xc4, 0xc8, 0xcc].includes(marker)) {
      return { height: be16(bytes, at + 5), width: be16(bytes, at + 7) };
    } else if (marker === 0xd8 || marker === 0x01 || (marker >= 0xd0 && marker <= 0xd7)) {
      at += 2;
    } else {
      at += 2 + be16(bytes, at + 2);
    }
  }
  return null;
}

function webpSize(bytes: Uint8Array): Size | null {
  const chunk = ascii(bytes, 12, 16);
  if (chunk === "VP8X" && bytes.length >= 30) return { width: le24(bytes, 24) + 1, height: le24(bytes, 27) + 1 };
  if (chunk === "VP8 " && bytes.length >= 30) return { width: le16(bytes, 26) & 0x3fff, height: le16(bytes, 28) & 0x3fff };
  if (chunk === "VP8L" && bytes.length >= 25) {
    const bits = (bytes[21] | (bytes[22] << 8) | (bytes[23] << 16) | (bytes[24] << 24)) >>> 0;
    return { width: (bits & 0x3fff) + 1, height: ((bits >>> 14) & 0x3fff) + 1 };
  }
  return null;
}

/** The picture's size in pixels when the format makes it cheap to read (not AVIF), else null. */
export function sizeOf(bytes: Uint8Array, type: string): Size | null {
  let size: Size | null = null;
  if (type === "image/png" && bytes.length >= 24) size = { width: be32(bytes, 16), height: be32(bytes, 20) };
  else if (type === "image/gif" && bytes.length >= 10) size = { width: le16(bytes, 6), height: le16(bytes, 8) };
  else if (type === "image/jpeg") size = jpegSize(bytes);
  else if (type === "image/webp") size = webpSize(bytes);
  return size && size.width > 0 && size.height > 0 ? size : null;
}
