# frozen_string_literal: true

require_relative "../../tools"
require_relative "masking"
require_relative "caps_words"
require_relative "text_checks"
require_relative "fixing"
require_relative "structure"

module Hecks
  module Tools
    module RustCommentStyle
      # One parsed `.rs` file and the violations found in it.
      class SourceFile
        include Masking
        include CapsWords
        include TextChecks
        include Fixing
        include Structure

        attr_reader :path, :lines, :comments

        def initialize(path, source = nil)
          @path = path
          @source = source || File.read(path)
          @lines = @source.lines
          @comments = generated? ? [] : Tokenizer.comments(@source)
          @by_line = @comments.to_h { |c| [c.line, c] }
          @open_spans = open_spans
          @constants = code_constants
        end

        # Finds every place this file departs from the style guide.
        def violations(only: nil)
          return [] if generated?

          found = text_violations + structure_violations
          found = found.select { |v| only.include?(v.category) } if only
          found.sort_by { |v| [v.line, v.category] }
        end

        # Rewrites the mechanical categories.
        def fixed(only: nil)
          return @source if generated?

          wanted = (only || FIXABLE) & FIXABLE
          @lines.map.with_index(1) { |line, number| fix_line(line, number, wanted) }.join
        end

        # A generated file's comments belong to its generator: `hecks project_rust`
        # and friends stamp this exact banner on line one.
        def generated?
          @lines.first.to_s.start_with?("// GENERATED by")
        end

        private

        # SCREAMING_SNAKE names this file defines: `const`/`static` items, plus
        # enum variants and macro-visible names that read the same way.
        def code_constants
          code_only = @source.dup
          Tokenizer.comments(@source).each { |c| code_only[c.line - 1] ||= "" }
          names = Set.new
          code_only.scan(/\b(?:const|static)\s+(?:mut\s+)?([A-Z][A-Z0-9_]*)\b/) { |(n)| names << n }
          code_only.scan(/"([A-Z][A-Z0-9_]{2,})"/) { |(n)| names << n }
          names
        end
      end
    end
  end
end
