# RUBY'S OWN "PRELUDE" WRITER — for `spec/codegen_parity_spec.rb` only.
#
# `rust/project/domain_generator.rb#call` writes one `.rs` file per
# aggregate that INTERLEAVES the "prelude" (value objects, entities, the
# record — this file's own target) with commands/ports (NOT ported to
# Rust this stage — see the stage report). This module replicates
# `domain_generator.rb`'s own `f.puts` CALL SEQUENCE for exactly the
# prelude portion — stopping right before `aggregate[:commands].each` —
# using the REAL, unmodified `RustProjection::Projector` functions
# `bin/project_rust` itself calls. It reimplements no codegen algorithm;
# it only reproduces the ORCHESTRATION (which function, in which order,
# with which blank-line puts calls) so `rust/codegen`'s own Rust "prelude"
# assembly (rust/codegen/src/prelude.rs) has a real, byte-comparable
# target built from the SAME real Ruby functions bin/project_rust uses,
# not a reimplementation of them.
#
# `f.puts` semantics matter for the exact byte output: Ruby's `puts`
# appends a trailing "\n" only if the string doesn't already end in one.
module RubyCodegenPrelude
  module_function

  def puts_str(out, text)
    out << text
    out << "\n" unless text.end_with?("\n")
  end

  def puts_blank(out)
    out << "\n"
  end

  def lifecycle_extra_field(node)
    return [] unless node[:lifecycle]

    field = RustProjection::Projector.rust_ident_field(node[:lifecycle][:field])
    [[RustProjection::Projector.rust_field(node[:lifecycle][:field]), "crate::kernel::Json::Str(self.#{field}.clone())"]]
  end

  # `nil` when `domain_generator.rb` would skip this aggregate entirely
  # (unsupported attribute type(s) — no `.rs` file at all), matching that
  # absence rather than emitting a partial prelude.
  # This method's own job (see the file header) IS the exact call
  # sequence below — it exists to be byte-comparable against Rust's own
  # prelude assembly. Extracting pieces would risk silently reordering
  # or dropping one of the `puts_str`/`puts_blank` calls the parity test
  # depends on, with no single resulting method looking wrong.
  # rubocop:disable-next Metrics/AbcSize, Metrics/MethodLength
  def aggregate_prelude(aggregate, source_label)
    value_objects_by_name = aggregate[:value_objects].to_h { |vo| [vo[:name], vo] }
    return nil if RustProjection::Projector.unsupported_attribute_types(aggregate, value_objects_by_name).any?

    # THE SAME MUTATING PASS `domain_generator.rb#call` runs on every real
    # aggregate before generating anything — real Ruby, real mutation, so
    # this Ruby-side comparator sees exactly what bin/project_rust would.
    RustProjection::Projector.mark_append_optional_fields!(aggregate, value_objects_by_name)

    out = +""
    puts_str(out, "// GENERATED by bin/project_rust from #{source_label}'s canonical IR.")
    puts_str(out, "// Do not hand-edit — re-run bin/project_rust instead.")
    puts_str(out, "#![allow(dead_code, unused_variables)]")
    puts_str(out, "use crate::kernel::Expr;")
    puts_blank(out)

    aggregate[:value_objects].each do |vo|
      puts_str(out,
               RustProjection::Projector.emit_value_object(vo, value_objects_by_name, AGGREGATES_BY_NAME.fetch(source_label)))
      puts_blank(out)

      if vo[:closed_set] && vo[:attributes].size == 1
        puts_str(out, RustProjection::Projector.emit_closed_set_codec(vo))
      elsif vo[:closed_set]
        puts_str(out, RustProjection::Projector.emit_closed_set_table_codec(vo))
      else
        name = RustProjection::Projector.rust_ident(vo[:name])
        puts_str(out, RustProjection::Projector.emit_to_json_flat(name, vo[:attributes], value_objects_by_name))
        puts_blank(out)
        puts_str(out, RustProjection::Projector.emit_from_json_flat(name, vo[:attributes], value_objects_by_name))
      end
      puts_blank(out)
    end

    aggregate[:entities].each do |entity|
      puts_str(out, RustProjection::Projector.emit_entity(entity, value_objects_by_name))
      puts_blank(out)
      entity_name = RustProjection::Projector.rust_ident(entity[:name])
      puts_str(out,
               RustProjection::Projector.emit_to_json_flat(entity_name, entity[:attributes], value_objects_by_name,
                                                           extra_fields: lifecycle_extra_field(entity)))
      puts_blank(out)
      puts_str(out,
               RustProjection::Projector.emit_from_json_state(entity_name, entity[:attributes], value_objects_by_name,
                                                              extra_fields: lifecycle_extra_field(entity)))
      puts_blank(out)

      if RustProjection::Projector.extract_id_supported?(entity)
        puts_str(out, RustProjection::Projector.emit_extract_id(entity))
        puts_blank(out)
        puts_str(out, RustProjection::Projector.emit_extract_wants(entity))
        puts_blank(out)
        puts_str(out, RustProjection::Projector.emit_self_identity(entity))
        puts_blank(out)
      end
    end

    puts_str(out, RustProjection::Projector.emit_record(aggregate, value_objects_by_name))
    puts_blank(out)
    record_name = RustProjection::Projector.rust_ident(aggregate[:name])
    puts_str(out,
             RustProjection::Projector.emit_to_json_flat(record_name, aggregate[:attributes], value_objects_by_name,
                                                         optional: true, extra_fields: lifecycle_extra_field(aggregate),
                                                         aggregate: aggregate))
    puts_blank(out)
    puts_str(out,
             RustProjection::Projector.emit_from_json_state(record_name, aggregate[:attributes], value_objects_by_name,
                                                            optional: true, extra_fields: lifecycle_extra_field(aggregate),
                                                            aggregate: aggregate))
    puts_blank(out)
    puts_str(out, <<~RUST)
      impl crate::kernel::ToJson for #{record_name} {
          fn to_json(&self) -> crate::kernel::Json {
              #{record_name}::to_json(self)
          }
      }
    RUST
    puts_blank(out)

    if RustProjection::Projector.extract_id_supported?(aggregate)
      puts_str(out, RustProjection::Projector.emit_extract_id(aggregate))
      puts_blank(out)
    end

    out
  end

  # `aggregates_by_name` needs the FULL domain's aggregate list (an
  # `admits:` on one aggregate's value object can name a closed set
  # declared on ANOTHER aggregate in the same chapter) — threaded through
  # a small keyed cache rather than a third positional argument, so
  # `aggregate_prelude`'s own call signature stays a direct match for
  # `rust/codegen`'s own `prelude::aggregate_prelude(exemplar, ir,
  # aggregate, source_label)`.
  # NOT frozen — a real accumulator, keyed by source_label and mutated
  # by #write_all below ([]=) and its own #ensure (.delete). False
  # positive for Style/MutableConstant.
  # rubocop:disable-next Style/MutableConstant
  AGGREGATES_BY_NAME = {}

  def write_all(payload, source_label, out_dir)
    AGGREGATES_BY_NAME[source_label] = payload[:aggregates].to_h { |a| [a[:name], a] }
    FileUtils.mkdir_p(out_dir)
    payload[:aggregates].each do |aggregate|
      text = aggregate_prelude(aggregate, source_label)
      next if text.nil?

      path = File.join(out_dir, "#{aggregate[:name].downcase}.rs")
      File.write(path, text)
    end
  ensure
    AGGREGATES_BY_NAME.delete(source_label)
  end
end
