require "tmpdir"
require "open3"
require "fileutils"

# bin/standardize_comments is a script whose `main` only runs when it is the program,
# so loading it here defines `CommentStyle` without running anything.
#
# These specs cover two rules. `design_history` flags phrasing that narrates change. `long_block`
# fails a block over `MAX_BLOCK` comment lines unless the checked-in baseline holds it at that
# length or longer.
load File.join(InMemoryDomain::ROOT, "bin/standardize_comments") unless defined?(CommentStyle)

RSpec.describe "bin/standardize_comments" do
  describe "design_history" do
    def history_found(comment)
      source = "# #{comment}\nclass Example\nend\n"
      CommentStyle::SourceFile.new("lib/hecks/example.rb", source).violations(only: ["design_history"])
    end

    ["This is no longer built here.", "There is no cache any more.", "It is not stored anymore."].each do |comment|
      it "flags #{comment.inspect}" do
        expect(history_found(comment).map(&:category)).to eq(["design_history"])
      end
    end

    it "leaves the same words alone inside a code span" do
      expect(history_found("Pass `no longer` to skip the check.")).to be_empty
    end

    it "leaves a present-tense statement alone" do
      expect(history_found("A file that does not exist is skipped.")).to be_empty
    end
  end

  describe "long_block" do
    let(:limit) { CommentStyle::MAX_BLOCK }
    let(:path)  { "lib/hecks/example.rb" }

    # A class opened by a comment block of `lines` lines, the first reading `opening`.
    def source_with_block(lines, opening: "Explains the example at length.")
      body = Array.new(lines - 1) { |index| "# line #{index + 2}" }
      ["# #{opening}", *body, "class Example", "end", ""].join("\n")
    end

    def long_block_violations(source, baseline: {})
      CommentStyle::SourceFile.new(path, source).violations(only: ["long_block"], baseline: baseline)
    end

    it "names the provisional threshold as a constant" do
      expect(limit).to eq(50)
    end

    it "passes a block exactly at the threshold" do
      expect(long_block_violations(source_with_block(limit))).to be_empty
    end

    it "fails a new block one line over the threshold" do
      found = long_block_violations(source_with_block(limit + 1))

      expect(found.map(&:category)).to eq(["long_block"])
      expect(found.first.line).to eq(1)
      expect(found.first.message).to include("#{limit + 1} lines", "over #{limit}")
    end

    it "passes a block the baseline holds at its current length" do
      baseline = { path => { "Explains the example at length." => limit + 5 } }

      expect(long_block_violations(source_with_block(limit + 5), baseline: baseline)).to be_empty
    end

    it "passes a block that has been trimmed below its baselined length" do
      baseline = { path => { "Explains the example at length." => limit + 20 } }

      expect(long_block_violations(source_with_block(limit + 5), baseline: baseline)).to be_empty
    end

    it "fails a baselined block that has grown" do
      baseline = { path => { "Explains the example at length." => limit + 5 } }
      found = long_block_violations(source_with_block(limit + 6), baseline: baseline)

      expect(found.map(&:category)).to eq(["long_block"])
      expect(found.first.message).to include("#{limit + 6} lines", "baselined at #{limit + 5}")
    end

    it "does not tolerate a block whose entry belongs to another file" do
      baseline = { "lib/hecks/other.rb" => { "Explains the example at length." => limit + 5 } }

      expect(long_block_violations(source_with_block(limit + 5), baseline: baseline).size).to eq(1)
    end

    it "keeps a block's key when lines are added above it" do
      baseline = { path => { "Explains the example at length." => limit + 5 } }
      shifted = "# frozen_string_literal: true\n\nmodule Hecks\nend\n\n#{source_with_block(limit + 5)}"

      expect(long_block_violations(shifted, baseline: baseline)).to be_empty
    end

    it "ends a block at a blank source line" do
      more = Array.new(limit) { "# more" }
      split = ["# first half", *more, "", "# second half", *more, "class Example", "end", ""]
      lengths = CommentStyle::SourceFile.new(path, split.join("\n")).long_blocks.map(&:lines)

      expect(lengths).to eq([limit + 1, limit + 1])
    end

    it "numbers blocks that open with the same text" do
      first = source_with_block(limit + 1).sub("class Example\nend\n", "")
      twice = [first, source_with_block(limit + 1)].join("\n")
      keys = CommentStyle::SourceFile.new(path, twice).long_blocks.map(&:key)

      expect(keys).to eq(["Explains the example at length.", "Explains the example at length. #2"])
    end

    it "ignores a generated file, whose comments belong to its generator" do
      generated = "# GENERATED by a tool, DO NOT EDIT\n#{source_with_block(limit + 10)}"

      expect(long_block_violations(generated)).to be_empty
    end

    it "does not count a trailing comment as part of a block" do
      lines = (1..limit).map { |index| "# line #{index}" }
      source = "#{lines.join("\n")}\nvalue = 1 # trailing\n# after the code\nclass Example\nend\n"

      expect(long_block_violations(source)).to be_empty
    end

    describe "the baseline file" do
      around do |example|
        @dir = Dir.mktmpdir("standardize-comments-spec-")
        example.run
      ensure
        FileUtils.remove_entry(@dir) if @dir
      end

      it "round-trips in a stable, sorted order" do
        file = File.join(@dir, "baseline.json")
        held = { "lib/b.rb" => { "z" => 60, "a" => 55 }, "lib/a.rb" => { "m" => 70 } }

        CommentStyle::Baseline.dump(held, file)

        expect(CommentStyle::Baseline.load(file)).to eq(held)
        expect(JSON.parse(File.read(file)).keys).to eq(["lib/a.rb", "lib/b.rb"])
        expect(JSON.parse(File.read(file))["lib/b.rb"].keys).to eq(%w[a z])
      end

      it "loads as empty when there is no file" do
        expect(CommentStyle::Baseline.load(File.join(@dir, "missing.json"))).to eq({})
      end

      it "is recorded from a run and then tolerates exactly what it recorded" do
        file = File.join(@dir, "example.rb")
        File.write(file, source_with_block(limit + 3))

        held = CommentStyle::Run.new([file], baseline: {}).long_block_baseline
        expect(held).to eq(file => { "Explains the example at length." => limit + 3 })

        tolerated = CommentStyle::Run.new([file], only: ["long_block"], baseline: held)
        expect(tolerated.violations).to be_empty

        File.write(file, source_with_block(limit + 4))
        grown = CommentStyle::Run.new([file], only: ["long_block"], baseline: held)
        expect(grown.violations.map(&:category)).to eq(["long_block"])
      end

      it "makes --check exit non-zero for a new long block and zero for a short one" do
        script = File.join(InMemoryDomain::ROOT, "bin/standardize_comments")
        long = File.join(@dir, "long.rb")
        short = File.join(@dir, "short.rb")
        File.write(long, source_with_block(limit + 1))
        File.write(short, source_with_block(limit))

        output, status = Open3.capture2e(script, "--check", "--only", "long_block", long)
        expect(status.exitstatus).to eq(1)
        expect(output).to include("[long_block]")

        _, status = Open3.capture2e(script, "--check", "--only", "long_block", short)
        expect(status.exitstatus).to eq(0)
      end
    end
  end
end
