require "spec_helper"

# ADR 0080, section 9 and plan step 11: `bin/` holds no hand-written script. Every tool is a
# command on the Hecks domain, run through the generated `hecks` launcher, so a file under `bin/`
# is either generated (it carries a banner) or it does not exist. While `bin/` still holds the
# shims that step 11 deletes, the example is skipped with that reason; the moment the directory
# is gone the example runs and passes with nothing to inspect, and if a hand-written script comes
# back the example fails and names it.
RSpec.describe "bin/ after the ADR 0080 removal" do
  let(:bin) { File.join(InMemoryDomain::ROOT, "bin") }

  # A generated file says so in its first lines, in Ruby (`# Generated ... do not edit`) or Rust
  # (`// GENERATED by ...`) comment form.
  BANNER = %r{\A\s*(#|//)\s*(Generated\b.*do not edit|GENERATED by\b)}i

  # What a shim over the library looks like: it prints the removal notice or hands its arguments
  # to `Hecks::Tools`.
  SHIM = /Hecks::ThreeZero\.notice|Hecks::Tools\.script\(/

  def files
    Dir.glob(File.join(bin, "**", "*"), File::FNM_DOTMATCH).select { |path| File.file?(path) }
  end

  def banner?(path)
    File.foreach(path).first(12).any? { |line| line.match?(BANNER) }
  end

  it "holds no file that lacks a generated banner, and no shim over the library" do
    skip "bin/ still holds the shims that plan step 11 deletes" if Dir.exist?(bin)

    hand_written = files.reject { |path| banner?(path) }.map { |path| path.delete_prefix("#{bin}/") }
    shims = files.select { |path| File.read(path).match?(SHIM) }.map { |path| path.delete_prefix("#{bin}/") }

    expect(hand_written).to eq([]), "hand-written files under bin/: #{hand_written.join(', ')}"
    expect(shims).to eq([]), "shim files under bin/: #{shims.join(', ')}"
  end
end
