require "tmpdir"
require "open3"
require "rbconfig"
require "fileutils"

# The linter is `Hecks::Tools::CommentStyle`, which `hecks check_comments` runs.
require "hecks/tools/comment_style"

RSpec.describe "Hecks::Tools::CommentStyle" do
  describe "design_history" do
    def history_found(comment)
      source = "# #{comment}\nclass Example\nend\n"
      Hecks::Tools::CommentStyle::SourceFile.new("lib/hecks/example.rb", source).violations(only: ["design_history"])
    end

    ["This is no longer built here.", "There is no cache any more.", "It is not stored anymore."].each do |comment|
      it "flags #{comment.inspect}" do
        expect(history_found(comment).map(&:category)).to eq(["design_history"])
      end
    end

    it "leaves the same words alone inside a code span" do
      expect(history_found("Pass `no longer` to skip the check.")).to be_empty
    end

    it "leaves a present-tense statement alone" do
      expect(history_found("A file that does not exist is skipped.")).to be_empty
    end
  end

  describe "long_block" do
    let(:limit) { Hecks::Tools::CommentStyle::MAX_BLOCK }
    let(:path)  { "lib/hecks/example.rb" }

    # A class opened by a comment block of `lines` lines, the first reading `opening`.
    def source_with_block(lines, opening: "Explains the example at length.")
      body = Array.new(lines - 1) { |index| "# line #{index + 2}" }
      ["# #{opening}", *body, "class Example", "end", ""].join("\n")
    end

    def long_block_violations(source, baseline: {})
      Hecks::Tools::CommentStyle::SourceFile.new(path, source).violations(only: ["long_block"], baseline: baseline)
    end

    it "names the decided threshold as a constant" do
      expect(limit).to eq(12)
    end

    it "passes a block exactly at the threshold" do
      expect(long_block_violations(source_with_block(limit))).to be_empty
    end

    it "fails a new block one line over the threshold", :aggregate_failures do
      found = long_block_violations(source_with_block(limit + 1))

      expect(found.map(&:category)).to eq(["long_block"])
      expect(found.first.line).to eq(1)
      expect(found.first.message).to include("#{limit + 1} lines", "over #{limit}")
    end

    it "passes a block the baseline holds at its current length" do
      baseline = { path => { "Explains the example at length." => limit + 5 } }

      expect(long_block_violations(source_with_block(limit + 5), baseline: baseline)).to be_empty
    end

    it "passes a block that has been trimmed below its baselined length" do
      baseline = { path => { "Explains the example at length." => limit + 20 } }

      expect(long_block_violations(source_with_block(limit + 5), baseline: baseline)).to be_empty
    end

    it "fails a baselined block that has grown", :aggregate_failures do
      baseline = { path => { "Explains the example at length." => limit + 5 } }
      found = long_block_violations(source_with_block(limit + 6), baseline: baseline)

      expect(found.map(&:category)).to eq(["long_block"])
      expect(found.first.message).to include("#{limit + 6} lines", "baselined at #{limit + 5}")
    end

    it "does not tolerate a block whose entry belongs to another file" do
      baseline = { "lib/hecks/other.rb" => { "Explains the example at length." => limit + 5 } }

      expect(long_block_violations(source_with_block(limit + 5), baseline: baseline).size).to eq(1)
    end

    it "keeps a block's key when lines are added above it" do
      baseline = { path => { "Explains the example at length." => limit + 5 } }
      shifted = "# frozen_string_literal: true\n\nmodule Hecks\nend\n\n#{source_with_block(limit + 5)}"

      expect(long_block_violations(shifted, baseline: baseline)).to be_empty
    end

    it "ends a block at a blank source line" do
      more = Array.new(limit) { "# more" }
      split = ["# first half", *more, "", "# second half", *more, "class Example", "end", ""]
      lengths = Hecks::Tools::CommentStyle::SourceFile.new(path, split.join("\n")).long_blocks.map(&:lines)

      expect(lengths).to eq([limit + 1, limit + 1])
    end

    it "numbers blocks that open with the same text" do
      first = source_with_block(limit + 1).sub("class Example\nend\n", "")
      twice = [first, source_with_block(limit + 1)].join("\n")
      keys = Hecks::Tools::CommentStyle::SourceFile.new(path, twice).long_blocks.map(&:key)

      expect(keys).to eq(["Explains the example at length.", "Explains the example at length. #2"])
    end

    it "ignores a generated file, whose comments belong to its generator" do
      generated = "# GENERATED by a tool, DO NOT EDIT\n#{source_with_block(limit + 10)}"

      expect(long_block_violations(generated)).to be_empty
    end

    it "does not count a trailing comment as part of a block" do
      lines = (1..limit).map { |index| "# line #{index}" }
      source = "#{lines.join("\n")}\nvalue = 1 # trailing\n# after the code\nclass Example\nend\n"

      expect(long_block_violations(source)).to be_empty
    end

    describe "the baseline file" do
      around do |example|
        @dir = Dir.mktmpdir("standardize-comments-spec-")
        example.run
      ensure
        FileUtils.remove_entry(@dir) if @dir
      end

      HELD_BASELINE = { "lib/b.rb" => { "z" => 60, "a" => 55 }, "lib/a.rb" => { "m" => 70 } }.freeze

      def write_example(lines)
        file = File.join(@dir, "example.rb")
        File.write(file, source_with_block(lines))
        file
      end

      def recorded_baseline(file) = Hecks::Tools::CommentStyle::Run.new([file], baseline: {}).long_block_baseline

      def long_block_run(file, baseline)
        Hecks::Tools::CommentStyle::Run.new([file], only: ["long_block"], baseline: baseline)
      end

      # Runs `standardize_comments --check` on one file as a child process.
      def check_long_block(file)
        entry = 'require "hecks/tools"; Hecks::Tools.script("standardize_comments", ARGV)'
        script = [RbConfig.ruby, "-I", File.join(InMemoryDomain::ROOT, "lib"), "-e", entry, "--"]
        Open3.capture2e(*script, "--check", "--only", "long_block", file)
      end

      it "round-trips in a stable, sorted order", :aggregate_failures do
        file = File.join(@dir, "baseline.json")
        Hecks::Tools::CommentStyle::Baseline.dump(HELD_BASELINE, file)

        expect(Hecks::Tools::CommentStyle::Baseline.load(file)).to eq(HELD_BASELINE)
        expect(JSON.parse(File.read(file)).keys).to eq(["lib/a.rb", "lib/b.rb"])
        expect(JSON.parse(File.read(file))["lib/b.rb"].keys).to eq(%w[a z])
      end

      it "lives at the checkout's root, where the committed file is", :aggregate_failures do
        root = File.expand_path("..", __dir__)

        expect(Hecks::Tools::CommentStyle::Baseline::PATH).to eq(File.join(root, ".standardize_comments_baseline.json"))
        expect(File.exist?(Hecks::Tools::CommentStyle::Baseline::PATH)).to be(true)
        expect(Hecks::Tools::CommentStyle::Baseline.load).not_to be_empty
      end

      it "is written inside the root the tool is given", :aggregate_failures do
        file = File.join(@dir, "example.rb")
        File.write(file, source_with_block(limit + 3))

        expect { Hecks::Tools::CommentStyle.main(["--write-baseline", file], root: @dir) }.to output.to_stdout

        expect(File.exist?(File.join(@dir, ".standardize_comments_baseline.json"))).to be(true)
      end

      it "passes over an extensionless binary in a scanned directory, and still finds a Ruby script" do
        File.binwrite(File.join(@dir, "compiled"), "\xFF\xFE\x00\x01 not text \xC3\x28\n")
        File.write(File.join(@dir, "tool"), "#!/usr/bin/env ruby\n#{source_with_block(limit + 3)}")

        run = Hecks::Tools::CommentStyle::Run.new([@dir], only: ["long_block"], baseline: {})

        expect(run.violations.map(&:path)).to eq([File.join(@dir, "tool")])
      end

      it "loads as empty when there is no file" do
        expect(Hecks::Tools::CommentStyle::Baseline.load(File.join(@dir, "missing.json"))).to eq({})
      end

      it "is recorded from a run" do
        file = write_example(limit + 3)

        expect(recorded_baseline(file)).to eq(file => { "Explains the example at length." => limit + 3 })
      end

      it "tolerates exactly what it recorded" do
        file = write_example(limit + 3)

        expect(long_block_run(file, recorded_baseline(file)).violations).to be_empty
      end

      it "stops tolerating what it recorded once the block grows" do
        file = write_example(limit + 3)
        held = recorded_baseline(file)
        write_example(limit + 4)

        expect(long_block_run(file, held).violations.map(&:category)).to eq(["long_block"])
      end

      it "makes --check exit non-zero for a new long block", :aggregate_failures do
        output, status = check_long_block(write_example(limit + 1))

        expect(status.exitstatus).to eq(1)
        expect(output).to include("[long_block]")
      end

      it "makes --check exit zero for a short block" do
        _, status = check_long_block(write_example(limit))

        expect(status.exitstatus).to eq(0)
      end
    end
  end
end
