require_relative "support/project_deploy_runner"
require "yaml"
require "tmpdir"
require "fileutils"

# Which `.world` file `hecks deploy project <dir>` reads when none is named after the directory:
# the QA ledger (`qa/`) holds `quality_control.world` beside `governance.world`, attaches the
# QualityControl chapter from the gem, and has no bluebook of its own.
RSpec.describe "hecks deploy project world lookup", :io do
  let(:recipe) { Hecks::Tools.fetch("project_deploy") }

  def root = File.expand_path("..", __dir__)

  def write_domain(dir, worlds:, hecksagon: nil)
    bluebook_dir = File.join(dir, "ledger", "bluebook")
    FileUtils.mkdir_p(bluebook_dir)
    worlds.each { |name| File.write(File.join(bluebook_dir, "#{name}.world"), "Hecks.world \"#{name}\" do\nend\n") }
    File.write(File.join(bluebook_dir, "ledger.hecksagon"), hecksagon) if hecksagon
    File.join(dir, "ledger")
  end

  it "resolves the QA ledger's quality_control.world and writes its recipe" do
    Dir.mktmpdir do |dir|
      _out, err, status = Dir.chdir(root) { ProjectDeployRunner.run("qa", "--out=#{dir}", root: root) }

      expect(status).to be_success, err
      template = File.read(File.join(dir, "template.yaml"))
      expect(template).to start_with("# GENERATED by hecks deploy project qa")
      expect(template).to include("quality-control-webhook")
      resources = YAML.unsafe_load(template).fetch("Resources")
      expect(resources).to include("WebFunctionWebhookSecret")
    end
  end

  it "picks the world named after the chapter the hecksagon attaches among several" do
    Dir.mktmpdir do |dir|
      domain = write_domain(dir, worlds: %w[governance quality_control],
                                 hecksagon: %(Hecks::Chapters.load!("QualityControl")\n))

      expect(recipe.world_file_for(domain)).to eq(File.join(domain, "bluebook", "quality_control.world"))
    end
  end

  it "takes the sole world when it is not named after the directory" do
    Dir.mktmpdir do |dir|
      domain = write_domain(dir, worlds: %w[only_one])

      expect(recipe.world_file_for(domain)).to eq(File.join(domain, "bluebook", "only_one.world"))
    end
  end

  it "refuses to guess among several worlds when none is attached by name" do
    Dir.mktmpdir do |dir|
      domain = write_domain(dir, worlds: %w[governance quality_control])

      expect { recipe.world_file_for(domain) }
        .to raise_error(SystemExit) { |e| expect(e.status).to eq(1) }
        .and output(/does not exist/).to_stderr
    end
  end
end
