require "hecks"
require "hecks/ports/persistence/plugins/era"
require_relative "support/qa_sweep_all_fixture"

# `qa_sweep`'s coverage-guided `CoverageCampaign` persists to a file per (target, mode) so its
# corpus and coverage knowledge compound across separate process invocations (one per tick),
# rather than rebuilding an identical corpus from an identical trace and discarding it at exit
# every time. `spec/fuzzing/coverage_campaign_spec.rb` pins the serialization round trip itself;
# this proves the wiring: the right file, read before the sweep and written after it.
RSpec.describe "qa_sweep coverage corpus persistence", :io do
  include_context "with a qa_sweep_all fixture", "hecks_qa_sweep_coverage_corpus_spec"

  around do |example|
    @corpus_dir = Dir.mktmpdir("qa_sweep_coverage_corpus_spec")
    example.run
    FileUtils.remove_entry(@corpus_dir)
  end

  def run_qa_sweep_with_corpus_dir(*args)
    run_qa_sweep(*args, env: { "QA_SWEEP_COVERAGE_CORPUS_DIR" => @corpus_dir })
  end

  # A sentinel entry standing in for "a prior tick already ran": no real seed of this fixture
  # domain ever produces the verb "Sentinel.Verb", so it can only appear here if the file was
  # actually read, not coincidentally regenerated by this run's own seeds.
  SENTINEL_SEEN = "Sentinel.Verb | verb | absent | - | ok".freeze

  SEEDED_CORPUS_STATE = {
    "corpus"         => [{ "spec" => { "seed" => 999_999, "favor" => [] }, "attempts" => 1 }],
    "seen"           => [SENTINEL_SEEN],
    "verb_hits"      => { "Sentinel.Verb" => 1 },
    "declared_verbs" => ["Sentinel.Verb"]
  }.freeze

  def corpus_file(name) = File.join(@corpus_dir, "#{name}.json")

  # Sweeps `target` with the given flags against the corpus dir, expects a clean exit, and
  # answers stdout.
  def sweep_ok(target, *flags)
    stdout, _stderr, status = run_qa_sweep_with_corpus_dir(target, *flags)
    expect(status.exitstatus).to eq(0), stdout
    stdout
  end

  # `--modes ruby_only` pins the primary seat this fixture target resolves to, so the file this
  # run reads and writes is deterministic without depending on which mode the dials would pick.
  context "with a prior process's saved corpus on disk" do
    before do
      identify_targets!("corpus_target" => @target_domain_relpath)
      File.write(corpus_file("corpus_target-ruby_only"), JSON.generate(SEEDED_CORPUS_STATE))
      @stdout = sweep_ok("corpus_target", "--modes", "ruby_only")
    end

    it "loads the saved corpus before sweeping" do
      expect(@stdout[/spliced from a corpus of (\d+)/, 1].to_i).to be >= 1, @stdout
    end

    it "keeps it, plus what this run found, in the file afterward", :aggregate_failures do
      saved = JSON.parse(File.read(corpus_file("corpus_target-ruby_only")))

      expect(saved["corpus"].map { |entry| entry["spec"]["seed"] }).to include(999_999)
      expect(saved["seen"]).to include(SENTINEL_SEEN)
    end
  end

  it "starts a fresh, empty corpus for a target that has never been swept with coverage guidance", :aggregate_failures do
    identify_targets!("fresh_corpus_target" => @target_domain_relpath)
    corpus_path = corpus_file("fresh_corpus_target-ruby_only")

    expect { sweep_ok("fresh_corpus_target", "--modes", "ruby_only") }.to change { File.exist?(corpus_path) }.from(false).to(true)
    expect(JSON.parse(File.read(corpus_path))).to include("corpus", "seen", "verb_hits", "declared_verbs")
  end

  # `qa_discover_external_domains` suggests `repo/entity`-shaped references for an external
  # domain (e.g. `shop/shop`); `coverage_corpus_path` folds that `/` into a filename,
  # and `FileUtils.mkdir_p(@corpus_dir)` never creates a matching subdirectory for it, so the
  # filename component is sanitized before the write runs. The reference itself keeps its `/` in
  # the ledger — only the filename derived from it changes.
  it "sanitizes a `/` in the target reference so the corpus file lands inside the corpus dir", :aggregate_failures do
    identify_targets!("vendor/fresh_corpus_target" => @target_domain_relpath)
    corpus_path = corpus_file("vendor-fresh_corpus_target-ruby_only")

    expect { sweep_ok("vendor/fresh_corpus_target", "--modes", "ruby_only") }
      .to change { File.exist?(corpus_path) }.from(false).to(true)
    expect(Dir.exist?(File.join(@corpus_dir, "vendor"))).to be(false)
  end

  it "keeps a target's primary-mode corpus in its own file" do
    identify_targets!("parity_corpus_target" => @pg_target_domain_relpath)
    sweep_ok("parity_corpus_target", "--modes", "ruby_only")

    expect(File.exist?(corpus_file("parity_corpus_target-ruby_only"))).to be(true)
  end

  it "keeps a target's persistence-parity-mode corpus in its own file" do
    identify_targets!("parity_corpus_target" => @pg_target_domain_relpath)
    sweep_ok("parity_corpus_target", "--persistence-parity")

    expect(File.exist?(corpus_file("parity_corpus_target-persistence_parity"))).to be(true)
  end
end
