require "hecks"
require "hecks/ports/persistence/plugins/era"
require_relative "support/qa_sweep_all_fixture"

# `qa_sweep`'s coverage-guided `CoverageCampaign` persists to a file per (target, mode) so its
# corpus and coverage knowledge compound across separate process invocations (one per tick),
# rather than rebuilding an identical corpus from an identical trace and discarding it at exit
# every time. `spec/fuzzing/coverage_campaign_spec.rb` pins the serialization round trip itself;
# this proves the wiring: the right file, read before the sweep and written after it.
RSpec.describe "qa_sweep coverage corpus persistence", :io do
  include_context "with a qa_sweep_all fixture", "hecks_qa_sweep_coverage_corpus_spec"

  around do |example|
    @corpus_dir = Dir.mktmpdir("qa_sweep_coverage_corpus_spec")
    example.run
    FileUtils.remove_entry(@corpus_dir)
  end

  def run_qa_sweep_with_corpus_dir(*args)
    run_qa_sweep(*args, env: { "QA_SWEEP_COVERAGE_CORPUS_DIR" => @corpus_dir })
  end

  it "loads a prior process's saved corpus before sweeping, and keeps it (plus what this run " \
     "found) in the file afterward" do
    identify_targets!("corpus_target" => @target_domain_relpath)

    # A sentinel entry standing in for "a prior tick already ran": no real seed of this fixture
    # domain ever produces the verb "Sentinel.Verb", so it can only appear here if the file was
    # actually read, not coincidentally regenerated by this run's own seeds.
    seeded_state = {
      "corpus"         => [{ "spec" => { "seed" => 999_999, "favor" => [] }, "attempts" => 1 }],
      "seen"           => ["Sentinel.Verb | verb | absent | - | ok"],
      "verb_hits"      => { "Sentinel.Verb" => 1 },
      "declared_verbs" => ["Sentinel.Verb"]
    }
    # `--modes ruby_only` pins the primary seat this fixture target resolves to, so the file this
    # run reads and writes is deterministic without depending on which mode the dials would pick.
    corpus_path = File.join(@corpus_dir, "corpus_target-ruby_only.json")
    File.write(corpus_path, JSON.generate(seeded_state))

    stdout, _stderr, status = run_qa_sweep_with_corpus_dir("corpus_target", "--modes", "ruby_only")
    expect(status.exitstatus).to eq(0), stdout

    match = stdout.match(/spliced from a corpus of (\d+)/)
    expect(match).not_to be_nil, stdout
    expect(match[1].to_i).to be >= 1

    saved = JSON.parse(File.read(corpus_path))
    expect(saved["corpus"].map { |entry| entry["spec"]["seed"] }).to include(999_999)
    expect(saved["seen"]).to include("Sentinel.Verb | verb | absent | - | ok")
  end

  it "starts a fresh, empty corpus for a target that has never been swept with coverage guidance" do
    identify_targets!("fresh_corpus_target" => @target_domain_relpath)
    corpus_path = File.join(@corpus_dir, "fresh_corpus_target-ruby_only.json")
    expect(File.exist?(corpus_path)).to be(false)

    stdout, _stderr, status = run_qa_sweep_with_corpus_dir("fresh_corpus_target", "--modes", "ruby_only")
    expect(status.exitstatus).to eq(0), stdout

    expect(File.exist?(corpus_path)).to be(true)
    saved = JSON.parse(File.read(corpus_path))
    expect(saved).to include("corpus", "seen", "verb_hits", "declared_verbs")
  end

  # `qa_discover_external_domains` suggests `repo/entity`-shaped references for an external
  # domain (e.g. `shop/shop`); `coverage_corpus_path` folds that `/` into a filename,
  # and `FileUtils.mkdir_p(@corpus_dir)` never creates a matching subdirectory for it, so the
  # filename component is sanitized before the write runs. The reference itself keeps its `/` in
  # the ledger — only the filename derived from it changes.
  it "sanitizes a `/` in the target reference so the corpus file lands inside the corpus dir" do
    identify_targets!("vendor/fresh_corpus_target" => @target_domain_relpath)
    corpus_path = File.join(@corpus_dir, "vendor-fresh_corpus_target-ruby_only.json")
    expect(File.exist?(corpus_path)).to be(false)

    stdout, _stderr, status = run_qa_sweep_with_corpus_dir("vendor/fresh_corpus_target", "--modes", "ruby_only")
    expect(status.exitstatus).to eq(0), stdout
    expect(File.exist?(corpus_path)).to be(true)
    expect(Dir.exist?(File.join(@corpus_dir, "vendor"))).to be(false)
  end

  it "keeps a target's primary-mode and persistence-parity-mode corpora in separate files" do
    identify_targets!("parity_corpus_target" => @pg_target_domain_relpath)

    stdout, _stderr, status = run_qa_sweep_with_corpus_dir("parity_corpus_target", "--modes", "ruby_only")
    expect(status.exitstatus).to eq(0), stdout
    expect(File.exist?(File.join(@corpus_dir, "parity_corpus_target-ruby_only.json"))).to be(true)

    stdout, _stderr, status = run_qa_sweep_with_corpus_dir("parity_corpus_target", "--persistence-parity")
    expect(status.exitstatus).to eq(0), stdout
    expect(File.exist?(File.join(@corpus_dir, "parity_corpus_target-persistence_parity.json"))).to be(true)
  end
end
