require "spec_helper"
require "tmpdir"
require "fileutils"
require "open3"
require "json"
require "hecks/tools"
require "hecks/tools/site_routes"

# The editor the Site chapter projects from a project's `Editor` row and its domain chapter.
# spec/fixtures/site/editor is a neutral sample project (a small publisher): its bluebook declares
# the row, its domain/ holds the chapter the editor edits, and expected/editor/ holds the files the
# projection must produce, byte for byte. Regenerate them with `GOLDEN=rewrite` and read the diff.
#
# The editor's behaviour is held by running the generated TypeScript under node against a fake
# `fetch` standing in for the domain host.
RSpec.describe Hecks::Projections::Site::CmsEditor do
  let(:project) { File.join(InMemoryDomain::ROOT, "spec/fixtures/site/editor") }
  let(:golden)  { File.join(project, "expected/editor") }

  def projected(editor: "/work/editor") = Hecks::Tools::SiteRoutes.projection(project, out: "/work/out", editor: editor)

  def editor_files
    projected.select { |path, _| path.start_with?("/work/editor/") }.transform_keys { |path| path.delete_prefix("/work/editor/") }
  end

  def golden_names = Dir.glob("**/*", base: golden).select { |name| File.file?(File.join(golden, name)) }.sort

  describe "the projection" do
    it "equals the committed goldens, file for file and byte for byte", :aggregate_failures do
      rewrite_goldens if ENV["GOLDEN"] == "rewrite"

      expect(golden_names).to eq(editor_files.keys.sort)
      editor_files.each do |name, text|
        expect(text).to eq(File.read(File.join(golden, name))), "#{name} has drifted from its golden"
      end
    end

    def rewrite_goldens
      FileUtils.rm_rf(golden)
      editor_files.each do |name, text|
        FileUtils.mkdir_p(File.dirname(File.join(golden, name)))
        File.write(File.join(golden, name), text)
      end
    end

    it "is the same text on every run" do
      first = projected

      expect(projected).to eq(first)
    end

    it "opens each TypeScript file with the banner, and has no time or machine in it", :aggregate_failures do
      sources = editor_files.select { |name, _| name.end_with?(".ts") }

      expect(sources.values).to all(start_with("// Generated by hecks site site_projection.project_site. Do not edit.\n"))
      expect(editor_files.values.join).not_to match(%r{\d{4}-\d\d-\d\d|/Users/|/tmp/})
    end

    it "writes nothing without the flag" do
      expect(Hecks::Tools::SiteRoutes.projection(project, out: "/work/out").keys).to eq(["/work/out/routes.ts"])
    end

    it "reads the domain's shape into schema.ts: value objects, optional parts, lists, lifecycle, queries", :aggregate_failures do
      schema = editor_files.fetch("src/schema.ts")

      expect(schema).to include('"identity": "slug"', '"optional": true', '"list": true', '"widget": "body"')
      expect(schema).to include('"verb": "Archive"', '"Published"', '"role": "Editor"', '"on": "Article"')
    end

    it "gives a value object's parts under its own name, two levels deep", :aggregate_failures do
      schema = JSON.parse(editor_files.fetch("src/schema.ts")[/SCHEMA: Schema = (\{.*\});\n/m, 1])
      article = schema["aggregates"].first

      expect(article["valueObjects"]["Section"].map { |part| part["name"] }).to eq(%w[heading links])
      expect(article["valueObjects"]["Link"].map { |part| part["kind"] }).to eq(%w[text text])
    end

    it "does not offer the lifecycle state as an input" do
      article = JSON.parse(editor_files.fetch("src/schema.ts")[/SCHEMA: Schema = (\{.*\});\n/m, 1])["aggregates"].first

      expect(article["attributes"].map { |attribute| attribute["name"] }).not_to include("status")
    end
  end

  describe "main" do
    let(:work) { Dir.mktmpdir("cms_editor") }

    after { FileUtils.rm_rf(work) }

    def run(*argv)
      out = StringIO.new
      err = StringIO.new
      $stdout = out
      $stderr = err
      [Hecks::Tools::SiteRoutes.main([project, *argv]), out.string, err.string]
    ensure
      $stdout = STDOUT
      $stderr = STDERR
    end

    it "writes the editor's files under --editor" do
      run("--out=#{work}", "--editor=#{work}/editor")

      expect(File.read(File.join(work, "editor/src/schema.ts"))).to eq(File.read(File.join(golden, "src/schema.ts")))
    end

    it "with --check answers 0 when the files are current, and 1 naming one that is stale", :aggregate_failures do
      run("--out=#{work}", "--editor=#{work}/editor")
      File.write(File.join(work, "editor/src/app.ts"), "// edited\n")
      status, _, err = run("--out=#{work}", "--editor=#{work}/editor", "--check")

      expect(status).to eq(1)
      expect(err).to include("out of date: #{File.join(work, "editor/src/app.ts")}")
    end

    it "with --check answers 0 once it is current" do
      run("--out=#{work}", "--editor=#{work}/editor")

      expect(run("--out=#{work}", "--editor=#{work}/editor", "--check").first).to eq(0)
    end
  end

  describe "the Editor row" do
    def refusal
      Dir.mktmpdir("cms_editor_project") do |dir|
        FileUtils.cp_r(File.join(project, "."), dir)
        file = File.join(dir, "bluebook/press_site.bluebook")
        File.write(file, yield(File.read(file)))
        Hecks::Tools::SiteRoutes.projection(dir, out: "/work/out", editor: "/work/editor")
      end
    rescue SystemExit => e
      e.message
    end

    it "is refused when the login page is not a route of the table" do
      text = refusal { |source| source.sub('login: "/admin-login"', 'login: "/nowhere"') }

      expect(text).to include("login /nowhere is not a route of the table")
    end

    it "is refused when the sign-in path is outside the editor's base path" do
      text = refusal { |source| source.sub('base_path: "/editor",', 'base_path: "/editor", sso_path: "/elsewhere/sso",') }

      expect(text).to include("sso_path /elsewhere/sso must be under /editor/")
    end

    it "is refused when a field is unknown" do
      text = refusal { |source| source.sub('title: "Press editor"', 'title: "Press editor", colour: "red"') }

      expect(text).to include("no field colour")
    end

    it "is refused when the row names a chapter the domain does not declare" do
      text = refusal { |source| source.sub('chapter: "Press"', 'chapter: "Elsewhere"') }

      expect(text).to include("declares no chapter Elsewhere")
    end
  end
end
