require "spec_helper"
require "tmpdir"
require "fileutils"
require "open3"
require "json"
require "hecks/tools"
require "hecks/tools/site_routes"

# The Site chapter's route table and the `routes.ts` projected from it.
# spec/fixtures/site/studio is a neutral sample project (a studio's website) whose bluebook
# declares the rows; spec/fixtures/site/routes.ts is the file the projection must produce for it,
# byte for byte. A change to the projection that is meant shows up as a change to that golden,
# which is regenerated with `GOLDEN=rewrite` and read in the diff.
RSpec.describe Hecks::Tools::SiteRoutes do
  let(:project) { File.join(InMemoryDomain::ROOT, "spec/fixtures/site/studio") }
  let(:golden)  { File.join(InMemoryDomain::ROOT, "spec/fixtures/site/routes.ts") }
  let(:table)   { Hecks::Projections::Site::Table }

  def projected(out: "/work/out") = described_class.projection(project, out: out).fetch("#{out}/routes.ts")

  describe "the projection" do
    it "equals the committed golden, byte for byte" do
      File.write(golden, projected) if ENV["GOLDEN"] == "rewrite"

      expect(projected).to eq(File.read(golden)),
                           "routes.ts for the sample project has drifted from spec/fixtures/site/routes.ts"
    end

    it "is the same text on every run, with no time or machine in it" do
      first = described_class.projection(project, out: "/work/out")
      second = described_class.projection(project, out: "/work/out")

      expect(first).to eq(second)
      expect(projected).to start_with("// Generated by hecks site site_projection.project_site. Do not edit.\n")
      expect(projected).to end_with("}\n")
      expect(projected).not_to match(/\d{4}-\d\d-\d\d|Users|tmp/)
    end

    it "writes to generated/ of the project when --out names no directory" do
      files = described_class.projection(project)

      expect(files.keys).to eq([File.join(project, "generated", "routes.ts"), File.join(project, "deploy/template.yaml")])
    end

    it "derives a domain route from a command with the forms scheme, /Chapter/Aggregate/Verb" do
      expect(projected).to include('{ path: "/Studio/Inquiry/Submit", kind: "endpoint"',
                                   'methods: ["POST"]', 'source: "command:Studio.Inquiry.Submit"')
      expect(projected).to include('{ path: "/Studio/Inquiry/Recent", kind: "endpoint", render: "ssr", auth: "admin"')
    end

    it "gives a cache class from the auth, and keeps one a row names" do
      expect(projected).to include('auth: "signed", methods: ["GET"], cache: "no_store"')
      expect(projected).to include('path: "/", kind: "page", render: "prerender", auth: "public", methods: ["GET"]',
                                   'cache: "home"')
      expect(projected).to include('kind: "proxy", render: "ssr", auth: "public", methods: ["GET"], cache: "immutable"')
    end

    it "keeps an off page out of the navigation and the sitemap, and in the 404 rule" do
      expect(projected).to include('off: { status: 404, paths: ["/podcast"] }')
      expect(projected).not_to include('label: "Podcast" }')
      expect(projected).not_to match(/SITEMAP_PATHS = \[[^\]]*podcast/)
    end
  end

  describe "main" do
    let(:work) { Dir.mktmpdir("site_routes") }

    after { FileUtils.rm_rf(work) }

    def run(*argv) = capture { described_class.main([project, *argv]) }

    def capture
      out = StringIO.new
      err = StringIO.new
      nil
      $stdout = out
      $stderr = err
      status = yield
      [status, out.string, err.string]
    ensure
      $stdout = STDOUT
      $stderr = STDERR
    end

    it "writes routes.ts and the template, names them, and answers 0; a second run writes nothing" do
      status, out, = run("--out=#{work}")

      expect(status).to eq(0)
      expect(out).to eq("wrote #{File.join(work, "routes.ts")}\nwrote #{File.join(work, "deploy/template.yaml")}\n")
      expect(File.read(File.join(work, "routes.ts"))).to eq(File.read(golden))

      status, out, = run("--out=#{work}")

      expect([status, out]).to eq([0, "project_site: 2 files, current\n"])
    end

    it "with --check writes nothing, answers 1 and names the stale file" do
      status, out, err = run("--out=#{work}", "--check")

      expect(status).to eq(1)
      expect(out).to eq("")
      expect(err).to include("out of date: #{File.join(work, "routes.ts")}, #{File.join(work, "deploy/template.yaml")}",
                             "run hecks site site_projection.project_site")
      expect(Dir.children(work)).to be_empty
    end

    it "with --check names a file that was edited by hand, and answers 0 when it is current" do
      run("--out=#{work}")
      expect(run("--out=#{work}", "--check").first).to eq(0)

      File.write(File.join(work, "routes.ts"), "// edited\n")
      status, _, err = run("--out=#{work}", "--check")

      expect(status).to eq(1)
      expect(err).to include("out of date: #{File.join(work, "routes.ts")}")
      expect(File.read(File.join(work, "routes.ts"))).to eq("// edited\n")
    end

    it "refuses a project with no bluebook directory" do
      expect { run_in(work) }.to raise_error(SystemExit) { |error| expect(error.message).to include("does not exist") }
    end

    def run_in(dir) = capture { described_class.main([dir]) }
  end

  describe "a route table that contradicts itself" do
    before(:all) do
      registry = described_class.registry_for(File.join(InMemoryDomain::ROOT, "spec/fixtures/site/studio"))
      @vocabulary = Hecks::Projections::Site::Table.vocabulary(registry)
    end

    def refused(*rows)
      Hecks::Projections::Site::Table.new(rows, vocabulary: @vocabulary)
      nil
    rescue Hecks::Projections::Site::Table::Invalid => e
      e.message
    end

    it "reads its closed sets from the Site chapter" do
      expect(@vocabulary.fetch(:cache)).to eq(%w[page home static media immutable no_store])
      expect(@vocabulary.fetch(:kind)).to eq(%w[page endpoint redirect rewrite proxy])
    end

    it "accepts a table of plain pages" do
      expect(refused({ path: "/", label: "Home", nav_order: 1 }, { path: "/about" })).to be_nil
    end

    it "refuses a cache class that is not one of the set, naming the set" do
      expect(refused({ path:  "/",
                       cache: "forever" })).to include("/ has cache \"forever\"",
                                                       "page, home, static, media, immutable, no_store")
    end

    it "refuses an unknown field, kind, auth and method" do
      message = refused({ path: "/a", colour: "red" }, { path: "/b", kind: "frame" }, { path: "/c", auth: "friends" },
                        { path: "/d", methods: "GET,FETCH" })

      expect(message).to include("/a has no field colour", "/b has kind \"frame\"", "/c has auth \"friends\"",
                                 "/d has method \"FETCH\"")
    end

    it "refuses a value of the wrong type" do
      expect(refused({ path: "/", nav_order: "first" })).to include("nav_order is a Integer")
      expect(refused({ path: "/", off: "yes" })).to include("off is true or false")
    end

    it "refuses a path declared twice, an alias included" do
      expect(refused({ path: "/a" }, { path: "/a" })).to include("/a is declared twice")
      expect(refused({ path: "/a", aliases: "/b" }, { path: "/b" })).to include("/b is declared twice")
    end

    it "allows one path for different verbs" do
      expect(refused({ path: "/a", kind: "endpoint", methods: "GET" },
                     { path: "/a", kind: "endpoint", methods: "POST" })).to be_nil
    end

    it "refuses an off route that names no switch" do
      expect(refused({ path: "/x", off: true })).to include("/x is off but names no switch")
    end

    it "refuses rows that disagree about one switch" do
      expect(refused({ path: "/x", switch: "talks", off: true }, { path: "/y", switch: "talks" }))
        .to include("switch talks is on for /y and off for the rest")
    end

    it "accepts an off route in the navigation, since the page keeps its slots while it is off" do
      expect(refused({ path: "/x", switch: "x", off: true, label: "X", nav_order: 1 })).to be_nil
    end

    it "refuses a navigation entry with no label, a parameter, or an admin page in a public menu" do
      message = refused({ path: "/a", nav_order: 1 }, { path: "/b/:id", label: "B", mobile_order: 1 },
                        { path: "/c", label: "C", auth: "admin", footer_column: "Studio" })

      expect(message).to include("/a sits in the navigation and has no label",
                                 "/b/:id sits in the navigation and has a parameter",
                                 "/c is an admin page in the footer navigation")
    end

    it "refuses a redirect with no target, and a target on a page" do
      expect(refused({ path: "/a", kind: "redirect" })).to include("/a is a redirect and needs redirect_to")
      expect(refused({ path: "/a", redirect_to: "/b" })).to include("only a redirect or rewrite has a target")
    end

    it "refuses an indexable admin route and a draft preview with no source" do
      expect(refused({ path: "/a", auth: "admin", indexable: true })).to include("/a is indexable but is admin")
      expect(refused({ path: "/a", preview: "draft" })).to include("previews as a draft but has source none")
    end

    it "refuses a source that is not one of the forms, and one global slug on two pages" do
      expect(refused({ path: "/a", source: "somewhere" })).to include("has source \"somewhere\"")
      expect(refused({ path: "/a", source: "global:a" }, { path: "/b", source: "global:a" }))
        .to include("global:a is used by 2 routes")
    end

    it "refuses a row with no path and no command or query to derive one from" do
      expect(refused({ label: "Nowhere" })).to include("needs a path")
    end

    it "names every problem at once" do
      message = refused({ path: "/a", cache: "forever" }, { path: "/a" }, { path: "/c", off: true })

      expect(message.lines.size).to be >= 4
    end
  end

  describe "a command or query source" do
    it "is refused when no attached chapter declares it" do
      Dir.mktmpdir("site_project") do |dir|
        FileUtils.cp_r(File.join(project, "bluebook"), dir)
        path = File.join(dir, "bluebook/studio_site.bluebook")
        File.write(path, File.read(path).sub("command:Studio.Inquiry.Submit", "command:Studio.Inquiry.Withdraw"))

        expect do
          expect { described_class.projection(dir) }.to raise_error(SystemExit) { |error|
            expect(error.message).to include("Withdraw")
          }
        end.to output(/Withdraw/).to_stderr
      end
    end
  end

  describe "the generated module, run by node" do
    def node? = system("node", "--version", out: File::NULL, err: File::NULL)

    # Node strips TypeScript types from a .ts file it loads, so the module is run as it stands.
    def run_node(script)
      Dir.mktmpdir("routes_ts") do |dir|
        File.write(File.join(dir, "routes.ts"), projected)
        File.write(File.join(dir, "check.mjs"), "import * as site from './routes.ts';\n#{script}")
        out, err, status = Open3.capture3({ "NODE_NO_WARNINGS" => "1" }, "node", File.join(dir, "check.mjs"))
        [out, status, err]
      end
    end

    it "parses and answers the helpers over the sample table" do
      skip "node is not installed" unless node?

      out, status, err = run_node(<<~JS)
        const answers = {
          off: [site.isOffPath("/podcast"), site.isOffPath("/podcast.html"), site.isOffPath("/about")],
          switch: [site.pageIsOn("podcast"), site.pageIsOn("unknown")],
          search: [site.notForSearch("/admin-inbox"), site.notForSearch("/pay/42"), site.notForSearch("/about")],
          preview: [site.previewUrl("global:about"), site.previewUrl("collection:posts", "hello world")],
          globals: site.globalPages.about,
          match: [site.matchesPath("/blog/:slug.html", "/blog/x"), site.matchesPath("/blog/:slug.html", "/blog/x/y")],
          nav: [site.NAV_DESKTOP.length, site.NAV_ADMIN[0].key, site.NAV_FOOTER[0].items.length],
          routes: site.ROUTES.length,
        };
        console.log(JSON.stringify(answers));
      JS

      expect(status.success?).to be(true), err
      expect(JSON.parse(out)).to eq(
        "off" => [true, true, false], "switch" => [false, true], "search" => [true, true, false],
        "preview" => ["/about", "/admin-preview/blog/hello%20world"], "globals" => "/about",
        "match" => [true, false], "nav" => [5, "inbox", 2], "routes" => 35
      )
    end

    it "refuses a preview for a source no route has, and a collection preview with no slug" do
      skip "node is not installed" unless node?

      out, status, err = run_node(<<~JS)
        const errors = [];
        for (const args of [["global:nothing"], ["collection:posts"]]) {
          try { site.previewUrl(...args); } catch (error) { errors.push(error.message); }
        }
        console.log(JSON.stringify(errors));
      JS

      expect(status.success?).to be(true), err
      expect(JSON.parse(out)).to eq(["no route has the source global:nothing",
                                     "collection:posts previews one entry: pass its slug"])
    end
  end
end
