# @@STACK@@: @@WHAT@@.
#   make stacks VPC=vpc-... PRIVATE_SUBNETS=subnet-a,subnet-b PUBLIC_SUBNET=subnet-c [REHEARSAL=true]
#   make deploy @@DEPLOY_HINT@@
RDS_STACK = @@RDS_STACK@@
BOX_STACK = @@BOX_STACK@@
@@REHEARSAL_NOTE@@
REHEARSAL ?= false

HECKS ?= hecks

@@PHONY@@
stacks:
@@RDS_DEPLOY@@
	aws cloudformation deploy --template-file box.yaml --stack-name $(BOX_STACK) --capabilities CAPABILITY_IAM \
		--parameter-overrides VpcId=$(VPC) SubnetId=$(PUBLIC_SUBNET) \
		DbSecurityGroupId=$$(aws cloudformation describe-stacks --stack-name $(RDS_STACK) --query "Stacks[0].Outputs[?OutputKey=='DbSecurityGroupId'].OutputValue" --output text) \
@@DB_SECRET_PARAM@@
		AlertTopicArn=$$(aws cloudformation describe-stacks --stack-name $(RDS_STACK) --query "Stacks[0].Outputs[?OutputKey=='AlertTopicArn'].OutputValue" --output text) \
		Rehearsal=$(REHEARSAL)

@@PROVISION@@
deploy:
@@DEPLOY_RECIPE@@
