# frozen_string_literal: true

module Hecks
  module Tools
    module Lanes
      # The workflow that promotes each lane that follows another: it runs after CI on the lane a
      # lane follows and asks `PromotionRun` to move the lane. The rule that decides a promotion is
      # `PromotionRun.Accept`, not anything written here.
      module Workflow
        HEADER = <<~YAML.chomp
          name: Promote

          # Generated by hecks project_lanes from the Lane rows of the Vocabulary chapter. Do not hand-edit.
          #
          # After CI finishes on a push to the lane a lane follows, asks `PromotionRun` to move the
          # lane onto the newest commit of that lane every RequiredCheck passed on. Which commit may
          # go is decided there (every RequiredCheck green on that exact commit, a fast-forward of
          # the lane), not here. The run is not tied to the commit that started it: a run that is
          # dropped, beaten to the lane, or started by a commit still red finds the same answer, so
          # no certified commit waits on a push that may never come.
        YAML

        module_function

        # @param promoted [Array<Hash{String => String}>] the lanes that follow another
        # @return [String] the workflow
        def text(promoted)
          sources = promoted.map { |lane| lane["follows"] }.uniq
          [HEADER, *trigger(sources), *promoted.flat_map { |lane| job(lane) }].join("\n") << "\n"
        end

        # @param sources [Array<String>] the lanes whose CI run starts a promotion
        # @return [Array<String>] the `on:` through `jobs:` lines
        def trigger(sources)
          ["on:", "  workflow_dispatch: {}", "  workflow_run:", "    workflows: [CI]", "    types: [completed]",
           "    branches: [#{sources.join(", ")}]", "",
           "# One promotion at a time, in the order the pushes finished; none is cancelled.",
           "concurrency:", "  group: promote", "  cancel-in-progress: false", "",
           "permissions:", "  contents: write", "  checks: read", "", "jobs:"]
        end

        # @param lane [Hash{String => String}] a lane that follows another
        # @return [Array<String>] the job that promotes it
        def job(lane)
          name = lane["name"]
          ["  promote_#{name}:", "    runs-on: ubuntu-latest", "    timeout-minutes: 15",
           *condition, "    steps:", *checkout_steps, *promote_step(name)]
        end

        # Which events may start a promotion.
        def condition
          ["    # A run that did not finish green reports no commit worth promoting. Only a push of this",
           "    # repository counts: the run of a fork's pull request from a branch named like the lane",
           "    # also reports that branch name, and its code must never meet the token that moves the lane.",
           "    # A by-hand run, or one the watch asked for, starts from no workflow run and needs no check.",
           "    if: >-", "      github.event_name == 'workflow_dispatch' || (",
           "      github.event.workflow_run.conclusion == 'success' &&",
           "      github.event.workflow_run.event == 'push' &&",
           "      github.event.workflow_run.head_repository.full_name == github.repository)"]
        end

        def checkout_steps
          ["      - uses: actions/checkout@v4", "        with:",
           "          ref: ${{ github.event.workflow_run.head_sha }}",
           "          # Full history: the fast-forward test needs both ends of the lane as real objects.",
           "          fetch-depth: 0",
           "      - uses: ./.github/actions/setup-ruby", "      - uses: ./.github/actions/hecks-environment"]
        end

        def promote_step(name)
          ["      - name: Promote #{name}", "        env:", "          GH_TOKEN: ${{ github.token }}",
           "        run: >-",
           "          bundle exec exe/hecks promotion_run.promote lane=#{name}",
           "          run=#{name}-${{ github.event.workflow_run.head_sha || github.run_id }} --confirm --wait"]
        end
      end
    end
  end
end
