// Generated by hecks project_site. Do not edit.

// The route table of this site, projected from its bluebook's Route rows. Change the rows and run
// `hecks project_site`; `hecks project_site --check` fails when this file is out of date.

export const ROUTES = [
  { path: "/", kind: "page", render: "prerender", auth: "public", methods: ["GET"], cache: "home", origin: "website", source: "global:home", indexable: true, switch: null, off: false, preview: "public", label: "Home", seo: "home", redirectTo: null },
  { path: "/about", kind: "page", render: "prerender", auth: "public", methods: ["GET"], cache: "page", origin: "website", source: "global:about", indexable: true, switch: null, off: false, preview: "public", label: "About", seo: "about", redirectTo: null },
  { path: "/services", kind: "page", render: "prerender", auth: "public", methods: ["GET"], cache: "page", origin: "website", source: "global:services", indexable: true, switch: null, off: false, preview: "public", label: "Services", seo: "services", redirectTo: null },
  { path: "/portfolio", kind: "page", render: "prerender", auth: "public", methods: ["GET"], cache: "page", origin: "website", source: "global:portfolio", indexable: true, switch: null, off: false, preview: "public", label: "Portfolio", seo: "portfolio", redirectTo: null },
  { path: "/blog", kind: "page", render: "prerender", auth: "public", methods: ["GET"], cache: "page", origin: "website", source: "global:blog", indexable: true, switch: null, off: false, preview: "public", label: "Blog", seo: "blog", redirectTo: null },
  { path: "/blog/:slug.html", kind: "page", render: "prerender", auth: "public", methods: ["GET"], cache: "page", origin: "website", source: "collection:posts", indexable: true, switch: null, off: false, preview: "draft", label: null, seo: "post", redirectTo: null },
  { path: "/contact", kind: "page", render: "prerender", auth: "public", methods: ["GET"], cache: "page", origin: "website", source: "global:contact", indexable: true, switch: null, off: false, preview: "public", label: "Contact", seo: "contact", redirectTo: null },
  { path: "/terms", kind: "page", render: "prerender", auth: "public", methods: ["GET"], cache: "page", origin: "website", source: "global:terms", indexable: true, switch: null, off: false, preview: "public", label: "Terms", seo: "terms", redirectTo: null },
  { path: "/privacy", kind: "page", render: "prerender", auth: "public", methods: ["GET"], cache: "page", origin: "website", source: "global:privacy", indexable: true, switch: null, off: false, preview: "public", label: "Privacy", seo: "privacy", redirectTo: null },
  { path: "/podcast", kind: "page", render: "prerender", auth: "public", methods: ["GET"], cache: "page", origin: "website", source: "global:podcast", indexable: false, switch: "podcast", off: true, preview: "public", label: "Podcast", seo: null, redirectTo: null },
  { path: "/inquiry-received", kind: "page", render: "ssr", auth: "public", methods: ["GET"], cache: "page", origin: "website", source: "none", indexable: false, switch: null, off: false, preview: "public", label: null, seo: null, redirectTo: null },
  { path: "/pay/:id", kind: "page", render: "ssr", auth: "signed", methods: ["GET"], cache: "no_store", origin: "website", source: "none", indexable: false, switch: null, off: false, preview: "public", label: null, seo: null, redirectTo: null },
  { path: "/old-portfolio", kind: "redirect", render: "ssr", auth: "public", methods: ["GET"], cache: "page", origin: "website", source: "none", indexable: false, switch: null, off: false, preview: "public", label: null, seo: null, redirectTo: "/portfolio" },
  { path: "/sitemap.xml", kind: "endpoint", render: "ssr", auth: "public", methods: ["GET"], cache: "page", origin: "website", source: "none", indexable: false, switch: null, off: false, preview: "public", label: null, seo: null, redirectTo: null },
  { path: "/robots.txt", kind: "endpoint", render: "ssr", auth: "public", methods: ["GET"], cache: "static", origin: "website", source: "none", indexable: false, switch: null, off: false, preview: "public", label: null, seo: null, redirectTo: null },
  { path: "/assets/*", kind: "proxy", render: "ssr", auth: "public", methods: ["GET"], cache: "immutable", origin: "assets", source: "none", indexable: false, switch: null, off: false, preview: "public", label: null, seo: null, redirectTo: null },
  { path: "/Studio/Inquiry/Submit", kind: "endpoint", render: "ssr", auth: "public", methods: ["POST"], cache: "no_store", origin: "domain", source: "command:Studio.Inquiry.Submit", indexable: false, switch: null, off: false, preview: "public", label: null, seo: null, redirectTo: null },
  { path: "/Studio/Inquiry/Recent", kind: "endpoint", render: "ssr", auth: "admin", methods: ["GET"], cache: "no_store", origin: "domain", source: "query:Studio.Inquiry.Recent", indexable: false, switch: null, off: false, preview: "public", label: null, seo: null, redirectTo: null },
  { path: "/admin-inbox", kind: "page", render: "ssr", auth: "admin", methods: ["GET"], cache: "no_store", origin: "website", source: "none", indexable: false, switch: null, off: false, preview: "public", label: "Inbox", seo: null, redirectTo: null },
  { path: "/admin-posts", kind: "page", render: "ssr", auth: "admin", methods: ["GET"], cache: "no_store", origin: "website", source: "none", indexable: false, switch: null, off: false, preview: "public", label: "Posts", seo: null, redirectTo: null },
  { path: "/admin-analytics", kind: "page", render: "ssr", auth: "admin", methods: ["GET"], cache: "no_store", origin: "website", source: "none", indexable: false, switch: null, off: false, preview: "public", label: "Analytics", seo: null, redirectTo: null },
] as const;

export type Route = (typeof ROUTES)[number];

// A page's switch: false while the page is off. A page without a switch is always on.
export const SWITCHES: Readonly<Record<string, boolean>> = { podcast: false };

export const REDIRECTS = [
  { from: "/about-us", to: "/about", status: 301 },
  { from: "/old-portfolio", to: "/portfolio", status: 301 },
  { from: "/who-we-are", to: "/about", status: 301 },
] as const;

// The three rules the site's middleware applies, as data: a switched-off page answers 404, a
// request under the preview prefix is served from draft content, and `.html` is dropped.
export const MIDDLEWARE = {
  off: { status: 404, paths: ["/podcast"] },
  preview: { prefix: "/admin-preview" },
  stripHtml: { suffix: ".html" },
} as const;

// The desktop navigation: a page with no group is its own entry; a group holds its pages.
export const NAV_DESKTOP = [
  { group: null, items: [{ path: "/", label: "Home" }] },
  { group: null, items: [{ path: "/about", label: "About" }] },
  { group: "Work", items: [{ path: "/services", label: "Services" }, { path: "/portfolio", label: "Portfolio" }] },
  { group: null, items: [{ path: "/blog", label: "Blog" }] },
  { group: null, items: [{ path: "/contact", label: "Contact" }] },
] as const;

// The mobile navigation, in its own order.
export const NAV_MOBILE = [
  { path: "/", label: "Home" },
  { path: "/about", label: "About" },
  { path: "/services", label: "Services" },
  { path: "/portfolio", label: "Portfolio" },
  { path: "/blog", label: "Blog" },
  { path: "/contact", label: "Contact" },
] as const;

// The footer columns, left to right, each with its links.
export const NAV_FOOTER = [
  { column: "Studio", items: [{ path: "/terms", label: "Terms" }, { path: "/privacy", label: "Privacy" }] },
] as const;

// The admin navigation: each admin page under its key.
export const NAV_ADMIN = [
  { key: "inbox", path: "/admin-inbox", label: "Inbox" },
  { key: "posts", path: "/admin-posts", label: "Posts" },
  { key: "analytics", path: "/admin-analytics", label: "Analytics" },
] as const;

// The paths a sitemap lists: indexable pages with no parameter. A collection's pages are listed
// from its entries, through `collectionPages`.
export const SITEMAP_PATHS = ["/", "/about", "/blog", "/contact", "/portfolio", "/privacy", "/services", "/terms"] as const;

// The routes a search engine is kept away from: every route that is not indexable.
export const NOT_FOR_SEARCH = ["/Studio/Inquiry/Recent", "/Studio/Inquiry/Submit", "/admin-analytics", "/admin-inbox", "/admin-posts", "/assets/*", "/inquiry-received", "/old-portfolio", "/pay/:id", "/podcast", "/robots.txt", "/sitemap.xml"] as const;

// robots.txt `Disallow` prefixes: each non-public route up to its first parameter.
export const ROBOTS_DISALLOW = ["/Studio/Inquiry/Recent", "/admin-analytics", "/admin-inbox", "/admin-posts", "/admin-preview/", "/pay/"] as const;

// A CMS global's slug to the page that shows it.
export const globalPages = { about: "/about", blog: "/blog", contact: "/contact", home: "/", podcast: "/podcast", portfolio: "/portfolio", privacy: "/privacy", services: "/services", terms: "/terms" } as const;

// A CMS collection's name to the page that shows one of its entries, and whether the sitemap lists them.
export const collectionPages = { posts: { path: "/blog/:slug.html", indexable: true } } as const;

const PREVIEWS: Readonly<Record<string, { readonly path: string; readonly draft: boolean }>> = { "collection:posts": { path: "/blog/:slug.html", draft: true }, "global:about": { path: "/about", draft: false }, "global:blog": { path: "/blog", draft: false }, "global:contact": { path: "/contact", draft: false }, "global:home": { path: "/", draft: false }, "global:podcast": { path: "/podcast", draft: false }, "global:portfolio": { path: "/portfolio", draft: false }, "global:privacy": { path: "/privacy", draft: false }, "global:services": { path: "/services", draft: false }, "global:terms": { path: "/terms", draft: false } };

/** Drops a trailing `.html` and a trailing slash, so `/about.html`, `/about/` and `/about` are one path. */
export function stripHtml(pathname: string): string {
  const bare = pathname.endsWith(".html") ? pathname.slice(0, -".html".length) : pathname;
  return bare.length > 1 && bare.endsWith("/") ? bare.slice(0, -1) : bare;
}

function toRegExp(pattern: string): RegExp {
  const source = stripHtml(pattern)
    .split("/")
    .map((part) =>
      part === "*" ? ".*" : part.startsWith(":") ? "[^/]+" : part.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"),
    )
    .join("/");
  return new RegExp("^" + source + "$");
}

/** Whether a pathname is one a route pattern (`/blog/:slug.html`, `/pay/*`) describes, with or without `.html`. */
export function matchesPath(pattern: string, pathname: string): boolean {
  return toRegExp(pattern).test(stripHtml(pathname));
}

/** Whether a page is on: true for an id no row switches off, and for an id no row names. */
export function pageIsOn(id: string): boolean {
  return Object.prototype.hasOwnProperty.call(SWITCHES, id) ? SWITCHES[id] : true;
}

/** Whether a pathname belongs to a switched-off page, with or without `.html`. */
export function isOffPath(pathname: string): boolean {
  return MIDDLEWARE.off.paths.some((pattern) => matchesPath(pattern, pathname));
}

/** Whether a search engine is kept away from a pathname. */
export function notForSearch(pathname: string): boolean {
  return NOT_FOR_SEARCH.some((pattern) => matchesPath(pattern, pathname));
}

/** The URL that previews a CMS source (`global:<slug>` or `collection:<name>`), under the preview prefix when it is a draft. */
export function previewUrl(source: string, slug?: string): string {
  const entry = PREVIEWS[source];
  if (entry === undefined) throw new Error(`no route has the source ${source}`);
  let path = entry.path;
  if (path.includes(":")) {
    if (slug === undefined) throw new Error(`${source} previews one entry: pass its slug`);
    path = path.replace(/:[A-Za-z_]\w*/, encodeURIComponent(slug));
  }
  return entry.draft ? MIDDLEWARE.preview.prefix + stripHtml(path) : path;
}
