// Generated by hecks site site_projection.project_site. Do not edit.

// The domain's shape, read from its bluebook: every aggregate with its attributes, value objects,
// lifecycle, commands and queries. The pages, the forms and the input parser all read this one
// constant, so the editor can edit any aggregate; none of it is written by hand.

/** How an attribute's value is entered: `object` is a value object, the rest are single values. */
export type Kind = "text" | "integer" | "number" | "boolean" | "object" | "reference";

/**
 * What an attribute names: an instance of another aggregate, offered as a choice. `strict` pickers
 * accept only a key that exists; the others suggest and accept any text. `listing` is the query of
 * the target that lists what is on offer, or none to offer every instance. With `kinds`, the value is
 * `<kind>:<key>`: the kind is chosen first, then the record of the aggregate that kind names.
 */
export interface Picker {
  target?: string;
  /** The target's chapter, when the editor spans several or the target is in another. */
  chapter?: string;
  /** The target's identity attribute. */
  key?: string;
  /** The attribute that names an instance to a person (its title, name or label, else its identity). */
  label?: string;
  listing?: string;
  strict?: boolean;
  kinds?: PickerKind[];
}

/** One kind of a `<kind>:<key>` value, and the aggregate it names when it names one. */
export type PickerKind = Omit<Picker, "kinds"> & { kind: string };

/**
 * A list of mixed blocks: a list of one value object whose `discriminator` part is one of `kinds`. With
 * `rules`, each kind's `requires` (parts it must have) and `uses` (parts it may have) come from a
 * declared table; a part no row names belongs to every kind. With none, every part is shown and
 * `mentions` says which parts a kind's rules read. `limits` are the most each list part of the block
 * may hold; `pictures` says, for a value object, which of its parts are a picture's key, alt text and caption.
 */
export interface BlockList {
  discriminator: string;
  kinds: string[];
  rules?: Record<string, { requires: string[]; uses: string[] }>;
  mentions?: Record<string, string[]>;
  limits?: Record<string, number>;
  pictures?: Record<string, { key: string; alt: string; caption?: string }>;
}

export interface Attr {
  name: string;
  /** The type as the bluebook spells it ("String", "Byline"). */
  type: string;
  kind: Kind;
  optional: boolean;
  /** True for `list_of`: the attribute holds a list of `type`. */
  list: boolean;
  /**
   * `body` for an attribute whose value object has the shape of a structured document (blocks of
   * spans); `date` or `datetime` for whole seconds since 1970 that the names say are a moment.
   */
  widget?: "body" | "date" | "datetime";
  /** Set when the attribute names an instance of another aggregate of the editor. */
  picker?: Picker;
  /** The members of the closed set the attribute is one of, when its value object declares one. */
  options?: string[];
  /** The aggregate a `reference` points at. */
  target?: string;
  /** Set when the attribute is a list of mixed blocks (see `BlockList`). */
  blockList?: BlockList;
  /** The most rows the list may hold, when a rule of its holder (an invariant or a command's `given`) says. */
  max?: number;
  /** The fewest rows the list may hold, when a rule of its holder says. */
  min?: number;
  /** The most characters a text may hold, when a rule of its holder says. */
  maxLength?: number;
  /** True when `maxLength` is long enough for the text to be written in a box of several lines. */
  multiline?: boolean;
  /** Set when the value object is a picture: the names of its parts that hold the file, its description and its caption. */
  picture?: { key: string; alt: string; caption?: string };
}

export interface Transition {
  verb: string;
  from: string[];
  to: string;
}

export interface Lifecycle {
  field: string;
  default: string;
  transitions: Transition[];
  /** Each state's badge tone: `neutral`, `ok`, `info`, `warn` or `danger`. */
  tones: Record<string, string>;
}

export interface Command {
  name: string;
  goal: string | null;
  role: string | null;
  /** True when the command makes a new instance; false when it acts on one (`reference_to`). */
  creates: boolean;
  /** The aggregate the command acts on, when it is not a creating command. */
  on: string | null;
  /** True when the editor asks for confirmation before running it (see the generator's `Destructive`). */
  destructive: boolean;
  attributes: Attr[];
  /** The arguments that only clear a field and are not offered as inputs: sent as empty lists. */
  empty?: string[];
}

export interface Query {
  name: string;
  description: string | null;
  attributes: Attr[];
}

/**
 * A record of another aggregate that goes with this one's records, because its identity is a
 * `<kind>:<slug>` key of this aggregate. `shape` says how to show it; `create` and `edit` name the
 * commands that make and change it, when it has them.
 */
export interface Related {
  aggregate: string;
  chapter?: string;
  /** The related aggregate's identity attribute, which the key fills. */
  field: string;
  shape: "document" | "gallery" | "metadata";
  create?: string;
  edit?: string;
}

/** An aggregate that keeps a draft of its content beside the live one, and the commands that handle it. */
export interface Drafts {
  /** The draft attribute (`draft_body`, `draft_content`) and the live one it stands for (`body`, `content`). */
  attribute: string;
  live: string;
  save: string;
  publish?: string;
  discard?: string;
}

export interface Aggregate {
  name: string;
  /** The chapter that declares the aggregate; set when the editor spans several. */
  chapter?: string;
  /** The roles that may edit it, when its chapter limits them; any admitted role otherwise. */
  roles?: string[];
  description: string | null;
  identity: string;
  lifecycle: Lifecycle | null;
  attributes: Attr[];
  valueObjects: Record<string, Attr[]>;
  commands: Command[];
  queries: Query[];
  /** The aggregates keyed by this one's records, shown as panels on a record's page. */
  related?: Related[];
  /** The draft the aggregate keeps beside its live content, when it keeps one. */
  drafts?: Drafts;
}

/** How one part of a picture's record is sent: `wrap` is the part of a value object that holds the value. */
export interface MediaField {
  name: string;
  wrap: string | null;
}

/** The aggregate that registers pictures, when the chapter has one: found by shape, never by name. */
export interface Media {
  aggregate: string;
  command: string;
  fields: { key: MediaField; alt: MediaField; mime: MediaField; width?: MediaField; height?: MediaField };
  /** The query that lists the pictures, or null when every instance is read. */
  listing: string | null;
  /** The chapter that holds the picture aggregate, when it is not this editor's own chapter. */
  domain?: string;
  /** That aggregate, which is then not among the editor's own; see `domain`. */
  definition?: Aggregate;
}

/**
 * The aggregate whose records are actions to run later, found by shape: the attribute that names the
 * record an action is for, the closed set of actions, the due time, and the commands. The editor only
 * makes and changes these records; something else runs them.
 */
export interface Scheduling {
  aggregate: string;
  chapter?: string;
  subject: string;
  action: string;
  actions: string[];
  due: string;
  /** The first state of a record: an action not yet run. */
  pending: string;
  schedule: string;
  reschedule?: string;
  cancel?: string;
  /** The query that lists the actions of one subject, when there is one. */
  query?: string;
  /** The optional text a record may carry to say why it ended as it did. */
  reason?: string;
  /** True when the editor makes the record's identity, since it is not the subject. */
  generated?: boolean;
}

export interface Schema {
  /** The first chapter, which names the domain the host is asked for. */
  domain: string;
  /** Every chapter, in the order the navigation groups them; set when the editor spans several. */
  chapters?: string[];
  aggregates: Aggregate[];
  media?: Media;
  scheduling?: Scheduling;
}

export const SCHEMA: Schema = {
  "domain": "Leaflets",
  "chapters": [
    "Leaflets",
    "Pictures"
  ],
  "aggregates": [
    {
      "name": "NotePage",
      "chapter": "Leaflets",
      "description": "A page of one titled piece of writing, and an edit saved aside until it is put live.",
      "identity": "key",
      "lifecycle": null,
      "attributes": [
        {
          "name": "key",
          "type": "LeafletKey",
          "kind": "object",
          "optional": false,
          "list": false,
          "picker": {
            "kinds": [
              {
                "kind": "page"
              }
            ]
          }
        },
        {
          "name": "content",
          "type": "NoteContent",
          "kind": "object",
          "optional": false,
          "list": false
        },
        {
          "name": "draft_content",
          "type": "NoteContent",
          "kind": "object",
          "optional": true,
          "list": false
        }
      ],
      "valueObjects": {
        "LeafletKey": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "NoteContent": [
          {
            "name": "heading",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false,
            "maxLength": 120
          },
          {
            "name": "summary",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false,
            "maxLength": 600,
            "multiline": true
          },
          {
            "name": "body",
            "type": "Body",
            "kind": "object",
            "optional": false,
            "list": false,
            "widget": "body"
          },
          {
            "name": "more",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false
          },
          {
            "name": "rows",
            "type": "Row",
            "kind": "object",
            "optional": false,
            "list": true,
            "max": 20
          }
        ],
        "Row": [
          {
            "name": "title",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          },
          {
            "name": "cells",
            "type": "Cell",
            "kind": "object",
            "optional": false,
            "list": true,
            "max": 8
          }
        ],
        "Cell": [
          {
            "name": "text",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "Body": [
          {
            "name": "blocks",
            "type": "Block",
            "kind": "object",
            "optional": false,
            "list": true
          }
        ],
        "Block": [
          {
            "name": "kind",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          },
          {
            "name": "level",
            "type": "Integer",
            "kind": "integer",
            "optional": true,
            "list": false
          },
          {
            "name": "align",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false
          },
          {
            "name": "indent",
            "type": "Integer",
            "kind": "integer",
            "optional": true,
            "list": false
          },
          {
            "name": "spans",
            "type": "Span",
            "kind": "object",
            "optional": false,
            "list": true
          },
          {
            "name": "items",
            "type": "Item",
            "kind": "object",
            "optional": false,
            "list": true
          },
          {
            "name": "media_ref",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false
          },
          {
            "name": "alt",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false
          },
          {
            "name": "caption",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false
          }
        ],
        "Item": [
          {
            "name": "spans",
            "type": "Span",
            "kind": "object",
            "optional": false,
            "list": true
          },
          {
            "name": "depth",
            "type": "Integer",
            "kind": "integer",
            "optional": true,
            "list": false
          },
          {
            "name": "list_kind",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false
          }
        ],
        "Span": [
          {
            "name": "text",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          },
          {
            "name": "marks",
            "type": "Mark",
            "kind": "object",
            "optional": false,
            "list": true,
            "blockList": {
              "discriminator": "name",
              "kinds": [
                "bold",
                "italic",
                "underline",
                "strike",
                "code"
              ]
            }
          },
          {
            "name": "href",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false
          }
        ],
        "Mark": [
          {
            "name": "name",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ]
      },
      "commands": [
        {
          "name": "Write",
          "goal": "Start a note page",
          "role": "Editor",
          "creates": true,
          "on": null,
          "destructive": false,
          "attributes": [
            {
              "name": "key",
              "type": "LeafletKey",
              "kind": "object",
              "optional": false,
              "list": false,
              "picker": {
                "kinds": [
                  {
                    "kind": "page"
                  }
                ]
              }
            },
            {
              "name": "content",
              "type": "NoteContent",
              "kind": "object",
              "optional": false,
              "list": false
            }
          ]
        },
        {
          "name": "Revise",
          "goal": "Replace the content readers see",
          "role": "Editor",
          "creates": false,
          "on": "NotePage",
          "destructive": false,
          "attributes": [
            {
              "name": "content",
              "type": "NoteContent",
              "kind": "object",
              "optional": false,
              "list": false
            }
          ]
        },
        {
          "name": "SaveDraft",
          "goal": "Keep an edit aside without changing what readers see",
          "role": "Editor",
          "creates": false,
          "on": "NotePage",
          "destructive": false,
          "attributes": [
            {
              "name": "draft_content",
              "type": "NoteContent",
              "kind": "object",
              "optional": false,
              "list": false
            }
          ]
        },
        {
          "name": "PublishDraft",
          "goal": "Make the saved edit what readers see, and clear it",
          "role": "Editor",
          "creates": false,
          "on": "NotePage",
          "destructive": false,
          "attributes": []
        },
        {
          "name": "DiscardDraft",
          "goal": "Drop the saved edit and keep what readers see",
          "role": "Editor",
          "creates": false,
          "on": "NotePage",
          "destructive": true,
          "attributes": []
        }
      ],
      "queries": [
        {
          "name": "Listing",
          "description": "Every note page.",
          "attributes": []
        }
      ],
      "drafts": {
        "attribute": "draft_content",
        "live": "content",
        "save": "SaveDraft",
        "publish": "PublishDraft",
        "discard": "DiscardDraft"
      }
    },
    {
      "name": "ChaptersPage",
      "chapter": "Leaflets",
      "description": "A page that opens with a hero and tells a sequence of chapters, and an edit saved aside until it is put live.",
      "identity": "key",
      "lifecycle": null,
      "attributes": [
        {
          "name": "key",
          "type": "LeafletKey",
          "kind": "object",
          "optional": false,
          "list": false,
          "picker": {
            "kinds": [
              {
                "kind": "page"
              }
            ]
          }
        },
        {
          "name": "content",
          "type": "ChaptersContent",
          "kind": "object",
          "optional": false,
          "list": false
        },
        {
          "name": "draft_content",
          "type": "ChaptersContent",
          "kind": "object",
          "optional": true,
          "list": false
        }
      ],
      "valueObjects": {
        "LeafletKey": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "ChaptersContent": [
          {
            "name": "hero",
            "type": "Hero",
            "kind": "object",
            "optional": true,
            "list": false
          },
          {
            "name": "chapters",
            "type": "Chapter",
            "kind": "object",
            "optional": false,
            "list": true,
            "min": 1,
            "max": 60
          }
        ],
        "Hero": [
          {
            "name": "heading",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          },
          {
            "name": "summary",
            "type": "Body",
            "kind": "object",
            "optional": true,
            "list": false,
            "widget": "body"
          },
          {
            "name": "picture",
            "type": "Picture",
            "kind": "object",
            "optional": true,
            "list": false,
            "picture": {
              "key": "media_ref",
              "alt": "alt",
              "caption": "caption"
            }
          }
        ],
        "Chapter": [
          {
            "name": "verse",
            "type": "Verse",
            "kind": "object",
            "optional": true,
            "list": false
          },
          {
            "name": "band",
            "type": "Band",
            "kind": "object",
            "optional": true,
            "list": false,
            "picture": {
              "key": "media_ref",
              "alt": "alt",
              "caption": "caption"
            }
          },
          {
            "name": "heading",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false
          },
          {
            "name": "body",
            "type": "Body",
            "kind": "object",
            "optional": true,
            "list": false,
            "widget": "body"
          },
          {
            "name": "parts",
            "type": "Part",
            "kind": "object",
            "optional": false,
            "list": true,
            "max": 12
          }
        ],
        "Verse": [
          {
            "name": "heading",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false
          },
          {
            "name": "body",
            "type": "Body",
            "kind": "object",
            "optional": false,
            "list": false,
            "widget": "body"
          }
        ],
        "Band": [
          {
            "name": "media_ref",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          },
          {
            "name": "alt",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          },
          {
            "name": "caption",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false
          },
          {
            "name": "align",
            "type": "BandAlign",
            "kind": "object",
            "optional": true,
            "list": false,
            "options": [
              "left",
              "center",
              "right"
            ]
          }
        ],
        "BandAlign": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "Part": [
          {
            "name": "heading",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          },
          {
            "name": "body",
            "type": "Body",
            "kind": "object",
            "optional": false,
            "list": false,
            "widget": "body"
          }
        ],
        "Picture": [
          {
            "name": "media_ref",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          },
          {
            "name": "alt",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          },
          {
            "name": "caption",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false
          }
        ],
        "Body": [
          {
            "name": "blocks",
            "type": "Block",
            "kind": "object",
            "optional": false,
            "list": true
          }
        ],
        "Block": [
          {
            "name": "kind",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          },
          {
            "name": "level",
            "type": "Integer",
            "kind": "integer",
            "optional": true,
            "list": false
          },
          {
            "name": "align",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false
          },
          {
            "name": "indent",
            "type": "Integer",
            "kind": "integer",
            "optional": true,
            "list": false
          },
          {
            "name": "spans",
            "type": "Span",
            "kind": "object",
            "optional": false,
            "list": true
          },
          {
            "name": "items",
            "type": "Item",
            "kind": "object",
            "optional": false,
            "list": true
          },
          {
            "name": "media_ref",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false
          },
          {
            "name": "alt",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false
          },
          {
            "name": "caption",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false
          }
        ],
        "Item": [
          {
            "name": "spans",
            "type": "Span",
            "kind": "object",
            "optional": false,
            "list": true
          },
          {
            "name": "depth",
            "type": "Integer",
            "kind": "integer",
            "optional": true,
            "list": false
          },
          {
            "name": "list_kind",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false
          }
        ],
        "Span": [
          {
            "name": "text",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          },
          {
            "name": "marks",
            "type": "Mark",
            "kind": "object",
            "optional": false,
            "list": true,
            "blockList": {
              "discriminator": "name",
              "kinds": [
                "bold",
                "italic",
                "underline",
                "strike",
                "code"
              ]
            }
          },
          {
            "name": "href",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false
          }
        ],
        "Mark": [
          {
            "name": "name",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ]
      },
      "commands": [
        {
          "name": "Write",
          "goal": "Start a chapters page",
          "role": "Editor",
          "creates": true,
          "on": null,
          "destructive": false,
          "attributes": [
            {
              "name": "key",
              "type": "LeafletKey",
              "kind": "object",
              "optional": false,
              "list": false,
              "picker": {
                "kinds": [
                  {
                    "kind": "page"
                  }
                ]
              }
            },
            {
              "name": "content",
              "type": "ChaptersContent",
              "kind": "object",
              "optional": false,
              "list": false
            }
          ]
        },
        {
          "name": "Revise",
          "goal": "Replace the content readers see",
          "role": "Editor",
          "creates": false,
          "on": "ChaptersPage",
          "destructive": false,
          "attributes": [
            {
              "name": "content",
              "type": "ChaptersContent",
              "kind": "object",
              "optional": false,
              "list": false
            }
          ]
        },
        {
          "name": "SaveDraft",
          "goal": "Keep an edit aside without changing what readers see",
          "role": "Editor",
          "creates": false,
          "on": "ChaptersPage",
          "destructive": false,
          "attributes": [
            {
              "name": "draft_content",
              "type": "ChaptersContent",
              "kind": "object",
              "optional": false,
              "list": false
            }
          ]
        },
        {
          "name": "PublishDraft",
          "goal": "Make the saved edit what readers see, and clear it",
          "role": "Editor",
          "creates": false,
          "on": "ChaptersPage",
          "destructive": false,
          "attributes": []
        },
        {
          "name": "DiscardDraft",
          "goal": "Drop the saved edit and keep what readers see",
          "role": "Editor",
          "creates": false,
          "on": "ChaptersPage",
          "destructive": true,
          "attributes": []
        }
      ],
      "queries": [
        {
          "name": "Listing",
          "description": "Every chapters page.",
          "attributes": []
        }
      ],
      "drafts": {
        "attribute": "draft_content",
        "live": "content",
        "save": "SaveDraft",
        "publish": "PublishDraft",
        "discard": "DiscardDraft"
      }
    },
    {
      "name": "GalleryPage",
      "chapter": "Leaflets",
      "description": "A page of pictures in order, and an edit saved aside until it is put live.",
      "identity": "key",
      "lifecycle": null,
      "attributes": [
        {
          "name": "key",
          "type": "LeafletKey",
          "kind": "object",
          "optional": false,
          "list": false,
          "picker": {
            "kinds": [
              {
                "kind": "page"
              }
            ]
          }
        },
        {
          "name": "content",
          "type": "GalleryContent",
          "kind": "object",
          "optional": false,
          "list": false
        },
        {
          "name": "draft_content",
          "type": "GalleryContent",
          "kind": "object",
          "optional": true,
          "list": false
        }
      ],
      "valueObjects": {
        "LeafletKey": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "GalleryContent": [
          {
            "name": "heading",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false
          },
          {
            "name": "photos",
            "type": "Picture",
            "kind": "object",
            "optional": false,
            "list": true,
            "picture": {
              "key": "media_ref",
              "alt": "alt",
              "caption": "caption"
            },
            "min": 1,
            "max": 60
          }
        ],
        "Picture": [
          {
            "name": "media_ref",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          },
          {
            "name": "alt",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          },
          {
            "name": "caption",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false
          }
        ]
      },
      "commands": [
        {
          "name": "Write",
          "goal": "Start a gallery page",
          "role": "Editor",
          "creates": true,
          "on": null,
          "destructive": false,
          "attributes": [
            {
              "name": "key",
              "type": "LeafletKey",
              "kind": "object",
              "optional": false,
              "list": false,
              "picker": {
                "kinds": [
                  {
                    "kind": "page"
                  }
                ]
              }
            },
            {
              "name": "content",
              "type": "GalleryContent",
              "kind": "object",
              "optional": false,
              "list": false
            }
          ]
        },
        {
          "name": "Revise",
          "goal": "Replace the content readers see",
          "role": "Editor",
          "creates": false,
          "on": "GalleryPage",
          "destructive": false,
          "attributes": [
            {
              "name": "content",
              "type": "GalleryContent",
              "kind": "object",
              "optional": false,
              "list": false
            }
          ]
        },
        {
          "name": "SaveDraft",
          "goal": "Keep an edit aside without changing what readers see",
          "role": "Editor",
          "creates": false,
          "on": "GalleryPage",
          "destructive": false,
          "attributes": [
            {
              "name": "draft_content",
              "type": "GalleryContent",
              "kind": "object",
              "optional": false,
              "list": false
            }
          ]
        },
        {
          "name": "PublishDraft",
          "goal": "Make the saved edit what readers see, and clear it",
          "role": "Editor",
          "creates": false,
          "on": "GalleryPage",
          "destructive": false,
          "attributes": []
        },
        {
          "name": "DiscardDraft",
          "goal": "Drop the saved edit and keep what readers see",
          "role": "Editor",
          "creates": false,
          "on": "GalleryPage",
          "destructive": true,
          "attributes": []
        }
      ],
      "queries": [
        {
          "name": "Listing",
          "description": "Every gallery page.",
          "attributes": []
        }
      ],
      "drafts": {
        "attribute": "draft_content",
        "live": "content",
        "save": "SaveDraft",
        "publish": "PublishDraft",
        "discard": "DiscardDraft"
      }
    },
    {
      "name": "RosterPage",
      "chapter": "Leaflets",
      "description": "A page of people in order, kept as a list with an edit saved aside until it is put live.",
      "identity": "key",
      "lifecycle": null,
      "attributes": [
        {
          "name": "key",
          "type": "LeafletKey",
          "kind": "object",
          "optional": false,
          "list": false,
          "picker": {
            "kinds": [
              {
                "kind": "page"
              }
            ]
          }
        },
        {
          "name": "people",
          "type": "Person",
          "kind": "object",
          "optional": false,
          "list": true
        },
        {
          "name": "draft_people",
          "type": "Person",
          "kind": "object",
          "optional": false,
          "list": true
        }
      ],
      "valueObjects": {
        "LeafletKey": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "Person": [
          {
            "name": "name",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false,
            "maxLength": 80
          },
          {
            "name": "role",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false
          },
          {
            "name": "about",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false,
            "maxLength": 1000,
            "multiline": true
          },
          {
            "name": "portrait",
            "type": "Picture",
            "kind": "object",
            "optional": true,
            "list": false,
            "picture": {
              "key": "media_ref",
              "alt": "alt",
              "caption": "caption"
            }
          }
        ],
        "Picture": [
          {
            "name": "media_ref",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          },
          {
            "name": "alt",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          },
          {
            "name": "caption",
            "type": "String",
            "kind": "text",
            "optional": true,
            "list": false
          }
        ]
      },
      "commands": [
        {
          "name": "Write",
          "goal": "Start a roster page",
          "role": "Editor",
          "creates": true,
          "on": null,
          "destructive": false,
          "attributes": [
            {
              "name": "key",
              "type": "LeafletKey",
              "kind": "object",
              "optional": false,
              "list": false,
              "picker": {
                "kinds": [
                  {
                    "kind": "page"
                  }
                ]
              }
            },
            {
              "name": "people",
              "type": "Person",
              "kind": "object",
              "optional": false,
              "list": true,
              "max": 60
            }
          ]
        },
        {
          "name": "SaveDraft",
          "goal": "Keep a roster aside without changing what readers see",
          "role": "Editor",
          "creates": false,
          "on": "RosterPage",
          "destructive": false,
          "attributes": [
            {
              "name": "draft_people",
              "type": "Person",
              "kind": "object",
              "optional": false,
              "list": true,
              "max": 60
            }
          ]
        },
        {
          "name": "PublishDraft",
          "goal": "Make the saved roster what readers see, and clear it",
          "role": "Editor",
          "creates": false,
          "on": "RosterPage",
          "destructive": false,
          "attributes": [],
          "empty": [
            "nothing"
          ]
        },
        {
          "name": "DiscardDraft",
          "goal": "Drop the saved roster and keep what readers see",
          "role": "Editor",
          "creates": false,
          "on": "RosterPage",
          "destructive": true,
          "attributes": [],
          "empty": [
            "nothing"
          ]
        }
      ],
      "queries": [
        {
          "name": "Listing",
          "description": "Every roster page.",
          "attributes": []
        }
      ],
      "drafts": {
        "attribute": "draft_people",
        "live": "people",
        "save": "SaveDraft",
        "publish": "PublishDraft",
        "discard": "DiscardDraft"
      }
    },
    {
      "name": "MediaItem",
      "chapter": "Pictures",
      "description": "A picture that has been uploaded: its record only, the bytes are kept elsewhere.",
      "identity": "key",
      "lifecycle": null,
      "attributes": [
        {
          "name": "key",
          "type": "PictureKey",
          "kind": "object",
          "optional": false,
          "list": false
        },
        {
          "name": "alt",
          "type": "AltText",
          "kind": "object",
          "optional": false,
          "list": false
        },
        {
          "name": "mime_type",
          "type": "MimeType",
          "kind": "object",
          "optional": false,
          "list": false
        }
      ],
      "valueObjects": {
        "PictureKey": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "AltText": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ],
        "MimeType": [
          {
            "name": "value",
            "type": "String",
            "kind": "text",
            "optional": false,
            "list": false
          }
        ]
      },
      "commands": [
        {
          "name": "RegisterPicture",
          "goal": "Record a picture that has been uploaded",
          "role": "Editor",
          "creates": true,
          "on": null,
          "destructive": false,
          "attributes": [
            {
              "name": "key",
              "type": "PictureKey",
              "kind": "object",
              "optional": false,
              "list": false
            },
            {
              "name": "alt",
              "type": "AltText",
              "kind": "object",
              "optional": false,
              "list": false
            },
            {
              "name": "mime_type",
              "type": "MimeType",
              "kind": "object",
              "optional": false,
              "list": false
            }
          ]
        }
      ],
      "queries": [
        {
          "name": "Pictures",
          "description": "Every registered picture.",
          "attributes": []
        }
      ]
    }
  ],
  "media": {
    "aggregate": "MediaItem",
    "command": "RegisterPicture",
    "fields": {
      "key": {
        "name": "key",
        "wrap": "value"
      },
      "alt": {
        "name": "alt",
        "wrap": "value"
      },
      "mime": {
        "name": "mime_type",
        "wrap": "value"
      }
    },
    "listing": "Pictures",
    "domain": "Pictures"
  }
};
