// EXEMPLAR shapes for rust/project/registry.rb — see mod.rs's own header.
// `check_role`/`check_reference` are real kernel functions
// (`rust/src/kernel/repository.rs`); `InMemoryRepository<T>` only
// requires `T: Clone`, so a throwaway `i64` record type is enough to give
// the reference-check hosts a real, compiling `Store`-shaped argument.
#![allow(dead_code, unused_variables)]

// `QUERIES` — a real, always-in-scope const every generated registry.rs/
// merged.rs already defines in the SAME file as `dispatch_by_name`
// (`rust/project/registry.rb`'s own `emit_query_table`, called once per
// chapter and once more over the merged union) — `check_role`'s own
// `caller_actor_id` branch (kernel/repository.rs) needs it to find
// `Governance::RoleAssignment.AssignmentsForActor`, the SAME compiled
// query path a real "query" step already answers through
// (kernel/cli.rs). Empty here — this exemplar proves the CALL SHAPE
// compiles, not any particular domain's own declared queries.
static QUERIES: &[crate::kernel::QueryDef] = &[];

fn tmpl_role_check_host(store: &TmplStore2, caller_role: Option<&str>, caller_actor_id: Option<&str>) -> Result<(), crate::kernel::Refusal> {
    // TMPL:role_check BEGIN
    crate::kernel::check_role(Some("TmplRole"), "TmplCommandName", caller_role, caller_actor_id, &*store, QUERIES)?;
    // TMPL:role_check END
    Ok(())
}

struct TmplStore {
    tmpl_target_mod: crate::kernel::InMemoryRepository<i64>,
}

struct TmplRefArgs {
    tmpl_field: String,
    tmpl_optional_field: Option<String>,
}

fn tmpl_reference_check_required_host(store: &TmplStore, args: &TmplRefArgs) -> Result<(), crate::kernel::Refusal> {
    // TMPL:reference_check_required BEGIN
    crate::kernel::check_reference(&store.tmpl_target_mod, &args.tmpl_field, "TmplTarget", "tmpl_heads")?;
    // TMPL:reference_check_required END
    Ok(())
}

fn tmpl_reference_check_optional_host(store: &TmplStore, args: &TmplRefArgs) -> Result<(), crate::kernel::Refusal> {
    // TMPL:reference_check_optional BEGIN
    if let Some(v) = &args.tmpl_optional_field { crate::kernel::check_reference(&store.tmpl_target_mod, v, "TmplTarget", "tmpl_heads")?; }
    // TMPL:reference_check_optional END
    Ok(())
}

// `registry_file` — the WHOLE per-domain `registry.rs`: `Store`, its
// `new`/`instances`/`from_seed`, the `dispatch_by_name` router, and
// `stamp_payload`. The five variable-arity blocks (`store_fields`,
// `store_inits`, `dump_arms`, `seed_arms`, `dispatch_arms`) stay plain
// Ruby-built opaque markers — the SAME choice `dispatch_fn`'s own
// `given`/`ensures`/mutation blocks already made (commands.rs's own
// header): each is already a proven-correct per-aggregate/per-command
// loop with its own established formatting; what this shape actually
// proves is the fixed STRUCTURE around them — the one `Store`/`impl`/
// `fn` skeleton every domain's registry shares verbatim, doc comments
// included (copied here as fixed text, not regenerated per domain).
fn tmpl_store_fields_placeholder() -> crate::kernel::InMemoryRepository<i64> {
    crate::kernel::InMemoryRepository::new()
}
fn tmpl_dump_arm_placeholder() {}
fn tmpl_seed_arm_placeholder() {}
fn tmpl_query_arm_placeholder() {}
fn tmpl_dispatch_arm_placeholder() -> Result<Vec<crate::kernel::Event>, crate::kernel::Refusal> {
    Ok(Vec::new())
}

// Two harmless `unused_mut` warnings come from THIS exemplar only, not
// real output: `instances`/`store` below genuinely need `mut` once the
// placeholder loop bodies are substituted for real ones that push/save
// into them — an attribute suppressing it here would have to sit INSIDE
// the fence (leaking into every real generated file) to reach the right
// items, so this is left as a documented, deliberate exception rather
// than a real fix. `cargo test --lib`'s own warning count already
// includes dozens of unrelated ones from checked-in generated code; two
// more from a never-shipped exemplar cost nothing real.
//
// The file-level header (the "GENERATED by..." comment, `#![allow(...)]`,
// the `use crate::kernel::Repository;` preamble) is NOT part of this
// fenced shape — a `#![...]` INNER attribute is only legal as the very
// first item of the file/module it applies to, and this exemplar file
// already has its own at the top. That header is fixed, never-varying
// text regardless, the same class of boilerplate `domain_generator.rb`'s
// own `f.puts` calls already write directly for every aggregate file's
// header — `emit_registry` (registry.rb) keeps building it as a plain
// Ruby constant, prepended in front of this shape's own rendered text.
// TMPL:registry_file BEGIN
// `Clone` — a DRY RUN (`cli::run`'s `{"dry_run": …}` step, `cli::serve`'s
// `snapshot`/`restore`) dispatches against a throwaway copy of the whole
// store: givens, mutations, ensures all run for real, nothing is kept.
#[derive(Clone)]
pub struct TmplStore2 {
    pub tmpl_field: crate::kernel::InMemoryRepository<i64>,
}

impl TmplStore2 {
    pub fn new() -> Self {
        Self {
            tmpl_field: tmpl_store_fields_placeholder(),
        }
    }

    /// Every aggregate this domain declared, dumped as
    /// "Domain::Aggregate#id" -> its own to_json() — the exact key
    /// shape bin/rust_conformance's own comparable["instances"]
    /// builds from Ruby (Fuzzing::Replay.call's own instance key
    /// format, read directly).
    pub fn instances(&self) -> Vec<(String, crate::kernel::Json)> {
        let mut instances = Vec::new();
tmpl_dump_arm_placeholder();
        instances
    }

    /// Seeds a fresh `Store` from a prior `instances()` dump —
    /// the exact "Domain::Aggregate#id" -> state shape, read
    /// back instead of written. Not `Result`-returning on a
    /// non-Object `seed`: an absent/malformed seed just yields
    /// an empty Store, the same starting point `Store::new()`
    /// already gives a caller with no prior state to seed from.
    pub fn from_seed(seed: &crate::kernel::Json) -> Result<Self, crate::kernel::Refusal> {
        let mut store = Self::new();
        if let crate::kernel::Json::Object(fields) = seed {
            for (key, value) in fields {
tmpl_seed_arm_placeholder();
            }
        }
        Ok(store)
    }
}

/// `AggregateScan` — kernel/repository.rs's own trait, given a REAL
/// per-aggregate body here: one `if` per aggregate this domain declared,
/// the same "Domain::Aggregate" prefix `instances()`'s own dump arms
/// already use, each returning that ONE aggregate's own (id, to_json())
/// listing straight off its repository's `entries()`. Falls through to
/// the trait's own default (`None`) for any prefix that matches none of
/// them — kernel/cli.rs turns that into a clean "unknown aggregate"
/// refusal, never a panic.
impl crate::kernel::AggregateScan for TmplStore2 {
    fn scan(&self, aggregate: &str) -> Option<Vec<(String, crate::kernel::Json)>> {
tmpl_query_arm_placeholder();
        None
    }
}

pub fn dispatch_by_name(
    store: &mut TmplStore2,
    verb: &str,
    args_json: &crate::kernel::Json,
    caller_role: Option<&str>,
    caller_actor_id: Option<&str>,
    mutations: &mut Vec<crate::kernel::MutationRecord>,
) -> Result<Vec<crate::kernel::Event>, crate::kernel::Refusal> {
    match verb {
"tmpl_verb" => { tmpl_dispatch_arm_placeholder() }
        other => Err(crate::kernel::Refusal::TypeMismatch(format!("unknown command {other:?}"))),
    }
}

/// Ruby's own event payload is `payload: args` — the WHOLE hash the
/// caller passed to `dispatch`, not filtered to the command's own
/// declared attributes (an identity-reference argument like
/// `number:` is not a declared `CreditArgs` field, and still shows
/// up on `AccountCredited`'s payload). `args.to_json()` inside each
/// generated `dispatch_*` only ever sees the NARROWED, typed args
/// struct, so it structurally can't reproduce that — this replaces
/// whatever payload the generated dispatch built with the raw,
/// unfiltered `args_json` this router itself received, after the
/// fact, once dispatch has already decided whether to accept it.
/// Load-bearing for process managers, not just payload fidelity: a
/// saga leg that forwards `reference: :reference` into `Account.
/// Debit` (which doesn't declare a `reference` attribute) needs
/// that field to survive onto `AccountDebited`'s own payload for
/// `correlates_by` to find it downstream.
fn stamp_payload(events: Vec<crate::kernel::Event>, args_json: &crate::kernel::Json) -> Vec<crate::kernel::Event> {
    events.into_iter().map(|e| crate::kernel::Event { payload: args_json.clone(), ..e }).collect()
}
// TMPL:registry_file END
