// HAND-WRITTEN, ON PURPOSE — the small floor every generated per-command
// function calls into. It knows nothing about Order, PizzaCreated, or any
// other domain-specific name; everything domain-specific lives in
// src/generated/, produced by bin/project_rust from canonical IR. Every
// fact below is cited against docs/implemented/guides/running-a-runtime.md and
// docs/implemented/guides/commands.md, not guessed or half-remembered from a prior
// read of the Ruby source.

pub mod attribute_shapes;
pub mod cli;
pub mod dispatch;
pub mod expr;
pub mod expression_operators;
pub mod json;
// `named_query` — a NAMED/declared bluebook `query "X" do ... end` block,
// for the subset of that construct real generated Rust now answers for
// real. See that module's own header for the full scope argument; the
// short version is `query_comparators.rs`'s own header on what the ad hoc
// OBJECT-shaped "query" step covers, one level up: same eight comparators,
// same `filter_entries`/`AggregateScan` machinery, now with a DECLARED
// query's own conditions baked in by a generator instead of supplied ad
// hoc over the wire.
pub mod named_query;
pub mod orchestrate;
pub mod pattern;
// `query_ordering` — the identity-sort/declared-order/limit TAIL shared by
// a declared AGGREGATE query's own `order_by`/`limit` (`named_query.rs`)
// and a read model's eligible-head `order_by`/`limit` (`read_model.rs`).
// Extracted from `read_model.rs` (2026-08-11) the moment a second caller
// needed the identical logic — see that module's own header for the full
// ground-truth citation and ONE genuine structural difference between the
// two callers (a read model's `filtered_head` selection, which happens
// above this module, never inside it).
pub mod query_ordering;
// `refusal_wording` — `RefusalSite`, the language-level refusal-template
// table (`Hecks::Runtime::RefusalWording::TEMPLATES`), generated by
// bin/project_refusal_wording — see that script's own header for the full
// ground-truth argument and why it's a sibling to bin/project_kernel_
// capabilities rather than an extension of it.
pub mod refusal_wording;
// `read_model` — a declared bluebook `report "X" do ... end` block
// (`IR::ReadModel`), for the subset real generated Rust now answers for
// real: a root aggregate fetched by reference id, plus reference-matched
// sibling heads. See that module's own header for the full scope
// argument, including why `where`/`order_by`/`limit` specifically stay
// structurally out of reach (not merely unported) for any read model.
pub mod read_model;
// `QueryComparator` — closed, and now dispatched for real, for exactly
// ONE slice of the query engine: `cli.rs`'s ad hoc, single-comparator
// "query" step (the OBJECT form). See query_comparators.rs's own header
// for the full story, including what it does NOT cover (a NAMED/declared
// bluebook query, the STRING form of the same step — still refused, on
// purpose, a separate and much bigger gap). No longer regenerated by
// bin/project_kernel_capabilities — see that script's own header for
// where that decision is made.
pub mod query_comparators;
pub mod reference_lookup;
pub mod repository;
pub mod routing;

pub use dispatch::{apply_entity_command, dispatch, dispatch_entity, enforce_invariants, EnsuresSpec, EntityInvariants, GivenSpec, Hydrate, InvariantSet, InvariantSpec, TransitionCheck};
pub use expr::{interpret, BlockMode, Bound, Comparison, EvalContext, Expr, Field, Fielded, NoFields, Value, WithParent};
pub use json::Json;
pub use named_query::{QueryCondition, QueryConditionValue, QueryDef};
pub use orchestrate::{
    orchestrate, CompletedCompensation, CrossDomainPolicyRule, DispatchSpec, Handler, PendingCrossDomainReaction, PolicyRule, ProcessManagerDef,
    SagaInstance, Tables, WithValue, MAX_REACTION_DEPTH, REFUSED,
};
pub use reference_lookup::{
    command_deref, owner_deref, parent_deref, seeded_projections, DerefNode, ProjectedFieldSpec, ReferenceLookup, ReferenceSpec, ReferenceTable,
    SetProjectedField, WithReferences, DEREFERENCE_DEPTH,
};
pub use refusal_wording::RefusalSite;
pub use repository::{check_reference, check_role, filter_entries, row_json, AggregateScan, InMemoryRepository, Repository};
pub use routing::{CommandInvocation, RoutingEnvelope};

#[derive(Debug, Clone)]
pub struct Event {
    pub name: String,
    pub aggregate: String,
    pub id: String,
    /// Mirrors Ruby's `payload: args` (running-a-runtime.md's "Commands: the
    /// roster and what each key means" section — `emits` is the plain list
    /// of event names a successful dispatch raises; the payload shape
    /// itself is `Runtime::CommandRules::Emission#emit`, read directly) —
    /// the dispatching command's own `args.to_json()`, structurally, not a
    /// debug-formatted string dump (that was this kernel's shape before
    /// policies/process managers needed to actually forward payload DATA
    /// into a re-triggered command's own `from_json`, not just print it).
    pub payload: json::Json,
    /// `Runtime::CommandRules::Emission#emit`'s own bare `Time.now.utc.
    /// iso8601` (lib/hecks/runtime/command_rules/emission.rb) — NOT the
    /// declared `Clock` port (`lib/hecks/ports/clock.rb`), a genuinely
    /// separate mechanism that stamps a `given` predicate's own `now`
    /// argument at the dispatch door (so a replayed step keeps judging
    /// the SAME baked-in time forever, never today's), the wrong shape
    /// for a plain record of when something actually happened —
    /// `docs/HECKS_IMPLEMENTATION_PLAN.md:764-767` names this event
    /// timestamp its own "environmental fact... precedent," deliberately
    /// exempt from that port's own replay concern: nothing re-JUDGES an
    /// already-emitted event's own `occurred_at` on a later run the way
    /// a `given` re-evaluates its own `now`. This kernel has no clock of
    /// its own —
    /// staying deterministic (this file's own header) means it NEVER
    /// calls one — so `orchestrate` receives this as an already-resolved
    /// string, exactly the same shape `saga_correlation`, below, already
    /// arrives in: `rust/host` (a real wall clock) stamps ONE timestamp
    /// per top-level step onto every event that step's own dispatch
    /// produces, INCLUDING every cascading policy/saga reaction it
    /// triggers within the same synchronous call — not a fresh `Time.now`
    /// per individual event the way Ruby's own bare call is. `None`
    /// inside the kernel's own generated `dispatch_by_name` (every real
    /// construction site) until `orchestrate`'s own stamping loop fills
    /// it in; `None` forever for a caller (`hecks-parse`'s own `chapter`
    /// command, the differential-parity harness) that never passes one
    /// at all, matching the same reasoning `caller_role: None` already
    /// has for a context with no real caller identity.
    pub occurred_at: Option<String>,
    /// Runtime-only bookkeeping, NEVER serialized — `cli.rs`'s own
    /// `event_to_json` deliberately excludes it, mirroring Ruby's own
    /// `Event#to_h` (event.rb: "`correlation` is NOT on the wire"). Stamped
    /// by `orchestrate` (`saga_correlation` parameter) exactly where
    /// `Dispatcher#dispatch` stamps it — `announced.each { (event.
    /// correlation ||= {}).merge!(saga_correlation) }` — when a saga leg's
    /// own dispatch causes this event (`SagaInterpreter#deliver_saga_
    /// dispatch`'s own `saga_correlation:` argument). `correlation_head`
    /// (`pm.correlates_by.split(".").first`) -> the correlating value, so
    /// an event caused by one saga cannot be misread by an unrelated one
    /// correlating on a different field — `Correlation#saga_correlation`'s
    /// own middle tier (orchestrate.rs's `correlation_of`) reads it back.
    /// `None` for any event no saga dispatch caused, which is most of them.
    pub correlation: Option<std::collections::HashMap<String, String>>,
}

/// The complete refusal roster for a command dispatch, per
/// docs/implemented/guides/commands.md's own table (quoted there as "the complete
/// roster" — not a subset picked for this slice). One Ruby DOMAIN_REFUSALS
/// class is deliberately NOT here: `UnknownVerb` (dispatching a command
/// name that doesn't exist at all is a router-level concern, not
/// something one generated dispatch function raises about itself).
/// `Unauthorized` (role-mismatch) WAS in that deliberately-absent list —
/// see `check_role` (repository.rs) and 0019 for how it's generated now.
///
/// `AbsentArgument`/`UnknownArgument` ARE variants here, but only ever
/// raised at the JSON boundary (`from_json`, `rust/project/json_codec.rb`'s
/// `emit_unknown_argument_check`), never by a generated `dispatch_*`
/// function itself: a TYPED args struct still makes both structurally
/// impossible to construct once `from_json` has already succeeded — the
/// gap this refusal closes is that `from_json`'s own JSON input has no
/// static shape at all, exactly the reason Ruby needs a runtime check on
/// its own argument hash. `AbsentArgument` is mostly redundant with the
/// existing `v.require(...)` failures inside `from_json` (both refuse a
/// missing required field; this variant exists for a caller who wants to
/// distinguish "missing" from "wrong shape" by refusal KIND, not just
/// wording) — `UnknownArgument` is the one that closed a real gap: nothing
/// checked for an EXTRA key before this.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Refusal {
    GivenNotMet(String),
    EnsuresNotMet(String),
    InvariantViolation(String),
    LifecycleRefused(String),
    AlreadyExists(String),
    NotFound(String),
    TypeMismatch(String),
    AbsentArgument(String),
    UnknownArgument(String),
    Unauthorized(String),
    Fault(String),
    /// `corrects` against a record that never emitted the corrected event
    /// — `Runtime::NothingToCorrect` (C9.2), its own class, not a
    /// `GivenNotMet` wearing that wording.
    NothingToCorrect(String),
}

impl Refusal {
    /// The refusal CLASS, spelled exactly as Ruby raises it — the
    /// semantics corpus compares this beside the message, because
    /// "refused" alone under-specifies the outcome (docs/semantics/
    /// bluebook-semantics.md, Outcomes).
    pub fn kind(&self) -> &'static str {
        match self {
            Refusal::GivenNotMet(_) => "GivenNotMet",
            Refusal::EnsuresNotMet(_) => "EnsuresNotMet",
            Refusal::InvariantViolation(_) => "InvariantViolation",
            Refusal::LifecycleRefused(_) => "LifecycleRefused",
            Refusal::AlreadyExists(_) => "AlreadyExists",
            Refusal::NotFound(_) => "NotFound",
            Refusal::TypeMismatch(_) => "TypeMismatch",
            Refusal::AbsentArgument(_) => "AbsentArgument",
            Refusal::UnknownArgument(_) => "UnknownArgument",
            Refusal::Unauthorized(_) => "Unauthorized",
            Refusal::Fault(_) => "Fault",
            Refusal::NothingToCorrect(_) => "NothingToCorrect",
        }
    }
}

impl std::fmt::Display for Refusal {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Refusal::GivenNotMet(msg)
            | Refusal::EnsuresNotMet(msg)
            | Refusal::InvariantViolation(msg)
            | Refusal::LifecycleRefused(msg)
            | Refusal::AlreadyExists(msg)
            | Refusal::NotFound(msg)
            | Refusal::TypeMismatch(msg)
            | Refusal::AbsentArgument(msg)
            | Refusal::UnknownArgument(msg)
            | Refusal::Unauthorized(msg)
            | Refusal::Fault(msg)
            | Refusal::NothingToCorrect(msg) => write!(f, "{msg}"),
        }
    }
}

/// Mirrors `CommandInterpreter#call`'s own return shape: `[ctx.instance,
/// ctx.result]`, where `ctx.result` is built from `emit` — a record plus
/// whatever events actually fired, or a refusal with no record and no
/// events at all ("Refusals leave state untouched", commands.md's own
/// closing section).
pub type DispatchResult<T> = Result<(T, Vec<Event>), Refusal>;

/// One aggregate record just saved by a command's own dispatch (top-level
/// or a cascaded policy/saga-leg re-entry) — pushed at the exact same call
/// site `repo.save` runs, in `dispatch`/`dispatch_entity` (dispatch.rs).
/// Exists so a HOST (rust/host, which only ever sees this kernel as an
/// opaque stdin/stdout process — docs/implemented/decisions/0012) can build a
/// per-aggregate journal matching postgres.rb's own shape (`era, aggregate,
/// aggregate_id, operation, state`) without needing per-command insight
/// into the domain itself — `cli.rs` reports one `Vec<MutationRecord>` per
/// step, parallel to `"steps"`, in its `"mutations"` output field.
///
/// `operation` is always `"save"` today — no generated dispatch path ever
/// calls `Repository::delete` (that method doesn't even exist on the trait
/// — see repository.rs). Add a `"delete"` variant here if that ever
/// changes; not built now because nothing exercises it.
#[derive(Debug, Clone)]
pub struct MutationRecord {
    pub aggregate: String,
    pub id: String,
    pub operation: &'static str,
    pub state: Json,
}

/// Generic access to a generated struct's own `to_json()` — every
/// generated record already has this as an INHERENT method
/// (`rust/project/json_codec.rb`'s `emit_to_json_flat`); this trait exists
/// only so `dispatch`/`dispatch_entity` (dispatch.rs), generic over the
/// record type `T`, can call it without knowing the concrete type. Ruby's
/// `record.to_json()`-in-a-loop equivalent, made possible in Rust only
/// through a trait bound. Implemented per aggregate record struct by
/// `domain_generator.rb`, delegating straight to the inherent method — see
/// its own comment on why only aggregate records (never value objects,
/// entities, or Args structs) need it: `dispatch`/`dispatch_entity`'s
/// generic `T` is always the aggregate record type.
pub trait ToJson {
    fn to_json(&self) -> Json;
}
