# frozen_string_literal: true

module Hecks
  module ProjectionFiles
    # The Rust text of the generated `reserved_names.rs` and `field_hints.rs`. Extended onto
    # `ProjectionFiles`.
    module Texts
      # The whole `reserved_names.rs`, with its constants where `%<consts>s` stands.
      RESERVED_NAMES = <<~RUST
        // GENERATED by hecks project_reserved_names from the RustReservedWord and
        // CargoReservedName vocabularies (lib/hecks/language/bluebook/
        // vocabulary.bluebook). Do not hand-edit — re-run hecks project_reserved_names.

        %<consts>s
      RUST

      # The whole `field_hints.rs`, with its statics where `%<consts>s` stands.
      FIELD_HINTS = <<~RUST
        // GENERATED by hecks project_field_hints from Vocabulary::FieldHint
        // (lib/hecks/language/bluebook/vocabulary.bluebook). Do not
        // hand-edit — re-run hecks project_field_hints instead.
        //
        // web.rs's `text_field` matches these in the SAME precedence Ruby's
        // own `text_field` does: EMAIL_HINT, then URL_HINT, then TEL_HINT —
        // against `html_type`, first match wins — then, only if `html_type`
        // stayed "text", TEXTAREA_HINT against `kind`.

        use regex::Regex;
        use std::sync::LazyLock;

        %<consts>s
      RUST

      # One hint's `static`.
      FIELD_HINT = <<~RUST
        /// %<title>s hint, resolving to `%<resolves_to>s` on a match —
        /// Vocabulary::FieldHint's own declared pattern, unmodified (the
        /// same text `Regexp#source` reads off FieldShape's own
        /// %<name>s, which is built from this same row).
        /// `(?i)` up front is this crate's spelling
        /// of Ruby's trailing `/i` — the WHOLE pattern is case-insensitive
        /// on both sides, never partially.
        pub static %<name>s: LazyLock<Regex> =
            LazyLock::new(|| Regex::new(r#"(?i)%<pattern>s"#).expect("declared field-hint pattern must compile"));
      RUST

      # @param consts [Array<String>] the rendered Rust constants
      # @return [String] the whole `reserved_names.rs`
      def reserved_names_text(consts)
        format(RESERVED_NAMES, consts: consts.join("\n\n"))
      end

      # @param hints [Array<Hash>] the rows of `Vocabulary::FieldHint`
      # @return [String] the whole `field_hints.rs`
      def field_hints_text(hints)
        format(FIELD_HINTS, consts: hints.map { |hint| field_hint_constant(hint) }.join("\n"))
      end

      # @param hint [Hash] one `FieldHint` row: its name, pattern and what it resolves to
      # @return [String] the Rust `static` for it
      def field_hint_constant(hint)
        format(FIELD_HINT, title: hint[:name].capitalize, resolves_to: hint[:resolves_to],
                           name: "#{hint[:name].upcase}_HINT", pattern: hint[:pattern])
      end
    end
  end
end
