// GENERATED by bin/project_rust_vocabulary (Hecks::Projections::RustVocabulary,
// lib/hecks/projections/rust_vocabulary.rb) from Vocabulary::AggregateDispatchOrder
// (lib/hecks/language/bluebook/vocabulary.bluebook).
// Do not hand-edit — re-run bin/project_rust_vocabulary instead.

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AggregateStep {
    RefuseUnknownArguments,
    RefuseAbsentArguments,
    NormalizeArgs,
    RefuseRoleMismatch,
    ResolveReferences,
    Hydrate,
    EnforceGivens,
    AdmissibleTransition,
    AssignCreationAttributes,
    ApplyMutations,
    AdvanceLifecycle,
    DelegateToEntity,
    EnforceEnsures,
    EnforceInvariants,
    Save,
    Emit,
}

impl AggregateStep {
    /// The declared step order, first to last.
    pub const ORDER: [AggregateStep; 16] = [
        AggregateStep::RefuseUnknownArguments,
        AggregateStep::RefuseAbsentArguments,
        AggregateStep::NormalizeArgs,
        AggregateStep::RefuseRoleMismatch,
        AggregateStep::ResolveReferences,
        AggregateStep::Hydrate,
        AggregateStep::EnforceGivens,
        AggregateStep::AdmissibleTransition,
        AggregateStep::AssignCreationAttributes,
        AggregateStep::ApplyMutations,
        AggregateStep::AdvanceLifecycle,
        AggregateStep::DelegateToEntity,
        AggregateStep::EnforceEnsures,
        AggregateStep::EnforceInvariants,
        AggregateStep::Save,
        AggregateStep::Emit,
    ];

    /// The row's declared `step`.
    pub fn step(&self) -> &'static str {
        match self {
            AggregateStep::RefuseUnknownArguments => "refuse_unknown_arguments",
            AggregateStep::RefuseAbsentArguments => "refuse_absent_arguments",
            AggregateStep::NormalizeArgs => "normalize_args",
            AggregateStep::RefuseRoleMismatch => "refuse_role_mismatch",
            AggregateStep::ResolveReferences => "resolve_references",
            AggregateStep::Hydrate => "hydrate",
            AggregateStep::EnforceGivens => "enforce_givens",
            AggregateStep::AdmissibleTransition => "admissible_transition",
            AggregateStep::AssignCreationAttributes => "assign_creation_attributes",
            AggregateStep::ApplyMutations => "apply_mutations",
            AggregateStep::AdvanceLifecycle => "advance_lifecycle",
            AggregateStep::DelegateToEntity => "delegate_to_entity",
            AggregateStep::EnforceEnsures => "enforce_ensures",
            AggregateStep::EnforceInvariants => "enforce_invariants",
            AggregateStep::Save => "save",
            AggregateStep::Emit => "emit",
        }
    }

    /// The row whose `step` is `name`, if any.
    pub fn from_name(name: &str) -> Option<AggregateStep> {
        AggregateStep::ORDER.iter().copied().find(|row| row.step() == name)
    }

    /// This step's index in `ORDER`.
    pub fn position(&self) -> usize {
        match self {
            AggregateStep::RefuseUnknownArguments => 0,
            AggregateStep::RefuseAbsentArguments => 1,
            AggregateStep::NormalizeArgs => 2,
            AggregateStep::RefuseRoleMismatch => 3,
            AggregateStep::ResolveReferences => 4,
            AggregateStep::Hydrate => 5,
            AggregateStep::EnforceGivens => 6,
            AggregateStep::AdmissibleTransition => 7,
            AggregateStep::AssignCreationAttributes => 8,
            AggregateStep::ApplyMutations => 9,
            AggregateStep::AdvanceLifecycle => 10,
            AggregateStep::DelegateToEntity => 11,
            AggregateStep::EnforceEnsures => 12,
            AggregateStep::EnforceInvariants => 13,
            AggregateStep::Save => 14,
            AggregateStep::Emit => 15,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_row_is_found_by_its_own_name() {
        for row in AggregateStep::ORDER.iter() {
            assert_eq!(AggregateStep::from_name(row.step()), Some(*row));
        }
    }

    #[test]
    fn position_is_the_index_in_order() {
        for (index, step) in AggregateStep::ORDER.iter().enumerate() {
            assert_eq!(step.position(), index);
        }
    }
}
