// GENERATED by bin/project_rust_vocabulary (Hecks::Projections::RustVocabulary,
// lib/hecks/projections/rust_vocabulary.rb) from Vocabulary::EntityDispatchOrder
// (lib/hecks/language/bluebook/vocabulary.bluebook).
// Do not hand-edit — re-run bin/project_rust_vocabulary instead.

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum EntityStep {
    DecodeArguments,
    RefuseUnknownArguments,
    RefuseAbsentArguments,
    NormalizeArgs,
    RefuseRoleMismatch,
    ResolveReferences,
    HydrateParent,
    LocateElement,
    EnforceGivens,
    AdmissibleTransition,
    ApplyMutations,
    AdvanceLifecycle,
    EnforceEnsures,
    EnforceInvariants,
    Save,
    Emit,
}

impl EntityStep {
    /// The declared step order, first to last.
    pub const ORDER: [EntityStep; 16] = [
        EntityStep::DecodeArguments,
        EntityStep::RefuseUnknownArguments,
        EntityStep::RefuseAbsentArguments,
        EntityStep::NormalizeArgs,
        EntityStep::RefuseRoleMismatch,
        EntityStep::ResolveReferences,
        EntityStep::HydrateParent,
        EntityStep::LocateElement,
        EntityStep::EnforceGivens,
        EntityStep::AdmissibleTransition,
        EntityStep::ApplyMutations,
        EntityStep::AdvanceLifecycle,
        EntityStep::EnforceEnsures,
        EntityStep::EnforceInvariants,
        EntityStep::Save,
        EntityStep::Emit,
    ];

    /// The row's declared `step`.
    pub fn step(&self) -> &'static str {
        match self {
            EntityStep::DecodeArguments => "decode_arguments",
            EntityStep::RefuseUnknownArguments => "refuse_unknown_arguments",
            EntityStep::RefuseAbsentArguments => "refuse_absent_arguments",
            EntityStep::NormalizeArgs => "normalize_args",
            EntityStep::RefuseRoleMismatch => "refuse_role_mismatch",
            EntityStep::ResolveReferences => "resolve_references",
            EntityStep::HydrateParent => "hydrate_parent",
            EntityStep::LocateElement => "locate_element",
            EntityStep::EnforceGivens => "enforce_givens",
            EntityStep::AdmissibleTransition => "admissible_transition",
            EntityStep::ApplyMutations => "apply_mutations",
            EntityStep::AdvanceLifecycle => "advance_lifecycle",
            EntityStep::EnforceEnsures => "enforce_ensures",
            EntityStep::EnforceInvariants => "enforce_invariants",
            EntityStep::Save => "save",
            EntityStep::Emit => "emit",
        }
    }

    /// The row whose `step` is `name`, if any.
    pub fn from_name(name: &str) -> Option<EntityStep> {
        EntityStep::ORDER.iter().copied().find(|row| row.step() == name)
    }

    /// This step's index in `ORDER`.
    pub fn position(&self) -> usize {
        match self {
            EntityStep::DecodeArguments => 0,
            EntityStep::RefuseUnknownArguments => 1,
            EntityStep::RefuseAbsentArguments => 2,
            EntityStep::NormalizeArgs => 3,
            EntityStep::RefuseRoleMismatch => 4,
            EntityStep::ResolveReferences => 5,
            EntityStep::HydrateParent => 6,
            EntityStep::LocateElement => 7,
            EntityStep::EnforceGivens => 8,
            EntityStep::AdmissibleTransition => 9,
            EntityStep::ApplyMutations => 10,
            EntityStep::AdvanceLifecycle => 11,
            EntityStep::EnforceEnsures => 12,
            EntityStep::EnforceInvariants => 13,
            EntityStep::Save => 14,
            EntityStep::Emit => 15,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_row_is_found_by_its_own_name() {
        for row in EntityStep::ORDER.iter() {
            assert_eq!(EntityStep::from_name(row.step()), Some(*row));
        }
    }

    #[test]
    fn position_is_the_index_in_order() {
        for (index, step) in EntityStep::ORDER.iter().enumerate() {
            assert_eq!(step.position(), index);
        }
    }
}
