// GENERATED by bin/project_rust_vocabulary (Hecks::Projections::RustVocabulary,
// lib/hecks/projections/rust_vocabulary.rb) from the Vocabulary
// aggregate (lib/hecks/language/bluebook/vocabulary.bluebook).
// Do not hand-edit — re-run bin/project_rust_vocabulary instead.
//
// One module per projected table. Every enum below is matched
// exhaustively by its own accessors — no wildcard arm — so a row the
// language gains fails to compile until it is handled.

pub mod refusal_template;
pub mod query_comparator;
pub mod field_hint;
pub mod aggregate_dispatch_order;
pub mod entity_dispatch_order;

pub use refusal_template::RefusalSite;
pub use query_comparator::QueryComparator;
pub use field_hint::FieldHint;
pub use aggregate_dispatch_order::AggregateStep;
pub use entity_dispatch_order::EntityStep;
