// GENERATED by bin/project_rust_vocabulary (Hecks::Projections::RustVocabulary,
// lib/hecks/projections/rust_vocabulary.rb) from Vocabulary::RefusalTemplate
// (lib/hecks/language/bluebook/vocabulary.bluebook).
// Do not hand-edit — re-run bin/project_rust_vocabulary instead.

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum RefusalSite {
    NotFoundCreatingNoIdentity,
    AlreadyExistsCreatingDuplicate,
    AlreadyExistsEntityDuplicate,
    NotFoundActingNoIdentity,
    NotFoundRecordMissing,
    NotFoundEntityParentNoIdentity,
    UnknownVerbEntityUnknown,
    NotFoundEntityElementNoIdentity,
    NotFoundEntityElementMissing,
    NotFoundReferenceTargetMissing,
    NotFoundReadModelReferenceMissing,
    TypeMismatchReadModelObjectReference,
    UnknownVerbNoQuery,
    UnknownVerbEntityQueryMissing,
    UnknownVerbEntityHoldsNoList,
    UnknownVerbEntityNoCommand,
    UnknownVerbAggregateNoCommand,
    UnknownVerbPortNoOperation,
    UnknownVerbNoDomain,
    UnknownVerbNoReadModel,
    UnknownVerbNotFullyQualified,
    UnknownVerbNoAggregate,
    LifecycleRefusedTransitionBlocked,
    TypeMismatchValueObjectShape,
    TypeMismatchReferenceWrongShape,
    TypeMismatchMultiFieldScalar,
    TypeMismatchCompositeIdentity,
    TypeMismatchNumericField,
    TypeMismatchNonFiniteField,
    TypeMismatchIntegerRange,
    TypeMismatchPatternMismatch,
    TypeMismatchArithmeticAmount,
    TypeMismatchArithmeticCurrent,
    TypeMismatchArithmeticSharedField,
    UnknownArgumentUnknownArgs,
    AbsentArgumentAbsentArgs,
    InvariantViolationClosedSetMember,
    InvariantViolationValueObjectInvariant,
    InvariantViolationAdmitsDeclaredSet,
    InvariantViolationUndeclaredSet,
    UnauthorizedTenantRequired,
    UnauthorizedRoleMismatch,
    UnauthorizedCrossTenantReference,
    AttributeAbsentAbsentRead,
    ProjectionAbsentAbsentRead,
}

impl RefusalSite {
    /// Every row, in declared order.
    pub const ALL: &'static [RefusalSite] = &[
        RefusalSite::NotFoundCreatingNoIdentity,
        RefusalSite::AlreadyExistsCreatingDuplicate,
        RefusalSite::AlreadyExistsEntityDuplicate,
        RefusalSite::NotFoundActingNoIdentity,
        RefusalSite::NotFoundRecordMissing,
        RefusalSite::NotFoundEntityParentNoIdentity,
        RefusalSite::UnknownVerbEntityUnknown,
        RefusalSite::NotFoundEntityElementNoIdentity,
        RefusalSite::NotFoundEntityElementMissing,
        RefusalSite::NotFoundReferenceTargetMissing,
        RefusalSite::NotFoundReadModelReferenceMissing,
        RefusalSite::TypeMismatchReadModelObjectReference,
        RefusalSite::UnknownVerbNoQuery,
        RefusalSite::UnknownVerbEntityQueryMissing,
        RefusalSite::UnknownVerbEntityHoldsNoList,
        RefusalSite::UnknownVerbEntityNoCommand,
        RefusalSite::UnknownVerbAggregateNoCommand,
        RefusalSite::UnknownVerbPortNoOperation,
        RefusalSite::UnknownVerbNoDomain,
        RefusalSite::UnknownVerbNoReadModel,
        RefusalSite::UnknownVerbNotFullyQualified,
        RefusalSite::UnknownVerbNoAggregate,
        RefusalSite::LifecycleRefusedTransitionBlocked,
        RefusalSite::TypeMismatchValueObjectShape,
        RefusalSite::TypeMismatchReferenceWrongShape,
        RefusalSite::TypeMismatchMultiFieldScalar,
        RefusalSite::TypeMismatchCompositeIdentity,
        RefusalSite::TypeMismatchNumericField,
        RefusalSite::TypeMismatchNonFiniteField,
        RefusalSite::TypeMismatchIntegerRange,
        RefusalSite::TypeMismatchPatternMismatch,
        RefusalSite::TypeMismatchArithmeticAmount,
        RefusalSite::TypeMismatchArithmeticCurrent,
        RefusalSite::TypeMismatchArithmeticSharedField,
        RefusalSite::UnknownArgumentUnknownArgs,
        RefusalSite::AbsentArgumentAbsentArgs,
        RefusalSite::InvariantViolationClosedSetMember,
        RefusalSite::InvariantViolationValueObjectInvariant,
        RefusalSite::InvariantViolationAdmitsDeclaredSet,
        RefusalSite::InvariantViolationUndeclaredSet,
        RefusalSite::UnauthorizedTenantRequired,
        RefusalSite::UnauthorizedRoleMismatch,
        RefusalSite::UnauthorizedCrossTenantReference,
        RefusalSite::AttributeAbsentAbsentRead,
        RefusalSite::ProjectionAbsentAbsentRead,
    ];

    /// The row's declared `refusal`.
    pub fn refusal_class(&self) -> &'static str {
        match self {
            RefusalSite::NotFoundCreatingNoIdentity => "NotFound",
            RefusalSite::AlreadyExistsCreatingDuplicate => "AlreadyExists",
            RefusalSite::AlreadyExistsEntityDuplicate => "AlreadyExists",
            RefusalSite::NotFoundActingNoIdentity => "NotFound",
            RefusalSite::NotFoundRecordMissing => "NotFound",
            RefusalSite::NotFoundEntityParentNoIdentity => "NotFound",
            RefusalSite::UnknownVerbEntityUnknown => "UnknownVerb",
            RefusalSite::NotFoundEntityElementNoIdentity => "NotFound",
            RefusalSite::NotFoundEntityElementMissing => "NotFound",
            RefusalSite::NotFoundReferenceTargetMissing => "NotFound",
            RefusalSite::NotFoundReadModelReferenceMissing => "NotFound",
            RefusalSite::TypeMismatchReadModelObjectReference => "TypeMismatch",
            RefusalSite::UnknownVerbNoQuery => "UnknownVerb",
            RefusalSite::UnknownVerbEntityQueryMissing => "UnknownVerb",
            RefusalSite::UnknownVerbEntityHoldsNoList => "UnknownVerb",
            RefusalSite::UnknownVerbEntityNoCommand => "UnknownVerb",
            RefusalSite::UnknownVerbAggregateNoCommand => "UnknownVerb",
            RefusalSite::UnknownVerbPortNoOperation => "UnknownVerb",
            RefusalSite::UnknownVerbNoDomain => "UnknownVerb",
            RefusalSite::UnknownVerbNoReadModel => "UnknownVerb",
            RefusalSite::UnknownVerbNotFullyQualified => "UnknownVerb",
            RefusalSite::UnknownVerbNoAggregate => "UnknownVerb",
            RefusalSite::LifecycleRefusedTransitionBlocked => "LifecycleRefused",
            RefusalSite::TypeMismatchValueObjectShape => "TypeMismatch",
            RefusalSite::TypeMismatchReferenceWrongShape => "TypeMismatch",
            RefusalSite::TypeMismatchMultiFieldScalar => "TypeMismatch",
            RefusalSite::TypeMismatchCompositeIdentity => "TypeMismatch",
            RefusalSite::TypeMismatchNumericField => "TypeMismatch",
            RefusalSite::TypeMismatchNonFiniteField => "TypeMismatch",
            RefusalSite::TypeMismatchIntegerRange => "TypeMismatch",
            RefusalSite::TypeMismatchPatternMismatch => "TypeMismatch",
            RefusalSite::TypeMismatchArithmeticAmount => "TypeMismatch",
            RefusalSite::TypeMismatchArithmeticCurrent => "TypeMismatch",
            RefusalSite::TypeMismatchArithmeticSharedField => "TypeMismatch",
            RefusalSite::UnknownArgumentUnknownArgs => "UnknownArgument",
            RefusalSite::AbsentArgumentAbsentArgs => "AbsentArgument",
            RefusalSite::InvariantViolationClosedSetMember => "InvariantViolation",
            RefusalSite::InvariantViolationValueObjectInvariant => "InvariantViolation",
            RefusalSite::InvariantViolationAdmitsDeclaredSet => "InvariantViolation",
            RefusalSite::InvariantViolationUndeclaredSet => "InvariantViolation",
            RefusalSite::UnauthorizedTenantRequired => "Unauthorized",
            RefusalSite::UnauthorizedRoleMismatch => "Unauthorized",
            RefusalSite::UnauthorizedCrossTenantReference => "Unauthorized",
            RefusalSite::AttributeAbsentAbsentRead => "AttributeAbsent",
            RefusalSite::ProjectionAbsentAbsentRead => "ProjectionAbsent",
        }
    }

    /// The row's declared `site`.
    pub fn site(&self) -> &'static str {
        match self {
            RefusalSite::NotFoundCreatingNoIdentity => "creating_no_identity",
            RefusalSite::AlreadyExistsCreatingDuplicate => "creating_duplicate",
            RefusalSite::AlreadyExistsEntityDuplicate => "entity_duplicate",
            RefusalSite::NotFoundActingNoIdentity => "acting_no_identity",
            RefusalSite::NotFoundRecordMissing => "record_missing",
            RefusalSite::NotFoundEntityParentNoIdentity => "entity_parent_no_identity",
            RefusalSite::UnknownVerbEntityUnknown => "entity_unknown",
            RefusalSite::NotFoundEntityElementNoIdentity => "entity_element_no_identity",
            RefusalSite::NotFoundEntityElementMissing => "entity_element_missing",
            RefusalSite::NotFoundReferenceTargetMissing => "reference_target_missing",
            RefusalSite::NotFoundReadModelReferenceMissing => "read_model_reference_missing",
            RefusalSite::TypeMismatchReadModelObjectReference => "read_model_object_reference",
            RefusalSite::UnknownVerbNoQuery => "no_query",
            RefusalSite::UnknownVerbEntityQueryMissing => "entity_query_missing",
            RefusalSite::UnknownVerbEntityHoldsNoList => "entity_holds_no_list",
            RefusalSite::UnknownVerbEntityNoCommand => "entity_no_command",
            RefusalSite::UnknownVerbAggregateNoCommand => "aggregate_no_command",
            RefusalSite::UnknownVerbPortNoOperation => "port_no_operation",
            RefusalSite::UnknownVerbNoDomain => "no_domain",
            RefusalSite::UnknownVerbNoReadModel => "no_read_model",
            RefusalSite::UnknownVerbNotFullyQualified => "not_fully_qualified",
            RefusalSite::UnknownVerbNoAggregate => "no_aggregate",
            RefusalSite::LifecycleRefusedTransitionBlocked => "transition_blocked",
            RefusalSite::TypeMismatchValueObjectShape => "value_object_shape",
            RefusalSite::TypeMismatchReferenceWrongShape => "reference_wrong_shape",
            RefusalSite::TypeMismatchMultiFieldScalar => "multi_field_scalar",
            RefusalSite::TypeMismatchCompositeIdentity => "composite_identity",
            RefusalSite::TypeMismatchNumericField => "numeric_field",
            RefusalSite::TypeMismatchNonFiniteField => "non_finite_field",
            RefusalSite::TypeMismatchIntegerRange => "integer_range",
            RefusalSite::TypeMismatchPatternMismatch => "pattern_mismatch",
            RefusalSite::TypeMismatchArithmeticAmount => "arithmetic_amount",
            RefusalSite::TypeMismatchArithmeticCurrent => "arithmetic_current",
            RefusalSite::TypeMismatchArithmeticSharedField => "arithmetic_shared_field",
            RefusalSite::UnknownArgumentUnknownArgs => "unknown_args",
            RefusalSite::AbsentArgumentAbsentArgs => "absent_args",
            RefusalSite::InvariantViolationClosedSetMember => "closed_set_member",
            RefusalSite::InvariantViolationValueObjectInvariant => "value_object_invariant",
            RefusalSite::InvariantViolationAdmitsDeclaredSet => "admits_declared_set",
            RefusalSite::InvariantViolationUndeclaredSet => "undeclared_set",
            RefusalSite::UnauthorizedTenantRequired => "tenant_required",
            RefusalSite::UnauthorizedRoleMismatch => "role_mismatch",
            RefusalSite::UnauthorizedCrossTenantReference => "cross_tenant_reference",
            RefusalSite::AttributeAbsentAbsentRead => "absent_read",
            RefusalSite::ProjectionAbsentAbsentRead => "absent_read",
        }
    }

    /// The row's declared `template`.
    pub fn template(&self) -> &'static str {
        match self {
            RefusalSite::NotFoundCreatingNoIdentity => "{command} creates a {aggregate} — pass {identity}:",
            RefusalSite::AlreadyExistsCreatingDuplicate => "{command} creates a {aggregate} that already exists — {identity} {offered}",
            RefusalSite::AlreadyExistsEntityDuplicate => "a {entity} already exists on {aggregate} — {identity} {offered}",
            RefusalSite::NotFoundActingNoIdentity => "{command} acts on an existing {aggregate} — pass {identity}:",
            RefusalSite::NotFoundRecordMissing => "no {aggregate} with {identity} {offered}",
            RefusalSite::NotFoundEntityParentNoIdentity => "{command} acts on a {aggregate}'s {entity} — pass {identity}:",
            RefusalSite::UnknownVerbEntityUnknown => "{aggregate} has no entity {entity}",
            RefusalSite::NotFoundEntityElementNoIdentity => "{command} acts on one {entity} — pass {identity}:",
            RefusalSite::NotFoundEntityElementMissing => "no {entity} with {identity} {wants} on {aggregate} {parent_id}",
            RefusalSite::NotFoundReferenceTargetMissing => "no {target} with {heads} {key}",
            RefusalSite::NotFoundReadModelReferenceMissing => "no {aggregate} with reference {offered}",
            RefusalSite::TypeMismatchReadModelObjectReference => "{query} refused — a reference is an id, and {field} arrived as an object",
            RefusalSite::UnknownVerbNoQuery => "{aggregate} has no query {query}",
            RefusalSite::UnknownVerbEntityQueryMissing => "{entity} has no query {query}",
            RefusalSite::UnknownVerbEntityHoldsNoList => "{aggregate} holds no list of {entity}",
            RefusalSite::UnknownVerbEntityNoCommand => "{entity} has no command {command}",
            RefusalSite::UnknownVerbAggregateNoCommand => "{aggregate} has no command {command}",
            RefusalSite::UnknownVerbPortNoOperation => "{port} has no operation {operation}",
            RefusalSite::UnknownVerbNoDomain => "no domain {domain} loaded (verb {verb})",
            RefusalSite::UnknownVerbNoReadModel => "{domain} has no read model {query}",
            RefusalSite::UnknownVerbNotFullyQualified => "{verb} is not a fully-qualified verb (Domain::Aggregate.Command)",
            RefusalSite::UnknownVerbNoAggregate => "{domain} has no aggregate {aggregate}",
            RefusalSite::LifecycleRefusedTransitionBlocked => "{command} refused — {field} is {current}, and {command} moves it only from {allowed}",
            RefusalSite::TypeMismatchValueObjectShape => "{name} is a {type} — pass its fields as an object, not {offered}",
            RefusalSite::TypeMismatchReferenceWrongShape => "{command} refused — a reference is an id, and {attribute} arrived as {offered}{known_by}",
            RefusalSite::TypeMismatchMultiFieldScalar => "{type} has multiple fields and cannot stand in for a scalar",
            RefusalSite::TypeMismatchCompositeIdentity => "{type} is a composite identity — an identity must have exactly one field",
            RefusalSite::TypeMismatchNumericField => "{type}.{field} expects {expected}, got {offered}",
            RefusalSite::TypeMismatchNonFiniteField => "{type}.{field} must be a finite number, got {offered}",
            RefusalSite::TypeMismatchIntegerRange => "{type}.{field} must fit in a 64-bit integer, got {offered}",
            RefusalSite::TypeMismatchPatternMismatch => "{type}.{field} must match {pattern}, got {offered}",
            RefusalSite::TypeMismatchArithmeticAmount => "{op} of {target} needs an Integer, got {offered}",
            RefusalSite::TypeMismatchArithmeticCurrent => "{op} of {target} needs an Integer {target}, got {offered}",
            RefusalSite::TypeMismatchArithmeticSharedField => "{op} of {target} needs a value object with one shared Integer field",
            RefusalSite::UnknownArgumentUnknownArgs => "{command} does not declare {unknown} — it takes {declared}",
            RefusalSite::AbsentArgumentAbsentArgs => "{command} was not given {absent} — it takes {declared}",
            RefusalSite::InvariantViolationClosedSetMember => "{type} admits {admitted} — got {offered}",
            RefusalSite::InvariantViolationValueObjectInvariant => "{name} invariant violated — {description} (given {offered})",
            RefusalSite::InvariantViolationAdmitsDeclaredSet => "{name} admits {admits} — {admitted} — got {offered}",
            RefusalSite::InvariantViolationUndeclaredSet => "{name} admits {admits}, which this chapter does not declare — a closed set is named Aggregate::SetName, and it must be one the bluebook actually holds",
            RefusalSite::UnauthorizedTenantRequired => "{query} declares authorize with tenant: {field} — pass {field}: to name which {field} this ask is scoped to",
            RefusalSite::UnauthorizedRoleMismatch => "{command} refused — role: {role}, and the caller stated {caller_role}",
            RefusalSite::UnauthorizedCrossTenantReference => "{aggregate} {field} is {tenant}, but {attribute} names a {target} whose own {target_field} is {other} — a cross-tenant reference",
            RefusalSite::AttributeAbsentAbsentRead => "{aggregate} {field} is absent on this record — declared, not optional, and added since it was written. Backfill it in a translation (backfill :{field}, default: ...), or declare it optional: true",
            RefusalSite::ProjectionAbsentAbsentRead => "{aggregate} {field} is not yet projected on this record — declared via projects :{field}, but no rebuild sweep has populated it. Run the sweep, or read {reference}.{remote_field} directly if this rule cannot wait",
        }
    }

    /// The row whose `site` is `name`, if any.
    pub fn from_name(name: &str) -> Option<RefusalSite> {
        RefusalSite::ALL.iter().copied().find(|row| row.site() == name)
    }

    /// `RefusalWording.render`: replace every `{key}` marker, in the
    /// order given. A template is read, never evaluated.
    pub fn render(&self, values: &[(&str, &str)]) -> String {
        let mut text = self.template().to_string();
        for (key, value) in values {
            text = text.replace(&format!("{{{key}}}"), value);
        }
        text
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_site_renders_with_no_leftover_placeholder() {
        for site in RefusalSite::ALL {
            let template = site.template();
            let mut keys: Vec<String> = Vec::new();
            let mut current: Option<String> = None;
            for ch in template.chars() {
                match (ch, current.as_mut()) {
                    ('{', _) => current = Some(String::new()),
                    ('}', Some(key)) => {
                        keys.push(key.clone());
                        current = None;
                    }
                    (_, Some(key)) => key.push(ch),
                    (_, None) => {}
                }
            }
            let dummies: Vec<(String, String)> = keys.iter().map(|k| (k.clone(), format!("<{k}>"))).collect();
            let pairs: Vec<(&str, &str)> = dummies.iter().map(|(k, v)| (k.as_str(), v.as_str())).collect();
            let rendered = site.render(&pairs);
            assert!(
                !rendered.contains('{') && !rendered.contains('}'),
                "{site:?} left an unrendered placeholder behind: {rendered:?}"
            );
        }
    }
}
