# frozen_string_literal: true

module Hecks
  module KernelCapabilities
    # The Rust source of the two capability modules. Extended onto `KernelCapabilities`.
    module Templates
      # One capability module, with `%{...}` where its parts go.
      RUST = <<~RUST
        // GENERATED by hecks project_kernel_capabilities from %<doc_line>s.
        // Do not hand-edit — re-run hecks project_kernel_capabilities instead.
        //
        %<header>s

        %<mods>s

        /// One variant per real %<kind>s the Ruby
        /// grammar admits, in the order %<doc_line>s declares them. Every match
        /// over this enum in the kernel (rust/src/kernel/expr.rs) is written
        /// WITHOUT a wildcard `_ =>` arm — see expr.rs's own header for why:
        /// a wildcard here would let a newly-admitted capability compile
        /// silently into a router that never calls the new file this same
        /// regeneration adds a `pub mod` line for above.
        #[derive(Debug, Clone, Copy, PartialEq, Eq)]
        pub enum %<enum_name>s {
        %<variants>s
        }

        impl %<enum_name>s {
            /// The `rust/src/kernel/%<directory>s/<name>.rs` file this
            /// variant names — `hecks measure_kernel_coverage`'s own existence
            /// check reads this, so the file-name spelling here is the ONE
            /// place that ever needs to change if a name is renamed.
            pub fn module_name(&self) -> &'static str {
                match self {
        %<arms>s
                }
            }

            pub const ALL: &'static [%<enum_name>s] = &[%<all>s];
        }
      RUST

      # @return [String] the whole `attribute_shapes/mod.rs`
      def shapes_module
        header = <<~HEADER.strip
          // Ground truth: Hecks::Runtime::Value::Coercion::SHAPES
          // (lib/hecks/runtime/value/coercion.rb) — the four branches
          // `for_attribute` itself takes, read directly rather than
          // re-derived here.
        HEADER
        render(header: header, enum_name: "AttributeShape", names: Hecks::Runtime::Value::Coercion::SHAPES,
               doc_line: "Coercion::SHAPES")
      end

      # @return [String] the whole `expression_operators/mod.rs`
      def operators_module
        header = <<~HEADER.strip
          // Ground truth: Hecks::Grammar.admitted_operators (lib/hecks/
          // grammar.rb), the SAME live-booted call hecks project_expression_tables
          // uses — grouped by the `category` field Evaluator::PROJECTION already
          // partitions comparison operators by (evaluator.rb).
        HEADER
        render(header: header, enum_name: "OperatorCategory", names: operator_categories,
               doc_line: "Grammar.admitted_operators's own `category` field")
      end

      # Renders one capability module: `pub mod` lines, the enum, and its `ALL`.
      #
      # @param header [String] the ground-truth comment
      # @param enum_name [String] `AttributeShape` or `OperatorCategory`
      # @param names [Array<String>] the capabilities, in declaration order
      # @param doc_line [String] where the capabilities are declared
      # @return [String] the Rust source
      def render(header:, enum_name:, names:, doc_line:)
        shapes = enum_name == "AttributeShape"
        format(RUST, header: header, doc_line: doc_line, enum_name: enum_name,
                     kind: shapes ? "attribute shape" : "expression-operator category",
                     directory: shapes ? "attribute_shapes" : "expression_operators",
                     mods: names.map { |name| "pub mod #{name};" }.join("\n"),
                     variants: names.map { |name| "    #{pascal(name)}," }.join("\n"),
                     arms: names.map { |name| "            #{enum_name}::#{pascal(name)} => #{name.to_s.inspect}," }.join("\n"),
                     all: names.map { |name| "#{enum_name}::#{pascal(name)}" }.join(", "))
      end

      # @param name [String, Symbol] a snake_case capability name
      # @return [String] the PascalCase Rust variant
      def pascal(name)
        name.to_s.split("_").map { |part| part[0].upcase + part[1..] }.join
      end
    end
  end
end
