#!/usr/bin/env python3
"""Build the comment-sweep worklist: select hand-written files that break the new limits,
attach public-name hints, and batch small files together. Writes worklist.json next to itself."""
import json, os, re, subprocess, sys, glob

ROOT = os.getcwd()
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "worklist.json")
PILOT = {
    "lib/hecks/runtime/saga_pending_dispatch.rb", "lib/hecks/storehouse.rb", "lib/hecks/ports/agent.rb",
    "spec/runtime/registry_saga_persistence_thread_safety_spec.rb", "rust/src/kernel/reference_lookup.rs",
    "rust/src/exemplar/reactions.rs", ".github/workflows/ci-rspec.yml",
}
SKIP_DIR = re.compile(r"^(docs/|rust/target/|rust/dist/|node_modules/|vendor/|spec/corpus/|packages/.*/node_modules/)")
RUBY_EXT = {".rb", ".rake", ".gemspec", ".ru", ".bluebook", ".hecksagon", ".world", ".adapter", ".port", ".behaviors"}
RUBY_NAMES = {"Rakefile", "Gemfile", "Guardfile"}
HIST = re.compile(r"\b(used to|previously|formerly|no longer|the old|until now|renamed|legacy|originally|has since|before this|BUG#?\d+|PR #\d+)\b", re.I)
ALLCAPS = re.compile(r"^\s*(#|//[/!]?)\s*[A-Z][A-Z' ]{6,}\b")

def ls():
    out = subprocess.run(["git", "ls-files"], capture_output=True, text=True, check=True).stdout
    return out.splitlines()

def kind_of(path, head):
    ext = os.path.splitext(path)[1]
    base = os.path.basename(path)
    if ext == ".rs": return "rust"
    if ext in RUBY_EXT or base in RUBY_NAMES: return "ruby"
    if ext in (".yml", ".yaml"): return "yaml"
    if ext in (".toml", ".sh"): return "hash"
    if ext == "" or base.startswith("."):
        if re.match(r"#!.*ruby", head): return "ruby"
        if re.match(r"#!.*(ba|z)?sh\b", head): return "hash"
        if base == "Dockerfile": return "hash"
    return None

def generated(kind, lines):
    top = "\n".join(lines[:8])
    if kind == "rust" and lines and lines[0].startswith("// GENERATED by"): return True
    if re.search(r"generated.{0,80}do not edit", top, re.I | re.S): return True
    return False

def is_comment(kind, line):
    s = line.strip()
    if kind == "rust": return s.startswith("//") and not re.match(r"//\s*TMPL:", s)
    if s.startswith("#!"): return False
    if re.match(r"#\s*(frozen_string_literal|encoding|coding|rubocop|shellcheck|yamllint|syntax=)", s): return False
    return s.startswith("#")

def doc_names():
    texts = []
    for pat in ["README.md", "docs/implemented/reference/**/*.md", "docs/implemented/guides/*.md", "docs/tools.md"]:
        for f in glob.glob(pat, recursive=True):
            try: texts.append(open(f, errors="ignore").read())
            except OSError: pass
    names = set()
    for t in texts:
        for m in re.finditer(r"\b[A-Z][A-Za-z0-9]+(?:::[A-Z][A-Za-z0-9]+)*\b", t):
            names.add(m.group(0).split("::")[-1])
    return names

def public_hint(kind, lines, docnames):
    found = []
    if kind == "ruby":
        for l in lines:
            m = re.match(r"\s*(class|module)\s+([A-Z][\w:]*)", l)
            if m and m.group(2).split("::")[-1] in docnames: found.append(m.group(2))
    elif kind == "rust":
        for l in lines:
            m = re.match(r"\s*pub\s+(struct|enum|trait|type)\s+([A-Z]\w*)", l)
            if m and m.group(2) in docnames: found.append(m.group(2))
    return sorted(set(found))[:12]

def main():
    docnames = doc_names()
    items, skipped = [], {"generated": 0, "clean": 0, "pilot": 0}
    for path in ls():
        if SKIP_DIR.match(path): continue
        if path in PILOT: skipped["pilot"] += 1; continue
        try: text = open(path, errors="ignore").read()
        except (OSError, IsADirectoryError): continue
        lines = text.split("\n")
        kind = kind_of(path, lines[0] if lines else "")
        if not kind: continue
        if generated(kind, lines): skipped["generated"] += 1; continue
        cl = mx = big = hist = caps = 0; run = 0; nonblank = 0
        for l in lines:
            if l.strip(): nonblank += 1
            if is_comment(kind, l):
                cl += 1; run += 1
                if HIST.search(l): hist += 1
                if ALLCAPS.match(l): caps += 1
            else:
                if run > 5: big += 1
                mx = max(mx, run); run = 0
        if run > 5: big += 1
        mx = max(mx, run)
        ratio = cl / nonblank if nonblank else 0
        if not (mx > 12 or big >= 1 or hist >= 1 or caps >= 1 or (cl >= 20 and ratio > 0.30)):
            skipped["clean"] += 1; continue
        items.append({"path": path, "kind": kind, "commentLines": cl, "maxBlock": mx,
                      "tmpl": bool(re.search(r"^\s*//\s*TMPL:", text, re.M)),
                      "publicNames": public_hint(kind, lines, docnames)})
    items.sort(key=lambda i: (i["kind"], i["path"]))
    batches, cur = [], None
    def flush():
        nonlocal cur
        if cur: batches.append(cur); cur = None
    for it in items:
        if it["commentLines"] > 450:
            flush(); batches.append({"kind": it["kind"], "files": [it]}); continue
        if cur and (cur["kind"] != it["kind"] or len(cur["files"]) >= 6 or
                    sum(f["commentLines"] for f in cur["files"]) + it["commentLines"] > 400):
            flush()
        if not cur: cur = {"kind": it["kind"], "files": []}
        cur["files"].append(it)
    flush()
    for n, b in enumerate(batches): b["id"] = n + 1
    json.dump({"batches": batches}, open(OUT, "w"))
    by = {}
    for it in items: by.setdefault(it["kind"], [0, 0]); by[it["kind"]][0] += 1; by[it["kind"]][1] += it["commentLines"]
    print("files selected:", len(items), "batches:", len(batches), "skipped:", skipped)
    for k, (n, c) in sorted(by.items()): print(f"  {k}: {n} files, {c} comment lines")
    print("  biggest single files:", sorted(((i["commentLines"], i["path"]) for i in items), reverse=True)[:5])

main()
