// Generated by hecks site site_projection.project_site. Do not edit.

// What the editor is built from: the project's Editor row, defaults filled. Change the row and run
// `hecks site site_projection.project_site`; with `--check` it fails when this file is out of date.

export const EDITOR = {
  title: "Pages editor",
  brand: "Layouts",
  logo: "",
  basePath: "/editor",
  ssoPath: "/editor/api/sso",
  login: "/admin-login",
  sessionCookie: "pages_editor",
  sessionMaxAge: 28800,
  flashMaxAge: 60,
  hostCookie: "pages_session",
  hostEnv: "PAGES_DOMAIN_SERVICE_URL",
  hostDefault: "http://127.0.0.1:4500",
  roles: ["Admin", "Owner"],
  mediaDir: "media",
  mediaMaxBytes: 5242880,
  pageSize: 25,
  /** Where a record is shown on the site, with `{key}`, `{kind}`, `{slug}` and `{id}`; null for no preview. */
  preview: null as string | null,
  accountPath: "/accounts/me",
  membersPath: "/members",
  rememberMs: 60000,
  timeoutMs: 5000,
} as const;
