require "fileutils"
require_relative "../../hecks"

module Hecks
  module CLI
    # The command behind `bin/project_cli` and `hecks project_cli`: writes a
    # command-line launcher beside each domain, named after its bluebook, so
    # `Hecks.bluebook "QualityControl"` in `qa/` becomes `qa/quality_control`.
    #
    # Each launcher is a dozen lines pinning one directory and handing over to
    # `Facade::CliRunner`; the surface itself is projected at the moment it runs,
    # so editing a chapter changes behaviour without regenerating anything.
    module ProjectCli
      # Build output and other trees under a root that hold no domain a caller means.
      IGNORED = %r{\A(rust|deploy|tmp|coverage)/}

      module_function

      # `remove_stale_bin` deletes `root/bin/<name>`, where a launcher for the same
      # chapter would otherwise linger as a second front door.
      def call(argv, program:, root:, remove_stale_bin: true)
        wanted = argv.empty? ? domains(root) : argv.map { |path| path.delete_prefix("#{root}/").chomp("/") }

        wanted.each do |path|
          name  = bluebook_name(root, path) or next
          snake = Naming.snake(name)
          file  = File.join(root, path, snake)

          File.write(file, launcher(path, name, program))
          FileUtils.chmod("+x", file)
          FileUtils.rm_f(File.join(root, "bin", snake)) if remove_stale_bin

          puts "  #{path}/#{snake}  ->  #{name}"
        end
      end

      def domains(root)
        folder = Adapters::Folder.new
        Dir.glob(File.join(root, "**/*.hecksagon"))
           .map { |path| folder.domain_root(File.dirname(path)) }
           .compact
           .map { |path| path.delete_prefix("#{root}/") }
           .grep_v(IGNORED)
           .uniq.sort
      end

      # Reads the name from `Hecks.bluebook "…"` rather than the directory, so a
      # domain using `formerly_known_as` gets a launcher under its current name.
      def bluebook_name(root, path)
        Hecks.boot(File.join(root, path), install_facade: false).registry.bluebooks.keys.first
      rescue StandardError => e
        warn "  #{path}: cannot boot — #{e.message.lines.first.strip}"
        nil
      end

      def launcher(path, name, program)
        snake = Naming.snake(name)
        up    = "../" * path.count("/").succ

        <<~RUBY
          #!/usr/bin/env ruby

          # #{name}'s command line — GENERATED by #{program}. Do not edit.
          #
          # A launcher, not a CLI: the verbs, their arguments and their refusals are
          # projected from the bluebook beside it every time this runs, so a change
          # to the chapter shows up here without re-minting anything.
          #
          #   #{path}/#{snake}                  every verb, and every question
          #   #{path}/#{snake} <verb> --help    what it wants, and how it refuses

          $LOAD_PATH.unshift File.expand_path("#{up}lib", __dir__)

          require "hecks"

          runtime = begin
            Hecks.boot(__dir__, install_facade: false)
          rescue StandardError => e
            abort "cannot open #{name}: \#{e.message.lines.first.strip}"
          end

          text, status = Hecks::Facade::CliRunner.call(
            runtime: runtime, argv: ARGV, program: "#{path}/#{snake}"
          )
          status.zero? ? puts(text) : abort(text)
        RUBY
      end
    end
  end
end
