# frozen_string_literal: true

require "fileutils"
require "json"
require "tmpdir"

module Hecks
  module RustBuild
    class ProjectRust
      # Generates a domain's Rust by running `hecks-codegen full` on IR the caller built from the
      # live registry, into a scratch directory, then copies only the files whose bytes changed
      # into `src/generated/`. An unchanged file keeps its mtime, so Cargo does not rebuild.
      class CodegenRun
        META_LABEL = "the self-hosted language (lib/hecks/language/bluebook)"

        # One chapter's IR, generated into its own module.
        Chapter = Struct.new(:mod_name, :label, :ir)

        # The `hecks-codegen` crate: the workspace's own copy when it carries one (a packaged
        # workspace does), otherwise the checkout's, so a scratch crate holding only the generated
        # tree still finds it.
        #
        # @param rust_dir [String] the workspace being generated into
        # @return [String] the crate's directory
        def self.crate_dir(rust_dir)
          own = File.join(rust_dir, "codegen")
          File.directory?(own) ? own : File.join(RustBuild::ROOT, "rust/codegen")
        end

        # Where Cargo puts the binary: under `CARGO_TARGET_DIR` when a build sets it (a copy of the
        # packaged workspace does, so nothing is written into the installed gem), else in the crate.
        #
        # @param rust_dir [String] the workspace being generated into
        # @param env [#fetch] the environment Cargo will run with
        # @return [String] the binary's path
        def self.binary(rust_dir, env: ENV)
          target = env.fetch("CARGO_TARGET_DIR") { File.join(crate_dir(rust_dir), "target") }
          File.join(target, "debug/hecks-codegen")
        end

        # @param rust_dir [String] the workspace being generated into
        # @param out_root [String] the crate's `src/generated`
        # @param target [Chapter] the domain being projected
        # @param chapters [Array<Chapter>] every other bluebook the target attached
        # @param meta [Hash] the self-hosted language's IR
        def initialize(rust_dir:, out_root:, target:, chapters:, meta:)
          @rust_dir = rust_dir
          @out_root = out_root
          @target = target
          @chapters = chapters
          @meta = meta
        end

        # @return [void]
        # @raise [Failure] when `hecks-codegen` cannot be built or exits non-zero
        def call
          build_binary
          Dir.mktmpdir("hecks-codegen-full") do |tmp|
            stage = File.join(tmp, "generated")
            FileUtils.mkdir_p(stage)
            generate_meta(stage, tmp)
            generate_target(stage, tmp)
            sync(stage)
          end
        end

        private

        def build_binary
          dir = self.class.crate_dir(@rust_dir)
          return if system("cargo", "build", "--quiet", chdir: dir, out: $stdout, err: $stderr)

          raise Failure, "hecks project_rust: cargo build failed in #{dir} — run it there directly to see why"
        end

        def generate_meta(stage, tmp)
          ir_path = write_ir(tmp, "meta", @meta)
          run("full", stage, "meta", META_LABEL, ir_path)
          write_sidecars(File.join(stage, "meta"), @meta, META_LABEL)
        end

        def generate_target(stage, tmp)
          args = [stage, @target.mod_name, @target.label, write_ir(tmp, @target.mod_name, @target.ir)]
          @chapters.each do |chapter|
            args.push(chapter.mod_name, chapter.label, write_ir(tmp, chapter.mod_name, chapter.ir))
          end
          run("full", *args)
          [@target, *@chapters].each do |chapter|
            write_sidecars(File.join(stage, chapter.mod_name), chapter.ir, chapter.label)
          end
        end

        def write_ir(tmp, name, tree)
          path = File.join(tmp, "#{name}_ir.json")
          File.write(path, JSON.pretty_generate(tree))
          path
        end

        # `ir.json` is what `rust/host` reads at runtime, and `metadata.rs` embeds the same text;
        # the codegen binary writes neither.
        def write_sidecars(mod_dir, tree, label)
          text = JSON.pretty_generate(tree)
          File.write(File.join(mod_dir, "ir.json"), text)
          File.write(File.join(mod_dir, "metadata.rs"), <<~RUST)
            // GENERATED by hecks project_rust — #{label}'s own canonical IR,
            // embedded for runtime self-description. Not read by any dispatch
            // function in this module — introspection only.
            pub const IR_JSON: &str = #{RustProjection::Projector.rust_string_literal(text)};
          RUST
        end

        def run(*args)
          return if system(self.class.binary(@rust_dir), *args, out: $stdout, err: $stderr)

          raise Failure, "hecks project_rust: hecks-codegen #{args.first} failed"
        end

        # Each module directory is tracked, so a file an earlier run wrote and this one did not
        # (a removed aggregate) is pruned. Pruning waits for the whole copy to succeed: after a
        # failure, the files not yet reached would look like orphans and be deleted.
        def sync(stage)
          Dir.children(stage).sort.each do |name|
            source = File.join(stage, name)
            dest = File.join(@out_root, name)
            RustProjection::WriteIfChanged.push_directory(dest)
            copy_changed(source, dest)
            RustProjection::WriteIfChanged.pop_and_prune(dest)
          end
        end

        def copy_changed(source, dest)
          Dir.children(source).sort.each do |file|
            path = File.join(dest, file)
            wrote = RustProjection::WriteIfChanged.call(path, File.read(File.join(source, file), encoding: "UTF-8"))
            puts(wrote ? "wrote #{path}" : "#{path} unchanged")
          end
        end
      end
    end
  end
end
