# frozen_string_literal: true

module Hecks
  module RustBuild
    class ProjectRust
      # Writes `src/generated/mod.rs`: a `pub mod` per generated directory, the feature-gated
      # `active` re-export of the selected domain, and a `compile_error!` for each pair of
      # non-default domain features enabled together.
      class RootMod
        # @param file [IO] where the module is written
        # @param directories [Array<String>] every directory under `src/generated`
        # @param domains [Array<String>] the directories that carry their own `merged.rs`
        # @param default [String] the domain this run generated, whose feature is the default
        def initialize(file, directories, domains, default)
          @file = file
          @directories = directories
          @domains = domains
          @default = default
        end

        # @return [void]
        def write
          banner
          modules
          active_notes
          reexports
          conflict_guards
        end

        private

        def banner
          @file.puts "// GENERATED by hecks project_rust — re-run it to refresh this list."
          @file.puts "//"
          @file.puts "// BUG#25 — every DOMAIN (an entry in `domains`, below: a directory"
          @file.puts "// carrying its own merged.rs and therefore its own Cargo feature) is"
          @file.puts "// declared behind that SAME feature, so a broken or absent domain's"
          @file.puts "// generated code is never even compiled into a build that selects a"
          @file.puts "// DIFFERENT domain — `cargo build --features waybill` used to pull in"
          @file.puts "// every OTHER domain's `pub mod` unconditionally, so one domain's own"
          @file.puts "// non-compiling generated code (a `has_many` field, before this fix)"
          @file.puts "// broke every feature's build, not just its own. A shared FRAMEWORK"
          @file.puts "// chapter (governance/identity — no merged.rs of its own, so absent"
          @file.puts "// from `domains`) stays unconditional: it has no single feature of its"
          @file.puts "// own to gate behind, and is compiled in by whichever domain(s) attach"
          @file.puts "// it via `attaches`."
        end

        def modules
          @directories.each do |name|
            @file.puts "#[cfg(feature = #{name.inspect})]" if @domains.include?(name)
            @file.puts "pub mod #{name};"
          end
        end

        def active_notes
          @file.puts
          @file.puts "// `active` is whichever ONE domain's own merged Store/dispatch table"
          @file.puts "// is selected by Cargo feature (rust/Cargo.toml, kept in sync with this"
          @file.puts "// list by hecks project_rust) — kernel/cli.rs imports"
          @file.puts "// `crate::generated::active::{dispatch_by_name, Store, ...}` unchanged"
          @file.puts "// no matter which domain that resolves to."
          @file.puts "//"
          @file.puts "// DOMAIN FEATURES ARE MUTUALLY EXCLUSIVE (R5) — Cargo has no native"
          @file.puts "// concept of that, and `default = [#{@default.inspect}]` in"
          @file.puts "// Cargo.toml stays enabled unless a build passes"
          @file.puts "// `--no-default-features`, so a plain `cargo build --features banking`"
          @file.puts "// used to enable BOTH the default domain's feature and banking's,"
          @file.puts "// producing two `pub use ... as active;` imports and a hard E0252."
          @file.puts "// Fixed two ways below, entirely mechanically from `domains`/"
          @file.puts "// `target_mod_name` (this run's new default) — never hand-maintained:"
          @file.puts "//"
          @file.puts "//   1. THE DEFAULT DOMAIN'S OWN re-export backs off whenever any OTHER"
          @file.puts "//      domain feature is also enabled, so it never contends for `active`"
          @file.puts "//      by accident — `cargo build --features banking` (still implicitly"
          @file.puts "//      carrying the default feature) now resolves to banking alone,"
          @file.puts "//      same as if `--no-default-features` had been passed explicitly."
          @file.puts "//   2. Two NON-default domain features enabled TOGETHER (a genuine,"
          @file.puts "//      not-accidental conflict — nothing makes that combination"
          @file.puts "//      meaningful) still fail the build, but with an explicit"
          @file.puts "//      `compile_error!` naming both features instead of a cryptic"
          @file.puts "//      \"defined multiple times\"."
        end

        def reexports
          @domains.each do |name|
            other_domains = @domains - [name]
            if name == @default && !other_domains.empty?
              guard = other_domains.map { |o| "feature = #{o.inspect}" }.join(", ")
              @file.puts "#[cfg(all(feature = #{name.inspect}, not(any(#{guard}))))]"
            else
              @file.puts "#[cfg(feature = #{name.inspect})]"
            end
            @file.puts "pub use #{name}::merged as active;"
          end
        end

        def conflict_guards
          non_default_domains = @domains - [@default]
          if non_default_domains.size > 1
            @file.puts
            @file.puts "// Explicit conflict guard — see point 2 above. Only fires when TWO"
            @file.puts "// non-default domain features are both turned on; the default"
            @file.puts "// domain's own feature never reaches here (point 1 already excludes"
            @file.puts "// it whenever any other domain feature is present)."
            non_default_domains.combination(2).each do |a, b|
              @file.puts "#[cfg(all(feature = #{a.inspect}, feature = #{b.inspect}))]"
              # Plain `a`/`b`/`domains.join` here, never `.inspect` — this whole
              # line already sits inside one Rust string literal
              # (`compile_error!("...")`), and `.inspect`'s own quoted form
              # would nest unescaped double quotes and produce invalid Rust.
              @file.puts "compile_error!(\"domain features are mutually exclusive — enable only one of: #{@domains.join(', ')} " \
                         "(both #{a} and #{b} are enabled)\");"
            end
          end
        end
      end
    end
  end
end
